// Metadata that is safe to publish for the sources currently used by the app.
// Missing bibliographic facts stay null instead of being inferred from a URL.
export const BIBLIOGRAPHY_METADATA = {
  panXu: {
    creators: ['Pan & Xu'],
    sourceType: 'journal article',
    discipline: 'comparative politics',
    publisher: 'University of Chicago Press',
    confidence: 'high',
    description: 'Research on multidimensional political preferences and ideological space in China.',
  },
  sepSocialism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of socialist traditions, arguments, and internal disagreements.',
  },
  sepLiberalism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of liberal approaches to liberty, property, authority, and the state.',
  },
  sepLibertarianism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of individual liberty, coercion, property, and market arguments.',
  },
  sepConservatism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of tradition, authority, gradual change, and paternalism.',
  },
  sepReligionPolitics: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory and philosophy of religion',
    confidence: 'high',
    description: 'Scholarly overview of religious reasons, secularism, political authority, coercive law, and religious pluralism.',
  },
  sepNationalism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of civic, liberal, conservative, and ethnic forms of nationalism.',
  },
  torontoConstitutionalTheocracy: {
    institution: 'University of Toronto Department of Political Science',
    sourceType: 'scholarly book profile',
    discipline: 'comparative constitutional law and religion',
    confidence: 'high',
    description: 'Comparative research on constitutional theocracy, religious constitutions, courts, and the boundary between constitutionalism and theocracy.',
  },
  oxfordStateReligionFreedom: {
    creators: ['Oxford Research Encyclopedia authors'],
    sourceType: 'reference chapter',
    discipline: 'comparative politics and religion',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Comparative research on state religion, religious freedom, identity regimes, constitutions, secularism, and intergroup conflict.',
  },
  oxfordIranTheocraticCriminalLaw: {
    creators: ['Oxford Academic chapter authors'],
    sourceType: 'scholarly book chapter',
    discipline: 'Iranian constitutional law and religion',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Analysis of the theological, constitutional, and legal framework of Iran’s constitutional theocracy.',
  },
  iconStateReligionTheocracy: {
    creators: ['International Journal of Constitutional Law authors'],
    sourceType: 'journal article',
    discipline: 'constitutional law and political theory',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Comparative constitutional analysis distinguishing political atheism, religious neutrality, multiculturalism, state churches, and theocracy.',
  },
  cambridgeMaimonidesTheocracy: {
    creators: ['Cambridge Elements authors'],
    sourceType: 'scholarly element',
    discipline: 'Jewish political thought and comparative religion',
    publisher: 'Cambridge University Press',
    confidence: 'high',
    description: 'Historical and philosophical study of divine rule, Jewish political thought, and the relationship between religious law and political authority.',
  },
  perseusJosephusTheocracy: {
    creators: ['Flavius Josephus'],
    sourceType: 'primary-text archive',
    discipline: 'ancient Jewish political thought',
    confidence: 'medium',
    description: 'Primary-text anchor for Josephus’s use of the term theocracy and his account of law and divine authority.',
    languages: ['Greek', 'English translation'],
  },
  waqfeyaMawardiOrdinances: {
    creators: ['Al-Mawardi'],
    institution: 'Waqfeya',
    sourceType: 'Arabic digital-library record',
    discipline: 'classical Islamic public law',
    confidence: 'medium',
    description: 'Arabic digital-library record for a classical work on the imam, offices, administration, judges, and governance.',
    languages: ['Arabic', 'English translation record'],
  },
  nsarchiveKhomeini1979: {
    creators: ['Ruhollah Khomeini'],
    institution: 'George Washington University National Security Archive',
    sourceType: 'archival primary-source record',
    discipline: 'Iranian political history and religion',
    confidence: 'high',
    description: 'Archival record for Khomeini’s public claims about the Islamic Republic and religiously grounded political legitimacy.',
  },
  constituteIran1989: {
    institution: 'Constitute Project',
    sourceType: 'constitutional text repository',
    discipline: 'comparative constitutional law',
    confidence: 'high',
    description: 'Constitutional text showing the interaction of Islamic criteria, religious offices, elected institutions, popular sovereignty, and the Guardian Council.',
  },
  vaticanStateBodies: {
    institution: 'Vatican City State',
    sourceType: 'official government information',
    discipline: 'constitutional government and religion',
    confidence: 'high',
    description: 'Official description of Vatican City’s governmental structure and the authority of the sovereign pontiff.',
  },
  bpbMonarchy: {
    institution: 'Bundeszentrale für politische Bildung',
    sourceType: 'institutional lexicon',
    discipline: 'comparative government and political theory',
    confidence: 'high',
    description: 'German-language institutional definition distinguishing monarchic rule from parliamentary and constitutional monarchy.',
    languages: ['German'],
  },
  perseeFrenchConstitutionalMonarchy: {
    creators: ['Persée article authors'],
    sourceType: 'academic journal article',
    discipline: 'French constitutional history',
    confidence: 'high',
    description: 'French-language academic history of constitutional-monarchical doctrines and practice from 1830 to 1900.',
    languages: ['French'],
  },
  oxfordConstitutionalMonarchy: {
    creators: ['American Journal of Jurisprudence author'],
    sourceType: 'journal article',
    discipline: 'constitutional law and political theory',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Normative analysis of hereditary office, democratic legitimacy, political authority, and constitutional monarchy.',
  },
  oxfordMonarchyConstitution: {
    creators: ['The Monarchy and the Constitution author'],
    sourceType: 'scholarly book',
    discipline: 'constitutional history and UK politics',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Scholarly history of monarchy, succession, constitutional rules, democracy, finance, and constitutional crisis in the United Kingdom.',
  },
  ukParliamentCrown: {
    institution: 'UK Parliament',
    sourceType: 'official parliamentary explainer',
    discipline: 'constitutional law and government',
    confidence: 'high',
    description: 'Official account of the contemporary constitutional relationship between the Crown and Parliament.',
  },
  journalDemocraticMonarchies: {
    creators: ['Journal of Democracy authors'],
    sourceType: 'journal article',
    discipline: 'comparative politics',
    publisher: 'National Endowment for Democracy',
    confidence: 'high',
    description: 'Comparative analysis of democratic parliamentary monarchies and the relationship between hereditary and elected legitimacy.',
  },
  bpbNationalism: {
    institution: 'Bundeszentrale für politische Bildung',
    sourceType: 'institutional lexicon',
    discipline: 'political theory and modern history',
    confidence: 'high',
    description: 'German-language institutional definition of nationalism and the elevation of ethnic community, language, culture, history, people, and territory.',
    languages: ['German'],
  },
  cambridgeKohnDichotomy: {
    creators: ['Nationalities Papers authors'],
    sourceType: 'journal article',
    discipline: 'nationalism studies and comparative politics',
    publisher: 'Cambridge University Press',
    confidence: 'high',
    description: 'Comparative analysis of the civic–ethnic distinction as an ideal type rather than a categorical geographic classification.',
  },
  oxfordConstitutionalPatriotism: {
    creators: ['International Journal of Constitutional Law authors'],
    sourceType: 'journal article',
    discipline: 'constitutional theory and citizenship',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Scholarly analysis of constitutional patriotism, civic nationalism, citizenship, belonging, and exclusion.',
  },
  coeDemocraticCitizenship: {
    institution: 'Council of Europe',
    sourceType: 'institutional charter and educational framework',
    discipline: 'human rights and democratic citizenship',
    confidence: 'high',
    description: 'Institutional framework connecting democratic citizenship with rights, responsibilities, diversity, participation, democracy, and rule of law.',
  },
  ohchrMinorityRights: {
    institution: 'United Nations Office of the High Commissioner for Human Rights',
    sourceType: 'human-rights guidance',
    discipline: 'international human rights and minority protection',
    confidence: 'high',
    description: 'International standards and guidance on ethnic, national, linguistic, and religious minorities, citizenship, participation, equality, and non-discrimination.',
  },
  ushmmNurembergLaws: {
    institution: 'United States Holocaust Memorial Museum',
    sourceType: 'museum encyclopedia and primary-documentary collection',
    discipline: 'modern history and Holocaust studies',
    confidence: 'high',
    description: 'Historical documentation of racial citizenship, anti-Jewish legislation, and the legal transformation of German democracy into dictatorship.',
  },
  vdem: {
    institution: 'Varieties of Democracy Institute',
    sourceType: 'dataset codebook',
    discipline: 'comparative politics',
    confidence: 'high',
    description: 'Operational definitions for liberal democracy, civil liberties, rule of law, and executive constraints.',
  },
  wvs: {
    institution: 'World Values Survey Association',
    sourceType: 'survey documentation',
    discipline: 'political behaviour',
    confidence: 'high',
    description: 'Empirical documentation for traditional/secular-rational and survival/self-expression value dimensions.',
  },
  ches: {
    institution: 'Chapel Hill Expert Survey',
    sourceType: 'survey codebook',
    discipline: 'comparative politics',
    confidence: 'high',
    description: 'Expert-coded party-position scales covering economic, lifestyle, religion, immigration, multiculturalism, and decentralization issues.',
  },
  manifesto: {
    institution: 'Manifesto Project',
    sourceType: 'coding handbook',
    discipline: 'comparative politics',
    confidence: 'high',
    description: 'Methodology for comparing party manifestos across economic, social, political-system, and international positions.',
  },
  foreignPolicy: {
    creators: ['Oxford research authors'],
    sourceType: 'journal article',
    discipline: 'foreign policy',
    publisher: 'Oxford University Press',
    confidence: 'medium',
    description: 'Comparative research on party positions toward security, alliances, multilateralism, and intervention.',
  },
  openTextbook: {
    creators: ['Open textbook contributors'],
    institution: 'Open Textbook Library',
    sourceType: 'open textbook',
    discipline: 'political theory',
    confidence: 'medium',
    description: 'Comparative introduction to political ideologies and worldviews, including liberalism, conservatism, socialism, anarchism, nationalism, populism, fascism, Islamism, Confucianism, environmentalism, and feminism.',
  },
  sepAnarchism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of philosophical distinctions among anarchist arguments and traditions.',
  },
  sepFascism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Conceptual and historical analysis of fascist ideology and its variants.',
  },
  sepFeminism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of feminist philosophical traditions and disagreements.',
  },
  sepPopulism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Conceptual overview of debates about populism as ideology, discourse, and political style.',
  },
  sepConfucianism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'comparative political thought',
    confidence: 'high',
    description: 'Scholarly overview of Chinese political traditions, including Confucian accounts of order and governance.',
  },
  sepLegalism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'comparative political thought',
    confidence: 'high',
    description: 'Historical scholarship on the fa tradition and classical Chinese statecraft.',
  },
  sepMedieval: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'history of political thought',
    confidence: 'high',
    description: 'Historical overview of medieval concepts of kingship, republicanism, law, and authority.',
  },
  ushmmFascism: {
    institution: 'United States Holocaust Memorial Museum',
    sourceType: 'museum encyclopedia',
    discipline: 'modern history',
    confidence: 'high',
    description: 'Historical context for fascism and the Nazi regime, used critically for contextualization and warnings.',
  },
  panAfricanism: {
    creators: ['African Affairs authors'],
    sourceType: 'journal article',
    discipline: 'comparative political thought',
    publisher: 'Oxford University Press',
    confidence: 'medium',
    description: 'Scholarly treatment of Pan-African political thought and transnational solidarity.',
  },
  oxfordChristianDemocracyEurope: {
    creators: ['Oxford Research Encyclopedia authors'],
    sourceType: 'reference chapter',
    discipline: 'Christian democracy and European politics',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Comparative account of Christian democracy’s religious values, political economy, parties, welfare institutions, and role in European integration.',
  },
  cambridgeChristianDemocracy: {
    creators: ['Cambridge History authors'],
    sourceType: 'history-of-political-thought chapter',
    discipline: 'political thought and religion',
    publisher: 'Cambridge University Press',
    confidence: 'high',
    description: 'Historical account of Christian democracy’s response to mass politics, socialism, secularism, and pluralist democracy.',
  },
  oxfordSocialCatholicismChristianDemocracy: {
    creators: ['Oxford Academic authors'],
    sourceType: 'scholarly book chapter',
    discipline: 'Catholic social thought and political history',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Study of social Catholicism, personalism, organicism, laity, secularization, and the intellectual formation of Christian democracy.',
  },
  oxfordChristianDemocratDecade: {
    creators: ['Oxford Academic authors'],
    sourceType: 'scholarly book chapter',
    discipline: 'postwar European political history',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Historical research on postwar Christian-democratic parties, reconstruction, social security, and the European political order.',
  },
  vaticanRerumNovarum: {
    creators: ['Pope Leo XIII'],
    institution: 'Holy See',
    sourceType: 'primary social encyclical',
    discipline: 'Catholic social thought',
    confidence: 'high',
    description: 'Primary social-encyclical source on labor, private property, worker associations, social duties, and limits of state intervention.',
    languages: ['Latin', 'English translation'],
  },
  vaticanQuadragesimoAnno: {
    creators: ['Pope Pius XI'],
    institution: 'Holy See',
    sourceType: 'primary social encyclical',
    discipline: 'Catholic social thought and political economy',
    confidence: 'high',
    description: 'Primary social-encyclical source on social order, economic power, occupational associations, and subsidiarity-related reasoning.',
    languages: ['Latin', 'English translation'],
  },
  vaticanSocialDoctrineCompendium: {
    creators: ['Pontifical Council for Justice and Peace'],
    institution: 'Holy See',
    sourceType: 'institutional compendium',
    discipline: 'Catholic social thought and public ethics',
    confidence: 'high',
    description: 'Institutional synthesis of human dignity, solidarity, subsidiarity, the common good, rights, family, work, and political community.',
    languages: ['English translation'],
  },
  euRobertSchuman: {
    creators: ['European Union historical services'],
    institution: 'European Union',
    sourceType: 'official historical profile',
    discipline: 'European political history and integration',
    confidence: 'high',
    description: 'Official historical source on Robert Schuman’s Christian-democratic statesmanship, reconciliation, and proposal for shared European institutions.',
  },
  adenauerHouse: {
    institution: 'Stiftung Bundeskanzler-Adenauer-Haus',
    sourceType: 'institutional biography and archive',
    discipline: 'German political history',
    confidence: 'high',
    description: 'Institutional biography and archive source for Konrad Adenauer’s democratic reconstruction and political work.',
  },
  bpbChristianDemocraticCVP: {
    institution: 'Bundeszentrale für politische Bildung',
    sourceType: 'political lexicon entry',
    discipline: 'German and Swiss political history',
    confidence: 'high',
    description: 'German institutional reference on confessional party origins, opening to non-Catholics, Christian social teaching, and the Swiss Christian-democratic tradition.',
    languages: ['German'],
  },
  oxfordPortugalPoliticalCatholicism: {
    creators: ['Oxford Academic authors'],
    sourceType: 'scholarly book chapter',
    discipline: 'Portuguese political and religious history',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Historical research on Portuguese Catholic political activity and the distinct development of Christian-democratic alternatives after authoritarian rule.',
  },
  comparativeChristianDemocracy: {
    creators: ['Evelyne Huber, Charles Ragin, John D. Stephens'],
    institution: 'Stanford Center for the Study of Poverty and Inequality',
    sourceType: 'comparative political-economy paper',
    discipline: 'comparative politics and welfare states',
    confidence: 'high',
    description: 'Comparative study distinguishing Christian-democratic and social-democratic institutional patterns, including federalism, welfare, and subsidiarity.',
  },
  oxfordLiberationTheologies: {
    creators: ['Oxford Research Encyclopedia authors'],
    sourceType: 'reference chapter',
    discipline: 'religion, theology, and politics',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Scholarly account of liberation theologies as contextual projects joining social analysis, scripture, religious history, and responses to particular forms of oppression.',
  },
  oxfordChristianSocialism: {
    creators: ['Oxford Handbook authors'],
    sourceType: 'reference chapter',
    discipline: 'Christian thought and political economy',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Historical scholarship on Christian thought, capitalism, socialism, Christian social teaching, and nineteenth-century debates.',
  },
  cambridgeReligionOriginsSocialism: {
    creators: ['Gareth Stedman Jones'],
    sourceType: 'scholarly book chapter',
    discipline: 'religion and history of socialism',
    publisher: 'Cambridge University Press',
    confidence: 'high',
    description: 'Comparative historical study challenging a simple opposition between religion and socialism and tracing religious dimensions in the origins of socialist politics.',
  },
  jstorChristianSocialistRevival: {
    creators: ['Anthony A. J. Williams'],
    sourceType: 'scholarly monograph record',
    discipline: 'British religious and political history',
    confidence: 'high',
    description: 'Scholarly history of British Christian socialist thought, its religious grounds, institutions, and relationship to socialism and the churches.',
  },
  vaticanLiberationInstruction: {
    creators: ['Congregation for the Doctrine of the Faith'],
    institution: 'Holy See',
    sourceType: 'primary doctrinal instruction',
    discipline: 'Catholic theology and political ethics',
    confidence: 'high',
    description: 'Primary institutional critique of forms of liberation theology that adopt Marxist concepts insufficiently critically, while affirming social concern and Christian freedom.',
    languages: ['Italian', 'English translation', 'Portuguese translation', 'Spanish translation'],
  },
  vaticanChristianFreedomLiberation: {
    creators: ['Congregation for the Doctrine of the Faith'],
    institution: 'Holy See',
    sourceType: 'primary doctrinal instruction',
    discipline: 'Catholic theology and political ethics',
    confidence: 'high',
    description: 'Primary institutional account of Christian freedom, social justice, and liberation following the 1984 instruction.',
    languages: ['Italian', 'English translation'],
  },
  celamMedellin: {
    creators: ['Consejo Episcopal Latinoamericano y Caribeño'],
    institution: 'CELAM',
    sourceType: 'institutional conference history',
    discipline: 'Latin American religious and political history',
    confidence: 'high',
    description: 'Institutional historical record for the Medellín conference and Latin American episcopal engagement with social transformation after Vatican II.',
    languages: ['Spanish'],
  },
  catholicWorkerMovement: {
    institution: 'Catholic Worker Movement',
    sourceType: 'movement history and archive link',
    discipline: 'religion, pacifism, and social movements',
    confidence: 'medium',
    description: 'Movement-maintained historical account of Dorothy Day, hospitality houses, voluntary poverty, worker solidarity, and pacifism.',
  },
  kingPoorPeoplesCampaign: {
    institution: 'Martin Luther King, Jr. Research and Education Institute',
    sourceType: 'institutional historical record',
    discipline: 'civil rights and economic justice movements',
    confidence: 'high',
    description: 'Institutional historical record of the Poor People’s Campaign and its demands for jobs, income, and economic justice through nonviolent protest.',
  },
  oxfordLiberationLegacy: {
    institution: 'University of Oxford, Faculty of Theology and Religion',
    sourceType: 'institutional research overview',
    discipline: 'liberation theology and political thought',
    confidence: 'medium',
    description: 'Institutional research overview of liberation theology’s intellectual and political legacy, used for contextual synthesis rather than quotation.',
  },
};

export const BIBLIOGRAPHY_ACCESS_DATE = '2026-09-13';
