// Metadata that is safe to publish for the sources currently used by the app.
// Missing bibliographic facts stay null instead of being inferred from a URL.
export const BIBLIOGRAPHY_METADATA = {
  panXu: {
    creators: ['Pan & Xu'],
    sourceType: 'journal article',
    discipline: 'comparative politics',
    publisher: 'University of Chicago Press',
    confidence: 'high',
    description: 'Research on multidimensional political preferences and ideological space in China.',
  },
  sepSocialism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of socialist traditions, arguments, and internal disagreements.',
  },
  sepLiberalism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of liberal approaches to liberty, property, authority, and the state.',
  },
  sepLibertarianism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of individual liberty, coercion, property, and market arguments.',
  },
  sepConservatism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of tradition, authority, gradual change, and paternalism.',
  },
  sepReligionPolitics: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory and philosophy of religion',
    confidence: 'high',
    description: 'Scholarly overview of religious reasons, secularism, political authority, coercive law, and religious pluralism.',
  },
  sepNationalism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of civic, liberal, conservative, and ethnic forms of nationalism.',
  },
  bpbNationalism: {
    institution: 'Bundeszentrale für politische Bildung',
    sourceType: 'institutional lexicon',
    discipline: 'political theory and modern history',
    confidence: 'high',
    description: 'German-language institutional definition of nationalism and the elevation of ethnic community, language, culture, history, people, and territory.',
    languages: ['German'],
  },
  cambridgeKohnDichotomy: {
    creators: ['Nationalities Papers authors'],
    sourceType: 'journal article',
    discipline: 'nationalism studies and comparative politics',
    publisher: 'Cambridge University Press',
    confidence: 'high',
    description: 'Comparative analysis of the civic–ethnic distinction as an ideal type rather than a categorical geographic classification.',
  },
  oxfordConstitutionalPatriotism: {
    creators: ['International Journal of Constitutional Law authors'],
    sourceType: 'journal article',
    discipline: 'constitutional theory and citizenship',
    publisher: 'Oxford University Press',
    confidence: 'high',
    description: 'Scholarly analysis of constitutional patriotism, civic nationalism, citizenship, belonging, and exclusion.',
  },
  coeDemocraticCitizenship: {
    institution: 'Council of Europe',
    sourceType: 'institutional charter and educational framework',
    discipline: 'human rights and democratic citizenship',
    confidence: 'high',
    description: 'Institutional framework connecting democratic citizenship with rights, responsibilities, diversity, participation, democracy, and rule of law.',
  },
  ohchrMinorityRights: {
    institution: 'United Nations Office of the High Commissioner for Human Rights',
    sourceType: 'human-rights guidance',
    discipline: 'international human rights and minority protection',
    confidence: 'high',
    description: 'International standards and guidance on ethnic, national, linguistic, and religious minorities, citizenship, participation, equality, and non-discrimination.',
  },
  ushmmNurembergLaws: {
    institution: 'United States Holocaust Memorial Museum',
    sourceType: 'museum encyclopedia and primary-documentary collection',
    discipline: 'modern history and Holocaust studies',
    confidence: 'high',
    description: 'Historical documentation of racial citizenship, anti-Jewish legislation, and the legal transformation of German democracy into dictatorship.',
  },
  vdem: {
    institution: 'Varieties of Democracy Institute',
    sourceType: 'dataset codebook',
    discipline: 'comparative politics',
    confidence: 'high',
    description: 'Operational definitions for liberal democracy, civil liberties, rule of law, and executive constraints.',
  },
  wvs: {
    institution: 'World Values Survey Association',
    sourceType: 'survey documentation',
    discipline: 'political behaviour',
    confidence: 'high',
    description: 'Empirical documentation for traditional/secular-rational and survival/self-expression value dimensions.',
  },
  ches: {
    institution: 'Chapel Hill Expert Survey',
    sourceType: 'survey codebook',
    discipline: 'comparative politics',
    confidence: 'high',
    description: 'Expert-coded party-position scales covering economic, lifestyle, religion, immigration, multiculturalism, and decentralization issues.',
  },
  manifesto: {
    institution: 'Manifesto Project',
    sourceType: 'coding handbook',
    discipline: 'comparative politics',
    confidence: 'high',
    description: 'Methodology for comparing party manifestos across economic, social, political-system, and international positions.',
  },
  foreignPolicy: {
    creators: ['Oxford research authors'],
    sourceType: 'journal article',
    discipline: 'foreign policy',
    publisher: 'Oxford University Press',
    confidence: 'medium',
    description: 'Comparative research on party positions toward security, alliances, multilateralism, and intervention.',
  },
  openTextbook: {
    creators: ['Open textbook contributors'],
    institution: 'Open Textbook Library',
    sourceType: 'open textbook',
    discipline: 'political theory',
    confidence: 'medium',
    description: 'Comparative introduction to political ideologies and worldviews, including liberalism, conservatism, socialism, anarchism, nationalism, populism, fascism, Islamism, Confucianism, environmentalism, and feminism.',
  },
  sepAnarchism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of philosophical distinctions among anarchist arguments and traditions.',
  },
  sepFascism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Conceptual and historical analysis of fascist ideology and its variants.',
  },
  sepFeminism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Scholarly overview of feminist philosophical traditions and disagreements.',
  },
  sepPopulism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'political theory',
    confidence: 'high',
    description: 'Conceptual overview of debates about populism as ideology, discourse, and political style.',
  },
  sepConfucianism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'comparative political thought',
    confidence: 'high',
    description: 'Scholarly overview of Chinese political traditions, including Confucian accounts of order and governance.',
  },
  sepLegalism: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'comparative political thought',
    confidence: 'high',
    description: 'Historical scholarship on the fa tradition and classical Chinese statecraft.',
  },
  sepMedieval: {
    institution: 'Stanford Encyclopedia of Philosophy',
    sourceType: 'reference work',
    discipline: 'history of political thought',
    confidence: 'high',
    description: 'Historical overview of medieval concepts of kingship, republicanism, law, and authority.',
  },
  ushmmFascism: {
    institution: 'United States Holocaust Memorial Museum',
    sourceType: 'museum encyclopedia',
    discipline: 'modern history',
    confidence: 'high',
    description: 'Historical context for fascism and the Nazi regime, used critically for contextualization and warnings.',
  },
  panAfricanism: {
    creators: ['African Affairs authors'],
    sourceType: 'journal article',
    discipline: 'comparative political thought',
    publisher: 'Oxford University Press',
    confidence: 'medium',
    description: 'Scholarly treatment of Pan-African political thought and transnational solidarity.',
  },
};

export const BIBLIOGRAPHY_ACCESS_DATE = '2026-09-13';
