// Consultation boundaries are part of the published bibliography, not hidden notes.
const sources = [
  {
    id: 'sepFarabiAtlas',
    label: 'Thérèse-Anne Druart — al-Farabi (Stanford Encyclopedia of Philosophy)',
    url: 'https://plato.stanford.edu/entries/al-farabi/',
    note: 'Biographical introduction and section 7, Ethics and Politics, consulted. Life chronology is uncertain; no original Arabic manuscript or complete primary work was reviewed for these geographic cases.',
    creators: ['Thérèse-Anne Druart'], institution: 'Stanford Encyclopedia of Philosophy',
    publicationDate: '2024-05-14', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'scholarly reference entry / selected sections',
    description: 'Date records the substantive revision, not the first publication (15 July 2016). Biography supplies intellectual locations, not proof that a city implemented the philosophical ideal.',
  },
  {
    id: 'endelmanOttoman2018',
    label: 'Jonathan Endelman — In the Shadow of Empire: States in an Ottoman System',
    url: 'https://www.cambridge.org/core/journals/social-science-history/article/in-the-shadow-of-empire-states-in-an-ottoman-system/DDC77388ECBDE53F331CD398CC13C057',
    note: 'Selected HTML discussion of Young Ottoman circulation, Islamic constitutional reasoning and connections between Egypt and the imperial centre; not a full review of the article or its underlying archives. No claim is made about the publication city of any particular newspaper.',
    creators: ['Jonathan Endelman'], institution: 'Cambridge University Press / Social Science History',
    publicationDate: '2018-03-28', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'original historical-sociological research / selected passages',
    identifiers: { doi: '10.1017/ssh.2018.3' },
    description: 'A comparative account of states within the Ottoman system. The atlas uses a broad nineteenth-century research window, not an assertion that one movement existed throughout that entire century.',
  },
  {
    id: 'abouElFadlNasserism2016',
    label: 'Reem Abou El-Fadl — Nasserism (Oxford Handbook)',
    url: 'https://academic.oup.com/edited-volume/34445/chapter-abstract/292269514',
    note: 'Publisher abstract and metadata only, cross-checked with the SOAS repository abstract. Full chapter, archival evidence and policy outcomes were not reviewed. Contemporary language refers to the author’s 2016 assessment, not an updated 2026 survey.',
    creators: ['Reem Abou El-Fadl'], institution: 'Oxford University Press',
    publicationDate: '2016-05-02', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'scholarly history chapter / abstract only',
    identifiers: { doi: '10.1093/oxfordhb/9780199672530.013.18' },
    description: 'Chapter 12, pp. 225–247, in The Oxford Handbook of Contemporary Middle Eastern and North African History, edited by Amal Ghazal and Jens Hanssen. Publisher date retained; SOAS lists 1 May 2016.',
  },
  {
    id: 'raponeAflaq2023',
    label: 'Spenser R. Rapone — The Metaphysical Universe of Michel ʿAflaq and His Party',
    url: 'https://www.cambridge.org/core/journals/modern-intellectual-history/article/metaphysical-universe-of-michel-aflaq-and-his-party-a-reappraisal-of-the-bath/265B91D651F7AF2CAB6C513D57A66173',
    note: 'Abstract, introduction, concluding discussion and associated bibliographic notes consulted. Rapone’s reconstruction of Aflaq’s philosophy is attributed; Aflaq’s Arabic editions were not independently collated and this is not a study verifying regime outcomes.',
    creators: ['Spenser R. Rapone'], institution: 'Cambridge University Press / Modern Intellectual History',
    publicationDate: '2023-09-14', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'original intellectual-history research / selected passages',
    description: 'Subtitle: A Reappraisal of the Baʿth. The atlas distinguishes the founder’s philosophical project from later party-state practices; it does not merge Iraqi and Syrian histories.',
  },
  {
    id: 'chpPrinciples2025',
    label: 'CHP — Örgüt Temsilcileri Meclisi Sonuç Bildirisi (8 September 2025)',
    url: 'https://chp.org.tr/haberler/orgut-temsilcileri-meclisi-sonuc-bildirisi',
    note: 'Turkish statement, date and opening ideological/programme passages consulted on 16 September 2026. Original English paraphrase, not a quotation or certified translation. A party’s own statement documents self-description, not independent verification of conduct or its later platform.',
    creators: ['Cumhuriyet Halk Partisi'], institution: 'CHP',
    publicationDate: '2025-09-08', evidenceRole: 'primary', confidence: 'medium', languages: ['Turkish'],
    sourceType: 'political party statement / selected ideological passages',
    description: 'A dated contemporary advocacy snapshot. The page remains accessible at review, but accessibility alone does not establish the present implementation of its proposals or continuity of every policy.',
  },
  {
    id: 'suncaConfederalism2020',
    label: 'Yasin Sunca — The bifurcated trajectory of nation formation in Kurdistan',
    url: 'https://onlinelibrary.wiley.com/doi/10.1111/nana.12609',
    note: 'Introduction and selected democratic-confederalism and implementation-limit passages consulted. The 2020 account is a dated interpretive analysis, not field verification by this project or an account of territorial control in 2026. Publisher notes a funding-statement correction on 26 October 2020.',
    creators: ['Yasin Sunca'], institution: 'Wiley / Nations and Nationalism',
    publicationDate: '2020-03-10', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'original political research / selected passages',
    identifiers: { doi: '10.1111/nana.12609' },
    description: 'Subtitle: Democratic confederalism, nationalism, and the crisis of capitalist modernity. Distinguishes rival projects in Kurdish politics and acknowledges tensions between an emancipatory programme and the exercise of power.',
  },
  {
    id: 'gandhiHindSwarajAtlas',
    label: 'M. K. Gandhi — Hind Swaraj / Indian Home Rule',
    url: 'https://www.gandhiheritageportal.org/mahatma-gandhi-books/hind-swaraj-indian-opinion-hindi?source=atlas',
    note: 'Primary-text link used as an intellectual witness for swaraj and anti-imperial self-rule. This geographic case uses original synthesis and keeps the edition, translation, and implementation limits visible; no passage or translation is republished.',
  },
  {
    id: 'indiaConstitution1950Atlas',
    label: 'India Code — Constitution of India',
    url: 'https://legislative.gov.in/constitution-of-india/',
    note: 'Official Government of India primary-text link for the constitutional framework, rights, directive principles, institutions, and amendment procedure; no complete article-by-article collation is claimed in this pass.',
  },
  {
    id: 'klugConstitutingDemocracy2000',
    label: 'Heinz Klug — Constituting Democracy: Law, Globalism and South Africa’s Political Reconstruction',
    url: 'https://www.cambridge.org/core/books/constituting-democracy/E30A8E0CBB457AF6EBB0CB3F3884BCA7',
    note: 'Official Cambridge University Press book record and summary consulted for the transition from apartheid-era parliamentary sovereignty to constitutional supremacy, a Constitutional Court and democratic constitutionalism. The monograph’s full chapters and archival record were not independently collated; no book text is reproduced.',
    accessDate: '2026-09-19',
    creators: ['Heinz Klug'], institution: 'Cambridge University Press',
    publicationDate: '2000', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'book-length constitutional and political history',
    identifiers: { doi: '10.1017/CBO9780511560156', isbn: '9780521781138' },
    description: 'A book-length study of South Africa’s constitutional reconstruction. The atlas uses Cambridge’s bibliographic record and summary as a source lead and keeps full-text verification and implementation history open.',
  },
  {
    id: 'rouxPoliticsOfPrinciple2013',
    label: 'Theunis Roux — The Politics of Principle: The First South African Constitutional Court, 1995–2005',
    url: 'https://www.cambridge.org/core/books/politics-of-principle/C6625CF7F3EBE07DD6294A18E427429E',
    note: 'Official Cambridge University Press book record and summary consulted for the first Constitutional Court’s jurisprudential and institutional role in political context. The monograph’s full case studies and underlying records were not independently collated; no book text is reproduced.',
    accessDate: '2026-09-19',
    creators: ['Theunis Roux'], institution: 'Cambridge University Press',
    publicationDate: '2013', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'book-length constitutional-court history',
    identifiers: { doi: '10.1017/CBO9781139005081', isbn: '9781107013643' },
    description: 'A book-length history of the first South African Constitutional Court, used here to separate principled adjudication from institutional strategy and political context. Full-text and later-court verification remain research gaps.',
  },
  {
    id: 'southAfricaInterimConstitution1993',
    label: 'Parliament of South Africa — Constitution of the Republic of South Africa Act 200 of 1993',
    url: 'https://www.parliament.gov.za/storage/app/media/Acts/1993/Act_200_of_1993_Constitution_of_the_Republic_of_South_Africa_Act_Interim_Constitution.pdf',
    note: 'Official Parliament PDF link consulted as the primary interim constitutional text, including rights, institutions and the route toward a final Constitution. The PDF is linked rather than republished; a complete multilingual and archival collation was not undertaken.',
    accessDate: '2026-09-19',
    creators: ['Parliament of South Africa'], institution: 'Parliament of South Africa',
    publicationDate: '1993', evidenceRole: 'primary', confidence: 'high', languages: ['English'],
    sourceType: 'primary constitutional text / official PDF',
    description: 'The 1993 interim constitutional framework is primary evidence of transitional institutional design. It does not, by itself, establish implementation, public consent, or equal lived outcomes.',
  },
  {
    id: 'southAfricaConstitutionMakingMemo1996',
    label: 'South African Government — Constitution of the Republic of South Africa, 1996: Explanatory Memorandum',
    url: 'https://www.gov.za/documents/constitution-republic-south-africa-1996-explanatory-memorandum',
    note: 'Official explanatory memorandum consulted for the drafting, public-participation and adoption sequence of the 1996 Constitution. It is an institutional account rather than an independent measure of consent or implementation; no memorandum passage is reproduced.',
    accessDate: '2026-09-19',
    creators: ['South African Government'], institution: 'South African Government',
    publicationDate: '1996', evidenceRole: 'primary', confidence: 'medium', languages: ['English'],
    sourceType: 'official explanatory memorandum / constitutional history',
    description: 'An official account of the negotiated drafting and adoption sequence, including the interim constitutional framework and Constitutional Court review. Its institutional perspective and limits remain explicit.',
  },
  {
    id: 'antarcticTreaty1959',
    label: 'Antarctic Treaty Secretariat — The Antarctic Treaty',
    url: 'https://www.ats.aq/e/antarctictreaty.html?lang=en',
    note: 'Official Treaty Secretariat overview and searchable treaty text consulted for Articles I–IV, VII and IX. The treaty area is treated here as a governance context, not as a country or as evidence of a stateless or anarchist society.',
    creators: ['Antarctic Treaty Consultative Parties'], institution: 'Secretariat of the Antarctic Treaty',
    publicationDate: '1959-12-01', evidenceRole: 'primary', confidence: 'high', languages: ['English'],
    sourceType: 'international treaty / official institutional text',
    description: 'The Treaty reserves Antarctica for peaceful purposes, continues freedom of scientific investigation, preserves existing sovereignty positions and prevents new claims or enlargements while it is in force. It entered into force in 1961; the atlas records the foundational 1959 instrument rather than assigning sovereignty.',
  },
  {
    id: 'antarcticEnvironmentalProtocol1991',
    label: 'Antarctic Treaty Secretariat — Protocol on Environmental Protection',
    url: 'https://www.ats.aq/e/protocol.html',
    note: 'Official Treaty Secretariat overview consulted for Articles 2, 3 and 7, the protocol’s entry into force, and the 2048 review-conference clarification. The summary records the legal framework without reproducing treaty text.',
    creators: ['Antarctic Treaty Consultative Parties'], institution: 'Secretariat of the Antarctic Treaty',
    publicationDate: '1991-10-04', evidenceRole: 'primary', confidence: 'high', languages: ['English'],
    sourceType: 'international environmental protocol / official institutional text',
    description: 'The Protocol designates Antarctica a natural reserve devoted to peace and science and prohibits mineral-resource activities except scientific research. It does not expire in 2048; that date concerns a possible review-conference procedure.',
  },
];

export const GEOGRAPHY_RESEARCH_SOURCES = sources.map(({ id, label, url, note }) => ({ id, label, url, note }));
export const GEOGRAPHY_SOURCE_METADATA = Object.fromEntries(sources.map((source) => [source.id, {
  accessDate: source.accessDate ?? '2026-09-16', creators: source.creators, institution: source.institution,
  sourceType: source.sourceType, evidenceRole: source.evidenceRole,
  discipline: source.id.startsWith('antarctic') ? 'International law, environmental governance and political geography'
    : source.id.startsWith('southAfrica') || source.id.startsWith('klug') || source.id.startsWith('roux') ? 'South African constitutional law and political history'
      : 'Middle Eastern political history and geography',
  publicationDate: source.publicationDate, publisher: source.institution, confidence: source.confidence,
  languages: source.languages, description: source.description, identifiers: source.identifiers ?? {},
}]));
