// Consultation boundaries are part of the published bibliography, not hidden notes.
const sources = [
  {
    id: 'sepFarabiAtlas',
    label: 'Thérèse-Anne Druart — al-Farabi (Stanford Encyclopedia of Philosophy)',
    url: 'https://plato.stanford.edu/entries/al-farabi/',
    note: 'Biographical introduction and section 7, Ethics and Politics, consulted. Life chronology is uncertain; no original Arabic manuscript or complete primary work was reviewed for these geographic cases.',
    creators: ['Thérèse-Anne Druart'], institution: 'Stanford Encyclopedia of Philosophy',
    publicationDate: '2024-05-14', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'scholarly reference entry / selected sections',
    description: 'Date records the substantive revision, not the first publication (15 July 2016). Biography supplies intellectual locations, not proof that a city implemented the philosophical ideal.',
  },
  {
    id: 'endelmanOttoman2018',
    label: 'Jonathan Endelman — In the Shadow of Empire: States in an Ottoman System',
    url: 'https://www.cambridge.org/core/journals/social-science-history/article/in-the-shadow-of-empire-states-in-an-ottoman-system/DDC77388ECBDE53F331CD398CC13C057',
    note: 'Selected HTML discussion of Young Ottoman circulation, Islamic constitutional reasoning and connections between Egypt and the imperial centre; not a full review of the article or its underlying archives. No claim is made about the publication city of any particular newspaper.',
    creators: ['Jonathan Endelman'], institution: 'Cambridge University Press / Social Science History',
    publicationDate: '2018-03-28', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'original historical-sociological research / selected passages',
    identifiers: { doi: '10.1017/ssh.2018.3' },
    description: 'A comparative account of states within the Ottoman system. The atlas uses a broad nineteenth-century research window, not an assertion that one movement existed throughout that entire century.',
  },
  {
    id: 'abouElFadlNasserism2016',
    label: 'Reem Abou El-Fadl — Nasserism (Oxford Handbook)',
    url: 'https://academic.oup.com/edited-volume/34445/chapter-abstract/292269514',
    note: 'Publisher abstract and metadata only, cross-checked with the SOAS repository abstract. Full chapter, archival evidence and policy outcomes were not reviewed. Contemporary language refers to the author’s 2016 assessment, not an updated 2026 survey.',
    creators: ['Reem Abou El-Fadl'], institution: 'Oxford University Press',
    publicationDate: '2016-05-02', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'scholarly history chapter / abstract only',
    identifiers: { doi: '10.1093/oxfordhb/9780199672530.013.18' },
    description: 'Chapter 12, pp. 225–247, in The Oxford Handbook of Contemporary Middle Eastern and North African History, edited by Amal Ghazal and Jens Hanssen. Publisher date retained; SOAS lists 1 May 2016.',
  },
  {
    id: 'raponeAflaq2023',
    label: 'Spenser R. Rapone — The Metaphysical Universe of Michel ʿAflaq and His Party',
    url: 'https://www.cambridge.org/core/journals/modern-intellectual-history/article/metaphysical-universe-of-michel-aflaq-and-his-party-a-reappraisal-of-the-bath/265B91D651F7AF2CAB6C513D57A66173',
    note: 'Abstract, introduction, concluding discussion and associated bibliographic notes consulted. Rapone’s reconstruction of Aflaq’s philosophy is attributed; Aflaq’s Arabic editions were not independently collated and this is not a study verifying regime outcomes.',
    creators: ['Spenser R. Rapone'], institution: 'Cambridge University Press / Modern Intellectual History',
    publicationDate: '2023-09-14', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'original intellectual-history research / selected passages',
    description: 'Subtitle: A Reappraisal of the Baʿth. The atlas distinguishes the founder’s philosophical project from later party-state practices; it does not merge Iraqi and Syrian histories.',
  },
  {
    id: 'chpPrinciples2025',
    label: 'CHP — Örgüt Temsilcileri Meclisi Sonuç Bildirisi (8 September 2025)',
    url: 'https://chp.org.tr/haberler/orgut-temsilcileri-meclisi-sonuc-bildirisi',
    note: 'Turkish statement, date and opening ideological/programme passages consulted on 16 September 2026. Original English paraphrase, not a quotation or certified translation. A party’s own statement documents self-description, not independent verification of conduct or its later platform.',
    creators: ['Cumhuriyet Halk Partisi'], institution: 'CHP',
    publicationDate: '2025-09-08', evidenceRole: 'primary', confidence: 'medium', languages: ['Turkish'],
    sourceType: 'political party statement / selected ideological passages',
    description: 'A dated contemporary advocacy snapshot. The page remains accessible at review, but accessibility alone does not establish the present implementation of its proposals or continuity of every policy.',
  },
  {
    id: 'suncaConfederalism2020',
    label: 'Yasin Sunca — The bifurcated trajectory of nation formation in Kurdistan',
    url: 'https://onlinelibrary.wiley.com/doi/10.1111/nana.12609',
    note: 'Introduction and selected democratic-confederalism and implementation-limit passages consulted. The 2020 account is a dated interpretive analysis, not field verification by this project or an account of territorial control in 2026. Publisher notes a funding-statement correction on 26 October 2020.',
    creators: ['Yasin Sunca'], institution: 'Wiley / Nations and Nationalism',
    publicationDate: '2020-03-10', evidenceRole: 'secondary', confidence: 'medium', languages: ['English'],
    sourceType: 'original political research / selected passages',
    identifiers: { doi: '10.1111/nana.12609' },
    description: 'Subtitle: Democratic confederalism, nationalism, and the crisis of capitalist modernity. Distinguishes rival projects in Kurdish politics and acknowledges tensions between an emancipatory programme and the exercise of power.',
  },
];

export const GEOGRAPHY_RESEARCH_SOURCES = sources.map(({ id, label, url, note }) => ({ id, label, url, note }));
export const GEOGRAPHY_SOURCE_METADATA = Object.fromEntries(sources.map((source) => [source.id, {
  accessDate: '2026-09-16', creators: source.creators, institution: source.institution,
  sourceType: source.sourceType, evidenceRole: source.evidenceRole, discipline: 'Middle Eastern political history and geography',
  publicationDate: source.publicationDate, publisher: source.institution, confidence: source.confidence,
  languages: source.languages, description: source.description, identifiers: source.identifiers ?? {},
}]));
