// These references are evidence anchors for the taxonomy language. A band is
// an interpretive synthesis unless a citation includes a short, verified
// primary-text quotation.
export const AUTHOR_REFERENCES = {
  marxEngelsManifesto: {
    author: 'Karl Marx & Friedrich Engels',
    work: 'Manifesto of the Communist Party',
    year: '1848',
    kind: 'direct',
    locator: 'Chapter I',
    quote: 'The history of all hitherto existing society is the history of class struggles.',
    url: 'https://www.marxists.org/archive/marx/works/1848/communist-manifesto/ch01.htm',
  },
  leninStateRevolution: {
    author: 'Vladimir Lenin',
    work: 'The State and Revolution',
    year: '1917',
    kind: 'primary',
    url: 'https://www.marxists.org/archive/lenin/works/1917/staterev/',
  },
  bernsteinEvolutionarySocialism: {
    author: 'Eduard Bernstein',
    work: 'Evolutionary Socialism',
    year: '1899',
    kind: 'primary',
    url: 'https://www.marxists.org/reference/archive/bernstein/works/1899/evsoc/',
  },
  adamSmithWealth: {
    author: 'Adam Smith',
    work: 'The Wealth of Nations',
    year: '1776',
    kind: 'primary',
    url: 'https://www.econlib.org/library/Smith/smWN.html',
  },
  hayekKnowledge: {
    author: 'Friedrich A. Hayek',
    work: 'The Use of Knowledge in Society',
    year: '1945',
    kind: 'direct',
    locator: 'American Economic Review, XXXV(4)',
    quote: 'The knowledge of the circumstances of which we must make use never exists in concentrated or integrated form.',
    url: 'https://www.econlib.org/library/Essays/hykKnw.html',
  },
  keynesGeneralTheory: {
    author: 'John Maynard Keynes',
    work: 'The General Theory of Employment, Interest and Money',
    year: '1936',
    kind: 'scholarly',
    url: 'https://www.econlib.org/library/Enc/bios/Keynes.html',
  },
  nozickASU: {
    author: 'Robert Nozick',
    work: 'Anarchy, State, and Utopia',
    year: '1974',
    kind: 'primary',
    url: 'https://www.hachettebookgroup.com/titles/robert-nozick/anarchy-state-and-utopia/9780465051007/',
  },
  millOnLiberty: {
    author: 'John Stuart Mill',
    work: 'On Liberty',
    year: '1859',
    kind: 'direct',
    locator: 'Chapter I',
    quote: 'The sole end for which mankind are warranted, individually or collectively, in interfering with the liberty of action of any of their number, is self-protection.',
    url: 'https://www.gutenberg.org/files/34901/34901-h/34901-h.htm',
  },
  wollstonecraftRights: {
    author: 'Mary Wollstonecraft',
    work: 'A Vindication of the Rights of Woman',
    year: '1792',
    kind: 'primary',
    url: 'https://www.gutenberg.org/cache/epub/3420/pg3420.html',
  },
  burkeReflections: {
    author: 'Edmund Burke',
    work: 'Reflections on the Revolution in France',
    year: '1790',
    kind: 'primary',
    url: 'https://www.gutenberg.org/cache/epub/15679/pg15679-images.html',
  },
  tocquevilleDemocracy: {
    author: 'Alexis de Tocqueville',
    work: 'Democracy in America',
    year: '1835–1840',
    kind: 'primary',
    url: 'https://www.gutenberg.org/ebooks/815',
  },
  hobbesLeviathan: {
    author: 'Thomas Hobbes',
    work: 'Leviathan',
    year: '1651',
    kind: 'primary',
    url: 'https://www.gutenberg.org/ebooks/3207',
  },
  lockeSecondTreatise: {
    author: 'John Locke',
    work: 'Second Treatise of Government',
    year: '1689',
    kind: 'direct',
    locator: 'Chapter VIII',
    quote: 'Men being, as has been said, by nature, all free, equal, and independent.',
    url: 'https://www.gutenberg.org/files/7370/7370-h/7370-h.htm',
  },
  bakuninStatism: {
    author: 'Mikhail Bakunin',
    work: 'Statism and Anarchy',
    year: '1873',
    kind: 'primary',
    url: 'https://www.marxists.org/reference/archive/bakunin/works/1873/statism-anarchy.htm',
  },
  arendtTotalitarianism: {
    author: 'Hannah Arendt',
    work: 'The Origins of Totalitarianism',
    year: '1951',
    kind: 'scholarly',
    url: 'https://www.penguinrandomhouse.com/books/53885/the-origins-of-totalitarianism-by-hannah-arendt/',
  },
  hitlerMeinKampf: {
    author: 'Adolf Hitler',
    work: 'Mein Kampf',
    year: '1925–1926',
    kind: 'primary',
    context: 'Historical primary source; cited for analysis of Nazi ideology, not endorsement.',
    url: 'https://germanhistorydocs.org/en/nazi-germany-1933-1945/adolf-hitler-mein-kampf-volume-1-1925',
  },
  mussoliniDoctrine: {
    author: 'Benito Mussolini (with Giovanni Gentile)',
    work: 'The Doctrine of Fascism',
    year: '1932',
    kind: 'direct',
    locator: 'Political and Social Doctrine of Fascism',
    quote: 'Fascism conceives of the State as an absolute, in comparison with which all individuals or groups are relative.',
    context: 'Historical primary source; cited critically as an authoritarian ideology text.',
    url: 'https://sourcebooks.web.fordham.edu/mod/mussolini-fascism.asp',
  },
  renanNation: {
    author: 'Ernest Renan',
    work: 'What Is a Nation?',
    year: '1882',
    kind: 'direct',
    locator: 'Sorbonne lecture',
    quote: 'A nation is a soul, a spiritual principle.',
    url: 'https://sourcebooks.web.fordham.edu/mod/1882Renan-nation-eng.asp',
  },
  andersonImaginedCommunities: {
    author: 'Benedict Anderson',
    work: 'Imagined Communities',
    year: '1983',
    kind: 'scholarly',
    url: 'https://cup.columbia.edu/book/imagined-communities/9781784786755',
  },
  kantPerpetualPeace: {
    author: 'Immanuel Kant',
    work: 'Toward Perpetual Peace',
    year: '1795',
    kind: 'primary',
    url: 'https://plato.stanford.edu/entries/kant-social-political/',
  },
  morgenthauRealism: {
    author: 'Hans J. Morgenthau',
    work: 'Politics Among Nations',
    year: '1948',
    kind: 'scholarly',
    url: 'https://plato.stanford.edu/entries/realism-intl-relations/',
  },
  mearsheimerTragedy: {
    author: 'John J. Mearsheimer',
    work: 'The Tragedy of Great Power Politics',
    year: '2001',
    kind: 'scholarly',
    url: 'https://political-science.uchicago.edu/directory/john-mearsheimer',
  },
  walzerJustWars: {
    author: 'Michael Walzer',
    work: 'Just and Unjust Wars',
    year: '1977',
    kind: 'scholarly',
    url: 'https://www.basicbooks.com/titles/michael-walzer/just-and-unjust-wars/9780465037070/',
  },
  clausewitzOnWar: {
    author: 'Carl von Clausewitz',
    work: 'On War',
    year: '1832',
    kind: 'primary',
    url: 'https://www.gutenberg.org/ebooks/1946',
  },
  gandhiHindSwaraj: {
    author: 'M. K. Gandhi',
    work: 'Hind Swaraj / Indian Home Rule',
    year: '1909',
    kind: 'primary',
    context: 'A primary anti-colonial text used to interpret ethical self-rule, nonviolence, and decentralized political economy.',
    url: 'https://www.gandhiheritageportal.org/mahatma-gandhi-books/hind-swaraj-indian-opinion-hindi',
  },
  duboisBlackReconstruction: {
    author: 'W. E. B. Du Bois',
    work: 'Black Reconstruction in America, 1860–1880',
    year: '1935',
    kind: 'primary',
    context: 'A historical analysis used to interpret emancipation, labor power, equal citizenship, and Black democratic agency.',
    url: 'https://www.loa.org/books/698-black-reconstruction/',
  },
  fanonWretchedEarth: {
    author: 'Frantz Fanon',
    work: 'The Wretched of the Earth',
    year: '1961',
    kind: 'primary',
    context: 'A historically situated anti-colonial text; it is cited critically and does not constitute a universal endorsement of revolutionary violence.',
    url: 'https://archive.org/details/wretchedofearth00fano',
  },
  ostromGoverningCommons: {
    author: 'Elinor Ostrom',
    work: 'Beyond Markets and States: Polycentric Governance of Complex Economic Systems',
    year: '2009',
    kind: 'primary',
    context: 'A Nobel Prize lecture used to interpret commons governance, polycentric institutions, and alternatives to a state-versus-market binary.',
    url: 'https://www.nobelprize.org/prizes/economic-sciences/2009/ostrom/lecture/',
  },
};

// Every band receives an explicit list. These are references for the
// conceptual position, not claims that an author used our exact label.
export const BAND_CITATIONS = {
  economic: [
    ['marxEngelsManifesto', 'leninStateRevolution'],
    ['marxEngelsManifesto', 'leninStateRevolution'],
    ['marxEngelsManifesto', 'bernsteinEvolutionarySocialism'],
    ['bernsteinEvolutionarySocialism', 'keynesGeneralTheory'],
    ['keynesGeneralTheory', 'millOnLiberty'],
    ['keynesGeneralTheory', 'hayekKnowledge'],
    ['adamSmithWealth', 'hayekKnowledge'],
    ['adamSmithWealth', 'millOnLiberty'],
    ['adamSmithWealth', 'hayekKnowledge'],
    ['hayekKnowledge', 'nozickASU'],
  ],
  social: [
    ['wollstonecraftRights', 'millOnLiberty'],
    ['wollstonecraftRights', 'millOnLiberty'],
    ['wollstonecraftRights', 'millOnLiberty'],
    ['millOnLiberty', 'lockeSecondTreatise'],
    ['millOnLiberty', 'lockeSecondTreatise'],
    ['millOnLiberty', 'burkeReflections'],
    ['burkeReflections', 'tocquevilleDemocracy'],
    ['burkeReflections', 'tocquevilleDemocracy'],
    ['burkeReflections', 'renanNation'],
    ['burkeReflections', 'hobbesLeviathan'],
  ],
  authority: [
    ['bakuninStatism', 'millOnLiberty'],
    ['nozickASU', 'lockeSecondTreatise'],
    ['millOnLiberty', 'lockeSecondTreatise'],
    ['lockeSecondTreatise', 'millOnLiberty'],
    ['lockeSecondTreatise', 'millOnLiberty'],
    ['lockeSecondTreatise', 'tocquevilleDemocracy'],
    ['hobbesLeviathan', 'tocquevilleDemocracy'],
    ['hobbesLeviathan', 'burkeReflections'],
    ['arendtTotalitarianism', 'hobbesLeviathan'],
    ['arendtTotalitarianism', 'mussoliniDoctrine'],
  ],
  identity: [
    ['renanNation', 'andersonImaginedCommunities'],
    ['kantPerpetualPeace', 'renanNation'],
    ['kantPerpetualPeace', 'andersonImaginedCommunities'],
    ['renanNation', 'andersonImaginedCommunities'],
    ['renanNation', 'andersonImaginedCommunities'],
    ['renanNation', 'andersonImaginedCommunities'],
    ['renanNation', 'burkeReflections'],
    ['renanNation', 'burkeReflections'],
    ['renanNation', 'andersonImaginedCommunities'],
    ['hitlerMeinKampf', 'renanNation'],
  ],
  foreign: [
    ['kantPerpetualPeace', 'walzerJustWars'],
    ['kantPerpetualPeace', 'morgenthauRealism'],
    ['morgenthauRealism', 'mearsheimerTragedy'],
    ['kantPerpetualPeace', 'morgenthauRealism'],
    ['kantPerpetualPeace', 'morgenthauRealism'],
    ['morgenthauRealism', 'kantPerpetualPeace'],
    ['morgenthauRealism', 'mearsheimerTragedy'],
    ['mearsheimerTragedy', 'morgenthauRealism'],
    ['mearsheimerTragedy', 'clausewitzOnWar'],
    ['clausewitzOnWar', 'hitlerMeinKampf', 'mussoliniDoctrine'],
  ],
};

export const ARCHETYPE_CITATIONS = {
  'authoritarian-collectivist': {
    summary: ['marxEngelsManifesto', 'leninStateRevolution', 'arendtTotalitarianism'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'leninStateRevolution'],
      social: ['marxEngelsManifesto', 'arendtTotalitarianism'],
      authority: ['leninStateRevolution', 'arendtTotalitarianism'],
      identity: ['marxEngelsManifesto', 'leninStateRevolution'],
      foreign: ['leninStateRevolution', 'morgenthauRealism'],
    },
  },
  'historical-fascist': {
    summary: ['hitlerMeinKampf', 'mussoliniDoctrine', 'arendtTotalitarianism'],
    dimensions: {
      economic: ['mussoliniDoctrine', 'hitlerMeinKampf'],
      social: ['hitlerMeinKampf', 'mussoliniDoctrine'],
      authority: ['mussoliniDoctrine', 'arendtTotalitarianism'],
      identity: ['hitlerMeinKampf', 'mussoliniDoctrine'],
      foreign: ['hitlerMeinKampf', 'mussoliniDoctrine'],
    },
  },
  'libertarian-market': {
    summary: ['hayekKnowledge', 'millOnLiberty', 'nozickASU'],
    dimensions: {
      economic: ['adamSmithWealth', 'hayekKnowledge', 'nozickASU'],
      social: ['millOnLiberty', 'lockeSecondTreatise'],
      authority: ['millOnLiberty', 'nozickASU'],
      identity: ['lockeSecondTreatise', 'millOnLiberty'],
      foreign: ['morgenthauRealism', 'millOnLiberty'],
    },
  },
  'progressive-liberal': {
    summary: ['millOnLiberty', 'wollstonecraftRights', 'kantPerpetualPeace'],
    dimensions: {
      economic: ['keynesGeneralTheory', 'millOnLiberty'],
      social: ['wollstonecraftRights', 'millOnLiberty'],
      authority: ['millOnLiberty', 'lockeSecondTreatise'],
      identity: ['kantPerpetualPeace', 'andersonImaginedCommunities'],
      foreign: ['kantPerpetualPeace', 'morgenthauRealism'],
    },
  },
  'national-conservative': {
    summary: ['burkeReflections', 'renanNation', 'andersonImaginedCommunities'],
    dimensions: {
      economic: ['adamSmithWealth', 'burkeReflections'],
      social: ['burkeReflections', 'tocquevilleDemocracy'],
      authority: ['burkeReflections', 'hobbesLeviathan'],
      identity: ['renanNation', 'andersonImaginedCommunities'],
      foreign: ['morgenthauRealism', 'mearsheimerTragedy'],
    },
  },
  'social-democratic': {
    summary: ['bernsteinEvolutionarySocialism', 'keynesGeneralTheory', 'millOnLiberty'],
    dimensions: {
      economic: ['bernsteinEvolutionarySocialism', 'keynesGeneralTheory'],
      social: ['millOnLiberty', 'wollstonecraftRights'],
      authority: ['lockeSecondTreatise', 'millOnLiberty'],
      identity: ['renanNation', 'andersonImaginedCommunities'],
      foreign: ['kantPerpetualPeace', 'morgenthauRealism'],
    },
  },
  'classical-liberal': {
    summary: ['adamSmithWealth', 'lockeSecondTreatise', 'millOnLiberty'],
    dimensions: {
      economic: ['adamSmithWealth', 'hayekKnowledge'],
      social: ['millOnLiberty', 'lockeSecondTreatise'],
      authority: ['lockeSecondTreatise', 'millOnLiberty'],
      identity: ['lockeSecondTreatise', 'kantPerpetualPeace'],
      foreign: ['kantPerpetualPeace', 'millOnLiberty'],
    },
  },
  'democratic-socialist': {
    summary: ['marxEngelsManifesto', 'bernsteinEvolutionarySocialism', 'keynesGeneralTheory'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'bernsteinEvolutionarySocialism', 'keynesGeneralTheory'],
      social: ['wollstonecraftRights', 'millOnLiberty'],
      authority: ['millOnLiberty', 'lockeSecondTreatise'],
      identity: ['andersonImaginedCommunities', 'renanNation'],
      foreign: ['kantPerpetualPeace', 'walzerJustWars'],
    },
  },
  'anarchist-communalist': {
    summary: ['bakuninStatism', 'marxEngelsManifesto', 'millOnLiberty'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'bakuninStatism'],
      social: ['bakuninStatism', 'millOnLiberty'],
      authority: ['bakuninStatism', 'millOnLiberty'],
      identity: ['bakuninStatism', 'andersonImaginedCommunities'],
      foreign: ['bakuninStatism', 'kantPerpetualPeace'],
    },
  },
  'green-commons': {
    summary: ['ostromGoverningCommons', 'millOnLiberty', 'kantPerpetualPeace'],
    dimensions: {
      economic: ['ostromGoverningCommons', 'adamSmithWealth'],
      social: ['ostromGoverningCommons', 'millOnLiberty'],
      authority: ['ostromGoverningCommons', 'lockeSecondTreatise'],
      identity: ['ostromGoverningCommons', 'kantPerpetualPeace'],
      foreign: ['ostromGoverningCommons', 'kantPerpetualPeace'],
    },
  },
  'religious-traditionalist': {
    summary: ['burkeReflections', 'hobbesLeviathan', 'renanNation'],
    dimensions: {
      economic: ['burkeReflections', 'adamSmithWealth'],
      social: ['burkeReflections', 'hobbesLeviathan'],
      authority: ['hobbesLeviathan', 'burkeReflections'],
      identity: ['burkeReflections', 'renanNation'],
      foreign: ['morgenthauRealism', 'burkeReflections'],
    },
  },
  'anti-colonial-liberation': {
    summary: ['gandhiHindSwaraj', 'fanonWretchedEarth', 'duboisBlackReconstruction'],
    dimensions: {
      economic: ['gandhiHindSwaraj', 'fanonWretchedEarth', 'duboisBlackReconstruction'],
      social: ['duboisBlackReconstruction', 'fanonWretchedEarth', 'gandhiHindSwaraj'],
      authority: ['gandhiHindSwaraj', 'fanonWretchedEarth', 'lockeSecondTreatise'],
      identity: ['fanonWretchedEarth', 'gandhiHindSwaraj', 'duboisBlackReconstruction'],
      foreign: ['gandhiHindSwaraj', 'fanonWretchedEarth', 'kantPerpetualPeace'],
    },
  },
};
