// These references are evidence anchors for the taxonomy language. A band is
// an interpretive synthesis unless a citation includes a short, verified
// primary-text quotation.
export const AUTHOR_REFERENCES = {
  marxEngelsManifesto: {
    author: 'Karl Marx & Friedrich Engels',
    work: 'Manifesto of the Communist Party',
    year: '1848',
    kind: 'direct',
    locator: 'Chapter I',
    quote: 'The history of all hitherto existing society is the history of class struggles.',
    url: 'https://www.marxists.org/archive/marx/works/1848/communist-manifesto/ch01.htm',
  },
  leninStateRevolution: {
    author: 'Vladimir Lenin',
    work: 'The State and Revolution',
    year: '1917',
    kind: 'primary',
    url: 'https://www.marxists.org/archive/lenin/works/1917/staterev/',
  },
  bernsteinEvolutionarySocialism: {
    author: 'Eduard Bernstein',
    work: 'Evolutionary Socialism',
    year: '1899',
    kind: 'primary',
    url: 'https://www.marxists.org/reference/archive/bernstein/works/1899/evsoc/',
  },
  luxemburgReformRevolution: {
    author: 'Rosa Luxemburg',
    work: 'Reform or Revolution',
    year: '1900',
    kind: 'primary',
    context: 'A German-Polish Marxist critique of reducing socialism to incremental reform; cited to represent an internal democratic-socialist and revolutionary debate, not as a universal programme.',
    url: 'https://www.marxists.org/archive/luxemburg/1900/reform-revolution/index.htm',
  },
  jauresSocialistHistory: {
    author: 'Jean Jaurès',
    work: 'Socialist History of the French Revolution',
    year: '1901',
    kind: 'primary',
    context: 'A French socialist account linking democracy, republican citizenship, and social transformation; the online English text is a translation and is cited through a link rather than reproduced.',
    url: 'https://www.marxists.org/archive/jaures/1901/history/judge-revolutionaries.htm',
  },
  kropotkinMutualAid: {
    author: 'Peter Kropotkin',
    work: 'Mutual Aid: A Factor of Evolution',
    year: '1902',
    kind: 'primary',
    context: 'An anarchist account of cooperation and mutual aid used to explain the positive institutional side of anti-authoritarian politics; it is not treated as a complete empirical theory of all human conduct.',
    url: 'https://www.marxists.org/reference/archive/kropotkin-peter/1902/mutual-aid/index.htm',
  },
  bookchinLibertarianMunicipalism: {
    author: 'Murray Bookchin',
    work: 'The Politics of Social Ecology: Libertarian Municipalism',
    year: '1999',
    kind: 'primary',
    context: 'A contemporary communalist proposal for directly democratic municipalities and confederations; it is distinguished from nineteenth-century anarcho-communism rather than treated as identical to it.',
    url: 'https://social-ecology.org/wp/1999/01/the-politics-of-social-ecology-libertarian-municipalism/',
  },
  adamSmithWealth: {
    author: 'Adam Smith',
    work: 'The Wealth of Nations',
    year: '1776',
    kind: 'primary',
    url: 'https://www.econlib.org/library/Smith/smWN.html',
  },
  constantLibertyModerns: {
    author: 'Benjamin Constant',
    work: 'The Liberty of Ancients Compared with that of Moderns',
    year: '1819',
    kind: 'primary',
    context: 'A French liberal primary text used to distinguish modern individual and civil liberty from direct political participation in the ancient model; it is not treated as a complete economic programme.',
    url: 'https://oll.libertyfund.org/titles/constant-the-liberty-of-ancients-compared-with-that-of-moderns-1819?html=true',
  },
  hayekKnowledge: {
    author: 'Friedrich A. Hayek',
    work: 'The Use of Knowledge in Society',
    year: '1945',
    kind: 'direct',
    locator: 'American Economic Review, XXXV(4)',
    quote: 'The knowledge of the circumstances of which we must make use never exists in concentrated or integrated form.',
    url: 'https://www.econlib.org/library/Essays/hykKnw.html',
  },
  keynesGeneralTheory: {
    author: 'John Maynard Keynes',
    work: 'The General Theory of Employment, Interest and Money',
    year: '1936',
    kind: 'scholarly',
    url: 'https://www.econlib.org/library/Enc/bios/Keynes.html',
  },
  nozickASU: {
    author: 'Robert Nozick',
    work: 'Anarchy, State, and Utopia',
    year: '1974',
    kind: 'primary',
    url: 'https://www.hachettebookgroup.com/titles/robert-nozick/anarchy-state-and-utopia/9780465051007/',
  },
  rothbardForNewLiberty: {
    author: 'Murray N. Rothbard',
    work: 'For a New Liberty: The Libertarian Manifesto',
    year: '1973',
    kind: 'primary',
    context: 'A canonical anarcho-capitalist presentation of self-ownership, private property, voluntary exchange, and the rejection of the state; cited as a primary position, not as proof that the proposed institutions work in practice.',
    url: 'https://openlibrary.org/books/OL5304654M/For_a_new_liberty',
  },
  millOnLiberty: {
    author: 'John Stuart Mill',
    work: 'On Liberty',
    year: '1859',
    kind: 'direct',
    locator: 'Chapter I',
    quote: 'The sole end for which mankind are warranted, individually or collectively, in interfering with the liberty of action of any of their number, is self-protection.',
    url: 'https://www.gutenberg.org/files/34901/34901-h/34901-h.htm',
  },
  wollstonecraftRights: {
    author: 'Mary Wollstonecraft',
    work: 'A Vindication of the Rights of Woman',
    year: '1792',
    kind: 'primary',
    url: 'https://www.gutenberg.org/cache/epub/3420/pg3420.html',
  },
  burkeReflections: {
    author: 'Edmund Burke',
    work: 'Reflections on the Revolution in France',
    year: '1790',
    kind: 'primary',
    url: 'https://www.gutenberg.org/cache/epub/15679/pg15679-images.html',
  },
  tocquevilleDemocracy: {
    author: 'Alexis de Tocqueville',
    work: 'Democracy in America',
    year: '1835–1840',
    kind: 'primary',
    url: 'https://www.gutenberg.org/ebooks/815',
  },
  hobbesLeviathan: {
    author: 'Thomas Hobbes',
    work: 'Leviathan',
    year: '1651',
    kind: 'primary',
    url: 'https://www.gutenberg.org/ebooks/3207',
  },
  lockeSecondTreatise: {
    author: 'John Locke',
    work: 'Second Treatise of Government',
    year: '1689',
    kind: 'direct',
    locator: 'Chapter VIII',
    quote: 'Men being, as has been said, by nature, all free, equal, and independent.',
    url: 'https://www.gutenberg.org/files/7370/7370-h/7370-h.htm',
  },
  bakuninStatism: {
    author: 'Mikhail Bakunin',
    work: 'Statism and Anarchy',
    year: '1873',
    kind: 'primary',
    url: 'https://www.marxists.org/reference/archive/bakunin/works/1873/statism-anarchy.htm',
  },
  arendtTotalitarianism: {
    author: 'Hannah Arendt',
    work: 'The Origins of Totalitarianism',
    year: '1951',
    kind: 'scholarly',
    url: 'https://www.penguinrandomhouse.com/books/53885/the-origins-of-totalitarianism-by-hannah-arendt/',
  },
  griffinNatureFascism: {
    author: 'Roger Griffin',
    work: 'The Nature of Fascism',
    year: '1991',
    kind: 'scholarly',
    context: 'Comparative scholarship used for the contested generic concept of fascism and its recurring theme of national rebirth; it is not treated as the only valid definition.',
    url: 'https://academic.oup.com/book/47490?searchresult=1',
  },
  hitlerMeinKampf: {
    author: 'Adolf Hitler',
    work: 'Mein Kampf',
    year: '1925–1926',
    kind: 'primary',
    context: 'Historical primary source; cited for analysis of Nazi ideology, not endorsement.',
    url: 'https://germanhistorydocs.org/en/nazi-germany-1933-1945/adolf-hitler-mein-kampf-volume-1-1925',
  },
  mussoliniDoctrine: {
    author: 'Benito Mussolini (with Giovanni Gentile)',
    work: 'The Doctrine of Fascism',
    year: '1932',
    kind: 'direct',
    locator: 'Political and Social Doctrine of Fascism',
    quote: 'Fascism conceives of the State as an absolute, in comparison with which all individuals or groups are relative.',
    context: 'Historical primary source; cited critically as an authoritarian ideology text.',
    url: 'https://sourcebooks.web.fordham.edu/mod/mussolini-fascism.asp',
  },
  renanNation: {
    author: 'Ernest Renan',
    work: 'What Is a Nation?',
    year: '1882',
    kind: 'direct',
    locator: 'Sorbonne lecture',
    quote: 'A nation is a soul, a spiritual principle.',
    url: 'https://sourcebooks.web.fordham.edu/mod/1882Renan-nation-eng.asp',
  },
  andersonImaginedCommunities: {
    author: 'Benedict Anderson',
    work: 'Imagined Communities',
    year: '1983',
    kind: 'scholarly',
    url: 'https://cup.columbia.edu/book/imagined-communities/9781784786755',
  },
  kantPerpetualPeace: {
    author: 'Immanuel Kant',
    work: 'Toward Perpetual Peace',
    year: '1795',
    kind: 'primary',
    url: 'https://plato.stanford.edu/entries/kant-social-political/',
  },
  morgenthauRealism: {
    author: 'Hans J. Morgenthau',
    work: 'Politics Among Nations',
    year: '1948',
    kind: 'scholarly',
    url: 'https://plato.stanford.edu/entries/realism-intl-relations/',
  },
  mearsheimerTragedy: {
    author: 'John J. Mearsheimer',
    work: 'The Tragedy of Great Power Politics',
    year: '2001',
    kind: 'scholarly',
    url: 'https://political-science.uchicago.edu/directory/john-mearsheimer',
  },
  walzerJustWars: {
    author: 'Michael Walzer',
    work: 'Just and Unjust Wars',
    year: '1977',
    kind: 'scholarly',
    url: 'https://www.basicbooks.com/titles/michael-walzer/just-and-unjust-wars/9780465037070/',
  },
  clausewitzOnWar: {
    author: 'Carl von Clausewitz',
    work: 'On War',
    year: '1832',
    kind: 'primary',
    url: 'https://www.gutenberg.org/ebooks/1946',
  },
  gandhiHindSwaraj: {
    author: 'M. K. Gandhi',
    work: 'Hind Swaraj / Indian Home Rule',
    year: '1909',
    kind: 'primary',
    context: 'A primary anti-colonial text used to interpret ethical self-rule, nonviolence, and decentralized political economy.',
    url: 'https://www.gandhiheritageportal.org/mahatma-gandhi-books/hind-swaraj-indian-opinion-hindi',
  },
  duboisBlackReconstruction: {
    author: 'W. E. B. Du Bois',
    work: 'Black Reconstruction in America, 1860–1880',
    year: '1935',
    kind: 'primary',
    context: 'A historical analysis used to interpret emancipation, labor power, equal citizenship, and Black democratic agency.',
    url: 'https://www.loa.org/books/698-black-reconstruction/',
  },
  fanonWretchedEarth: {
    author: 'Frantz Fanon',
    work: 'The Wretched of the Earth',
    year: '1961',
    kind: 'primary',
    context: 'A historically situated anti-colonial text; it is cited critically and does not constitute a universal endorsement of revolutionary violence.',
    url: 'https://archive.org/details/wretchedofearth00fano',
  },
  cesaireDiscourseColonialism: {
    author: 'Aimé Césaire',
    work: 'Discourse on Colonialism',
    year: '1950',
    kind: 'primary',
    context: 'A French-language anti-colonial critique of racial hierarchy, imperial domination, and the material and cultural violence of colonialism; cited critically and paraphrased independently.',
    url: 'https://catalogue.bnf.fr/ark:/12148/cb39259691z',
  },
  nabucoAbolitionism: {
    author: 'Joaquim Nabuco',
    work: 'O Abolicionismo',
    year: '1883',
    kind: 'primary',
    context: 'A Portuguese-language Brazilian abolitionist work used to connect slavery, law, citizenship, national development, and constitutional reform; it is not treated as a complete theory of twentieth-century decolonization.',
    url: 'https://bd.camara.leg.br/bd/items/06a7a704-9df6-4523-a7d3-e1803bded996/full',
  },
  ostromGoverningCommons: {
    author: 'Elinor Ostrom',
    work: 'Beyond Markets and States: Polycentric Governance of Complex Economic Systems',
    year: '2009',
    kind: 'primary',
    context: 'A Nobel Prize lecture used to interpret commons governance, polycentric institutions, and alternatives to a state-versus-market binary.',
    url: 'https://www.nobelprize.org/prizes/economic-sciences/2009/ostrom/lecture/',
  },
  senDevelopmentFreedom: {
    author: 'Amartya Sen',
    work: 'Development as Freedom',
    year: '1999',
    kind: 'primary',
    context: 'A capability-based account used to connect substantive freedom, public reasoning, health, education, and environmental justice; it is not treated as a complete green ideology.',
    url: 'https://global.oup.com/academic/product/development-as-freedom-9780192893309?cc=gb&lang=en',
  },
  lockeLetterToleration: {
    author: 'John Locke',
    work: 'A Letter Concerning Toleration',
    year: '1689',
    kind: 'scholarly',
    context: 'Used as a political-theory anchor for religious toleration, the limits of coercion, and the distinction between civil and religious authority.',
    url: 'https://plato.stanford.edu/entries/locke-political/',
  },
  aquinasMoralPolitical: {
    author: 'Thomas Aquinas',
    work: 'Moral, Political, and Legal Philosophy',
    year: '13th century',
    kind: 'scholarly',
    context: 'A scholarly account of natural law, kingship, the common good, and the relationship between temporal and spiritual authority.',
    url: 'https://plato.stanford.edu/entries/aquinas-moral-political/',
  },
  spinozaPolitical: {
    author: 'Baruch Spinoza',
    work: 'Political Philosophy',
    year: '1670–1677',
    kind: 'scholarly',
    context: 'Used as a political-theory anchor for freedom of thought, religious authority, sovereignty, and the state’s relationship to public religion.',
    url: 'https://plato.stanford.edu/entries/spinoza-political/',
  },
};

// Every band receives an explicit list. These are references for the
// conceptual position, not claims that an author used our exact label.
export const BAND_CITATIONS = {
  economic: [
    ['marxEngelsManifesto', 'leninStateRevolution'],
    ['marxEngelsManifesto', 'leninStateRevolution'],
    ['marxEngelsManifesto', 'bernsteinEvolutionarySocialism'],
    ['bernsteinEvolutionarySocialism', 'keynesGeneralTheory'],
    ['keynesGeneralTheory', 'millOnLiberty'],
    ['keynesGeneralTheory', 'hayekKnowledge'],
    ['adamSmithWealth', 'hayekKnowledge'],
    ['adamSmithWealth', 'millOnLiberty'],
    ['adamSmithWealth', 'hayekKnowledge'],
    ['hayekKnowledge', 'nozickASU'],
  ],
  social: [
    ['wollstonecraftRights', 'millOnLiberty'],
    ['wollstonecraftRights', 'millOnLiberty'],
    ['wollstonecraftRights', 'millOnLiberty'],
    ['millOnLiberty', 'lockeSecondTreatise'],
    ['millOnLiberty', 'lockeSecondTreatise'],
    ['millOnLiberty', 'burkeReflections'],
    ['burkeReflections', 'tocquevilleDemocracy'],
    ['burkeReflections', 'tocquevilleDemocracy'],
    ['burkeReflections', 'renanNation'],
    ['burkeReflections', 'hobbesLeviathan'],
  ],
  authority: [
    ['bakuninStatism', 'millOnLiberty'],
    ['nozickASU', 'lockeSecondTreatise'],
    ['millOnLiberty', 'lockeSecondTreatise'],
    ['lockeSecondTreatise', 'millOnLiberty'],
    ['lockeSecondTreatise', 'millOnLiberty'],
    ['lockeSecondTreatise', 'tocquevilleDemocracy'],
    ['hobbesLeviathan', 'tocquevilleDemocracy'],
    ['hobbesLeviathan', 'burkeReflections'],
    ['arendtTotalitarianism', 'hobbesLeviathan'],
    ['arendtTotalitarianism', 'mussoliniDoctrine'],
  ],
  identity: [
    ['renanNation', 'andersonImaginedCommunities'],
    ['kantPerpetualPeace', 'renanNation'],
    ['kantPerpetualPeace', 'andersonImaginedCommunities'],
    ['renanNation', 'andersonImaginedCommunities'],
    ['renanNation', 'andersonImaginedCommunities'],
    ['renanNation', 'andersonImaginedCommunities'],
    ['renanNation', 'burkeReflections'],
    ['renanNation', 'burkeReflections'],
    ['renanNation', 'andersonImaginedCommunities'],
    ['hitlerMeinKampf', 'renanNation'],
  ],
  foreign: [
    ['kantPerpetualPeace', 'walzerJustWars'],
    ['kantPerpetualPeace', 'morgenthauRealism'],
    ['morgenthauRealism', 'mearsheimerTragedy'],
    ['kantPerpetualPeace', 'morgenthauRealism'],
    ['kantPerpetualPeace', 'morgenthauRealism'],
    ['morgenthauRealism', 'kantPerpetualPeace'],
    ['morgenthauRealism', 'mearsheimerTragedy'],
    ['mearsheimerTragedy', 'morgenthauRealism'],
    ['mearsheimerTragedy', 'clausewitzOnWar'],
    ['clausewitzOnWar', 'hitlerMeinKampf', 'mussoliniDoctrine'],
  ],
  religion: [
    ['millOnLiberty', 'wollstonecraftRights'],
    ['millOnLiberty', 'spinozaPolitical'],
    ['lockeLetterToleration', 'millOnLiberty'],
    ['lockeLetterToleration', 'kantPerpetualPeace'],
    ['lockeLetterToleration', 'spinozaPolitical'],
    ['kantPerpetualPeace', 'burkeReflections'],
    ['burkeReflections', 'lockeLetterToleration'],
    ['aquinasMoralPolitical', 'burkeReflections'],
    ['aquinasMoralPolitical', 'renanNation'],
    ['aquinasMoralPolitical', 'spinozaPolitical'],
  ],
};

export const ARCHETYPE_CITATIONS = {
  'authoritarian-collectivist': {
    summary: ['marxEngelsManifesto', 'leninStateRevolution', 'arendtTotalitarianism'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'leninStateRevolution'],
      social: ['marxEngelsManifesto', 'arendtTotalitarianism'],
      authority: ['leninStateRevolution', 'arendtTotalitarianism'],
      identity: ['marxEngelsManifesto', 'leninStateRevolution'],
      foreign: ['leninStateRevolution', 'morgenthauRealism'],
      religion: ['spinozaPolitical', 'hobbesLeviathan'],
    },
  },
  'historical-fascist': {
    summary: ['hitlerMeinKampf', 'mussoliniDoctrine', 'arendtTotalitarianism'],
    dimensions: {
      economic: ['mussoliniDoctrine', 'hitlerMeinKampf'],
      social: ['hitlerMeinKampf', 'mussoliniDoctrine'],
      authority: ['mussoliniDoctrine', 'arendtTotalitarianism'],
      identity: ['hitlerMeinKampf', 'mussoliniDoctrine'],
      foreign: ['hitlerMeinKampf', 'mussoliniDoctrine'],
      religion: ['mussoliniDoctrine', 'aquinasMoralPolitical'],
    },
  },
  'libertarian-market': {
    summary: ['hayekKnowledge', 'millOnLiberty', 'nozickASU'],
    dimensions: {
      economic: ['adamSmithWealth', 'hayekKnowledge', 'nozickASU'],
      social: ['millOnLiberty', 'lockeSecondTreatise'],
      authority: ['millOnLiberty', 'nozickASU'],
      identity: ['lockeSecondTreatise', 'millOnLiberty'],
      foreign: ['morgenthauRealism', 'millOnLiberty'],
      religion: ['lockeLetterToleration', 'millOnLiberty'],
    },
  },
  'progressive-liberal': {
    summary: ['millOnLiberty', 'wollstonecraftRights', 'kantPerpetualPeace'],
    dimensions: {
      economic: ['keynesGeneralTheory', 'millOnLiberty'],
      social: ['wollstonecraftRights', 'millOnLiberty'],
      authority: ['millOnLiberty', 'lockeSecondTreatise'],
      identity: ['kantPerpetualPeace', 'andersonImaginedCommunities'],
      foreign: ['kantPerpetualPeace', 'morgenthauRealism'],
      religion: ['lockeLetterToleration', 'spinozaPolitical'],
    },
  },
  'national-conservative': {
    summary: ['burkeReflections', 'renanNation', 'andersonImaginedCommunities'],
    dimensions: {
      economic: ['adamSmithWealth', 'burkeReflections'],
      social: ['burkeReflections', 'tocquevilleDemocracy'],
      authority: ['burkeReflections', 'hobbesLeviathan'],
      identity: ['renanNation', 'andersonImaginedCommunities'],
      foreign: ['morgenthauRealism', 'mearsheimerTragedy'],
      religion: ['burkeReflections', 'aquinasMoralPolitical'],
    },
  },
  'social-democratic': {
    summary: ['bernsteinEvolutionarySocialism', 'keynesGeneralTheory', 'millOnLiberty'],
    dimensions: {
      economic: ['bernsteinEvolutionarySocialism', 'keynesGeneralTheory'],
      social: ['millOnLiberty', 'wollstonecraftRights'],
      authority: ['lockeSecondTreatise', 'millOnLiberty'],
      identity: ['renanNation', 'andersonImaginedCommunities'],
      foreign: ['kantPerpetualPeace', 'morgenthauRealism'],
      religion: ['lockeLetterToleration', 'spinozaPolitical'],
    },
  },
  'classical-liberal': {
    summary: ['adamSmithWealth', 'lockeSecondTreatise', 'millOnLiberty'],
    dimensions: {
      economic: ['adamSmithWealth', 'hayekKnowledge'],
      social: ['millOnLiberty', 'lockeSecondTreatise'],
      authority: ['lockeSecondTreatise', 'millOnLiberty'],
      identity: ['lockeSecondTreatise', 'kantPerpetualPeace'],
      foreign: ['kantPerpetualPeace', 'millOnLiberty'],
      religion: ['lockeLetterToleration', 'millOnLiberty'],
    },
  },
  'democratic-socialist': {
    summary: ['marxEngelsManifesto', 'bernsteinEvolutionarySocialism', 'keynesGeneralTheory'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'bernsteinEvolutionarySocialism', 'keynesGeneralTheory'],
      social: ['wollstonecraftRights', 'millOnLiberty'],
      authority: ['millOnLiberty', 'lockeSecondTreatise'],
      identity: ['andersonImaginedCommunities', 'renanNation'],
      foreign: ['kantPerpetualPeace', 'walzerJustWars'],
      religion: ['lockeLetterToleration', 'millOnLiberty'],
    },
  },
  'anarchist-communalist': {
    summary: ['bakuninStatism', 'marxEngelsManifesto', 'millOnLiberty'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'bakuninStatism'],
      social: ['bakuninStatism', 'millOnLiberty'],
      authority: ['bakuninStatism', 'millOnLiberty'],
      identity: ['bakuninStatism', 'andersonImaginedCommunities'],
      foreign: ['bakuninStatism', 'kantPerpetualPeace'],
      religion: ['bakuninStatism', 'spinozaPolitical'],
    },
  },
  'green-commons': {
    summary: ['ostromGoverningCommons', 'millOnLiberty', 'kantPerpetualPeace'],
    dimensions: {
      economic: ['ostromGoverningCommons', 'adamSmithWealth'],
      social: ['ostromGoverningCommons', 'millOnLiberty'],
      authority: ['ostromGoverningCommons', 'lockeSecondTreatise'],
      identity: ['ostromGoverningCommons', 'kantPerpetualPeace'],
      foreign: ['ostromGoverningCommons', 'kantPerpetualPeace'],
      religion: ['lockeLetterToleration', 'ostromGoverningCommons'],
    },
  },
  'religious-traditionalist': {
    summary: ['burkeReflections', 'hobbesLeviathan', 'renanNation'],
    dimensions: {
      economic: ['burkeReflections', 'adamSmithWealth'],
      social: ['burkeReflections', 'hobbesLeviathan'],
      authority: ['hobbesLeviathan', 'burkeReflections'],
      identity: ['burkeReflections', 'renanNation'],
      foreign: ['morgenthauRealism', 'burkeReflections'],
      religion: ['aquinasMoralPolitical', 'burkeReflections'],
    },
  },
  'anti-colonial-liberation': {
    summary: ['gandhiHindSwaraj', 'fanonWretchedEarth', 'duboisBlackReconstruction'],
    dimensions: {
      economic: ['gandhiHindSwaraj', 'fanonWretchedEarth', 'duboisBlackReconstruction'],
      social: ['duboisBlackReconstruction', 'fanonWretchedEarth', 'gandhiHindSwaraj'],
      authority: ['gandhiHindSwaraj', 'fanonWretchedEarth', 'lockeSecondTreatise'],
      identity: ['fanonWretchedEarth', 'gandhiHindSwaraj', 'duboisBlackReconstruction'],
      foreign: ['gandhiHindSwaraj', 'fanonWretchedEarth', 'kantPerpetualPeace'],
      religion: ['gandhiHindSwaraj', 'spinozaPolitical'],
    },
  },
  communist: {
    summary: ['marxEngelsManifesto', 'leninStateRevolution', 'arendtTotalitarianism'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'leninStateRevolution'],
      social: ['marxEngelsManifesto', 'arendtTotalitarianism'],
      authority: ['leninStateRevolution', 'arendtTotalitarianism'],
      identity: ['marxEngelsManifesto', 'leninStateRevolution'],
      foreign: ['leninStateRevolution', 'morgenthauRealism'],
      religion: ['spinozaPolitical', 'leninStateRevolution'],
    },
  },
  'anarcho-capitalist': {
    summary: ['nozickASU', 'hayekKnowledge', 'millOnLiberty'],
    dimensions: {
      economic: ['nozickASU', 'hayekKnowledge'],
      social: ['millOnLiberty', 'lockeSecondTreatise'],
      authority: ['nozickASU', 'millOnLiberty'],
      identity: ['lockeSecondTreatise', 'millOnLiberty'],
      foreign: ['millOnLiberty', 'kantPerpetualPeace'],
      religion: ['lockeLetterToleration', 'millOnLiberty'],
    },
  },
  'anarcho-communist': {
    summary: ['bakuninStatism', 'marxEngelsManifesto', 'millOnLiberty'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'bakuninStatism'],
      social: ['bakuninStatism', 'millOnLiberty'],
      authority: ['bakuninStatism', 'millOnLiberty'],
      identity: ['bakuninStatism', 'andersonImaginedCommunities'],
      foreign: ['bakuninStatism', 'kantPerpetualPeace'],
      religion: ['bakuninStatism', 'spinozaPolitical'],
    },
  },
  conservative: {
    summary: ['burkeReflections', 'tocquevilleDemocracy', 'hobbesLeviathan'],
    dimensions: {
      economic: ['burkeReflections', 'adamSmithWealth'],
      social: ['burkeReflections', 'tocquevilleDemocracy'],
      authority: ['hobbesLeviathan', 'burkeReflections'],
      identity: ['burkeReflections', 'renanNation'],
      foreign: ['morgenthauRealism', 'burkeReflections'],
      religion: ['burkeReflections', 'aquinasMoralPolitical'],
    },
  },
  'civic-nationalist': {
    summary: ['renanNation', 'andersonImaginedCommunities', 'kantPerpetualPeace'],
    dimensions: {
      economic: ['adamSmithWealth', 'millOnLiberty'],
      social: ['millOnLiberty', 'renanNation'],
      authority: ['lockeSecondTreatise', 'millOnLiberty'],
      identity: ['renanNation', 'andersonImaginedCommunities'],
      foreign: ['kantPerpetualPeace', 'morgenthauRealism'],
      religion: ['lockeLetterToleration', 'millOnLiberty'],
    },
  },
  'ethnic-nationalist': {
    summary: ['renanNation', 'hitlerMeinKampf', 'arendtTotalitarianism'],
    dimensions: {
      economic: ['burkeReflections', 'hitlerMeinKampf'],
      social: ['burkeReflections', 'hitlerMeinKampf'],
      authority: ['hitlerMeinKampf', 'arendtTotalitarianism'],
      identity: ['hitlerMeinKampf', 'renanNation'],
      foreign: ['hitlerMeinKampf', 'mussoliniDoctrine'],
      religion: ['hitlerMeinKampf', 'burkeReflections'],
    },
  },
  monarchist: {
    summary: ['hobbesLeviathan', 'burkeReflections', 'aquinasMoralPolitical'],
    dimensions: {
      economic: ['burkeReflections', 'adamSmithWealth'],
      social: ['burkeReflections', 'aquinasMoralPolitical'],
      authority: ['hobbesLeviathan', 'aquinasMoralPolitical'],
      identity: ['burkeReflections', 'renanNation'],
      foreign: ['morgenthauRealism', 'burkeReflections'],
      religion: ['aquinasMoralPolitical', 'burkeReflections'],
    },
  },
  theocratic: {
    summary: ['aquinasMoralPolitical', 'hobbesLeviathan', 'lockeLetterToleration'],
    dimensions: {
      economic: ['aquinasMoralPolitical', 'adamSmithWealth'],
      social: ['aquinasMoralPolitical', 'burkeReflections'],
      authority: ['aquinasMoralPolitical', 'hobbesLeviathan'],
      identity: ['aquinasMoralPolitical', 'renanNation'],
      foreign: ['morgenthauRealism', 'aquinasMoralPolitical'],
      religion: ['aquinasMoralPolitical', 'lockeLetterToleration'],
    },
  },
  'christian-democratic': {
    summary: ['aquinasMoralPolitical', 'burkeReflections', 'keynesGeneralTheory'],
    dimensions: {
      economic: ['keynesGeneralTheory', 'burkeReflections'],
      social: ['aquinasMoralPolitical', 'burkeReflections'],
      authority: ['aquinasMoralPolitical', 'lockeSecondTreatise'],
      identity: ['burkeReflections', 'renanNation'],
      foreign: ['kantPerpetualPeace', 'morgenthauRealism'],
      religion: ['aquinasMoralPolitical', 'lockeLetterToleration'],
    },
  },
  'religious-socialist': {
    summary: ['gandhiHindSwaraj', 'marxEngelsManifesto', 'spinozaPolitical'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'gandhiHindSwaraj'],
      social: ['gandhiHindSwaraj', 'millOnLiberty'],
      authority: ['gandhiHindSwaraj', 'bakuninStatism'],
      identity: ['gandhiHindSwaraj', 'andersonImaginedCommunities'],
      foreign: ['gandhiHindSwaraj', 'kantPerpetualPeace'],
      religion: ['gandhiHindSwaraj', 'spinozaPolitical'],
    },
  },
  populist: {
    summary: ['renanNation', 'tocquevilleDemocracy', 'mussoliniDoctrine'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'adamSmithWealth'],
      social: ['tocquevilleDemocracy', 'burkeReflections'],
      authority: ['tocquevilleDemocracy', 'mussoliniDoctrine'],
      identity: ['renanNation', 'andersonImaginedCommunities'],
      foreign: ['morgenthauRealism', 'renanNation'],
      religion: ['burkeReflections', 'renanNation'],
    },
  },
  'centrist-pragmatist': {
    summary: ['millOnLiberty', 'keynesGeneralTheory', 'tocquevilleDemocracy'],
    dimensions: {
      economic: ['keynesGeneralTheory', 'hayekKnowledge'],
      social: ['millOnLiberty', 'tocquevilleDemocracy'],
      authority: ['lockeSecondTreatise', 'millOnLiberty'],
      identity: ['renanNation', 'kantPerpetualPeace'],
      foreign: ['kantPerpetualPeace', 'morgenthauRealism'],
      religion: ['lockeLetterToleration', 'millOnLiberty'],
    },
  },
  'liberal-constitutionalist': {
    summary: ['lockeSecondTreatise', 'millOnLiberty', 'kantPerpetualPeace'],
    dimensions: {
      economic: ['adamSmithWealth', 'lockeSecondTreatise'],
      social: ['millOnLiberty', 'lockeSecondTreatise'],
      authority: ['lockeSecondTreatise', 'millOnLiberty'],
      identity: ['lockeSecondTreatise', 'kantPerpetualPeace'],
      foreign: ['kantPerpetualPeace', 'millOnLiberty'],
      religion: ['lockeLetterToleration', 'millOnLiberty'],
    },
  },
  'militarist-imperialist': {
    summary: ['clausewitzOnWar', 'mearsheimerTragedy', 'mussoliniDoctrine'],
    dimensions: {
      economic: ['clausewitzOnWar', 'mussoliniDoctrine'],
      social: ['clausewitzOnWar', 'mussoliniDoctrine'],
      authority: ['clausewitzOnWar', 'arendtTotalitarianism'],
      identity: ['mearsheimerTragedy', 'mussoliniDoctrine'],
      foreign: ['clausewitzOnWar', 'mearsheimerTragedy'],
      religion: ['mussoliniDoctrine', 'burkeReflections'],
    },
  },
  'national-socialist': {
    summary: ['hitlerMeinKampf', 'mussoliniDoctrine', 'arendtTotalitarianism'],
    dimensions: {
      economic: ['mussoliniDoctrine', 'hitlerMeinKampf'],
      social: ['hitlerMeinKampf', 'mussoliniDoctrine'],
      authority: ['mussoliniDoctrine', 'arendtTotalitarianism'],
      identity: ['hitlerMeinKampf', 'mussoliniDoctrine'],
      foreign: ['hitlerMeinKampf', 'mussoliniDoctrine'],
      religion: ['mussoliniDoctrine', 'hitlerMeinKampf'],
    },
  },
  'libertarian-socialist': {
    summary: ['bakuninStatism', 'marxEngelsManifesto', 'millOnLiberty'],
    dimensions: {
      economic: ['marxEngelsManifesto', 'bakuninStatism'],
      social: ['bakuninStatism', 'millOnLiberty'],
      authority: ['bakuninStatism', 'millOnLiberty'],
      identity: ['bakuninStatism', 'andersonImaginedCommunities'],
      foreign: ['bakuninStatism', 'kantPerpetualPeace'],
      religion: ['bakuninStatism', 'spinozaPolitical'],
    },
  },
};
