// Structured research inventory for the educational atlas. Positions are
// ranges and interpretations, never claims that a person occupied one exact
// point on the app's five axes.
export const RESEARCH_REVIEW_DATE = '2026-09-12';

export const RESEARCH_DIMENSION_IDS = ['economic', 'social', 'authority', 'identity', 'foreign'];
export const RESEARCH_BAND_RANGES = [[-100, -81], [-80, -61], [-60, -41], [-40, -21], [-20, -1], [0, 19], [20, 39], [40, 59], [60, 79], [80, 100]];

const claim = (id, dimensionId, positionRange, evidenceType, summary, locator) => ({
  id,
  dimensionId,
  positionRange,
  evidenceType,
  summary,
  locator,
});

export const RESEARCH_WORKS = [
  {
    id: 'plato-republic',
    title: 'Republic',
    creators: ['Plato'],
    originalLanguage: 'Ancient Greek',
    publicationDate: 'c. 380 BCE',
    publisher: 'Classical work; modern translations vary',
    canonicalUrl: 'https://www.gutenberg.org/ebooks/1497',
    sourceType: 'primary text / book',
    evidenceRole: 'primary',
    discipline: 'political philosophy',
    regions: ['Ancient Greece / Mediterranean'],
    periods: ['Classical antiquity'],
    traditions: ['classical philosophy', 'philosopher-rule'],
    dimensionIds: ['social', 'authority', 'identity'],
    translationNote: 'The work survives through Greek textual traditions; English wording depends on the selected translation.',
    context: 'A primary philosophical dialogue used to study hierarchy, civic education, justice, and the design of a city—not as a modern party platform.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('plato-republic-authority', 'authority', [40, 90], 'primary-text reading', 'The dialogue gives political order a strongly hierarchical and educational form, with expertise and civic guardianship placed above unconstrained individual choice.', 'Books II–IV, VI–VII'),
      claim('plato-republic-social', 'social', [-40, 20], 'primary-text reading', 'Its account of civic education and role differentiation treats social formation as a public concern, but the dialogue is not a simple proxy for modern social conservatism.', 'Books II–V'),
    ],
  },
  {
    id: 'aristotle-politics',
    title: 'Politics',
    creators: ['Aristotle'],
    originalLanguage: 'Ancient Greek',
    publicationDate: '4th century BCE',
    publisher: 'Classical work; modern translations vary',
    canonicalUrl: 'https://classics.mit.edu/Aristotle/politics.html',
    sourceType: 'primary text / book',
    evidenceRole: 'primary',
    discipline: 'political philosophy',
    regions: ['Ancient Greece / Mediterranean'],
    periods: ['Classical antiquity'],
    traditions: ['classical republicanism', 'civic naturalism'],
    dimensionIds: ['economic', 'social', 'authority', 'identity'],
    translationNote: 'The MIT Classics text is an English translation; concepts such as polis, citizenship, and household require historical context.',
    context: 'A foundational analysis of constitutions, citizenship, property, class conflict, and civic education. Historical categories should not be treated as modern universal definitions.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('aristotle-politics-regime', 'authority', [20, 75], 'primary-text reading', 'The work compares rule by one, few, and many and treats constitutional design as a question of the common good and civic formation.', 'Books III–IV'),
      claim('aristotle-politics-property', 'economic', [-20, 35], 'primary-text reading', 'Aristotle discusses property, household management, and economic exchange without mapping neatly onto either modern capitalism or collectivism.', 'Books I–II'),
    ],
  },
  {
    id: 'confucius-analects',
    title: 'The Analects',
    creators: ['Confucius and later transmitters'],
    originalLanguage: 'Classical Chinese',
    publicationDate: 'compiled c. 5th–3rd century BCE',
    publisher: 'Chinese Text Project; source and translation information provided on site',
    canonicalUrl: 'https://ctext.org/analects/ens',
    sourceType: 'primary text / canonical collection',
    evidenceRole: 'primary',
    discipline: 'comparative political thought',
    regions: ['China / East Asia'],
    periods: ['Classical antiquity → imperial and modern reception'],
    traditions: ['Confucian political thought', 'East Asian statecraft'],
    dimensionIds: ['social', 'authority', 'identity', 'foreign'],
    translationNote: 'The site presents Classical Chinese with English translation choices and identifies its textual base; translations should be compared before quoting.',
    context: 'A layered canonical source for moral cultivation, role ethics, education, and legitimate rule. It is not identical to every later Confucian state or to modern authoritarianism.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('analects-moral-rule', 'authority', [25, 70], 'primary-text reading', 'Political legitimacy is tied to cultivated conduct, exemplary leadership, and the ordering of social roles rather than only to coercive power.', 'Analects 2.1–2.3; 12.11–12.19'),
      claim('analects-tradition', 'social', [-70, -10], 'primary-text reading', 'Filial piety, ritual, learning, and inherited roles are central themes, although later interpretations disagree about how flexible or reformist the tradition is.', 'Analects 1.2; 2.3; 12.1–12.2'),
    ],
  },
  {
    id: 'kautilya-arthashastra',
    title: 'Arthashastra',
    creators: ['Kautilya / traditionally attributed to Chanakya'],
    originalLanguage: 'Sanskrit',
    publicationDate: 'date and compilation history disputed; commonly associated with the Mauryan period',
    publisher: 'Historical treatise; editions and attribution vary',
    canonicalUrl: 'https://www.britannica.com/topic/Arthashastra',
    sourceType: 'primary text / statecraft treatise',
    evidenceRole: 'primary',
    discipline: 'comparative political thought',
    regions: ['South Asia'],
    periods: ['Ancient India'],
    traditions: ['Indic statecraft', 'realist state formation'],
    dimensionIds: ['economic', 'authority', 'identity', 'foreign'],
    translationNote: 'The text has contested dating, authorship, and translation history; entries should identify the edition used for any detailed quotation.',
    context: 'A statecraft manual that addresses administration, revenue, law, intelligence, war, and diplomacy. It is evidence about a tradition of governance, not proof that one historical state implemented every prescription.',
    review: { status: 'needs-review', confidence: 'medium' },
    claims: [
      claim('arthashastra-administration', 'authority', [60, 100], 'primary-text reading', 'The treatise presents a highly capable administrative state with surveillance, enforcement, revenue collection, and strategic control.', 'Books I–II'),
      claim('arthashastra-foreign', 'foreign', [-70, -10], 'primary-text reading', 'Its mandala theory and treatment of war and diplomacy are commonly read as strategic and realist rather than pacifist.', 'Books VI–XIII'),
    ],
  },
  {
    id: 'gandhi-hind-swaraj',
    title: 'Hind Swaraj / Indian Home Rule',
    creators: ['M. K. Gandhi'],
    originalLanguage: 'Gujarati; translated into English by Gandhi and later translators',
    publicationDate: '1909',
    publisher: 'Gandhi Heritage Portal / historical editions',
    canonicalUrl: 'https://www.gandhiheritageportal.org/mahatma-gandhi-books',
    sourceType: 'primary text / political essay',
    evidenceRole: 'primary',
    discipline: 'anti-colonial political thought',
    regions: ['India / South Asia'],
    periods: ['20th century anti-colonial thought'],
    traditions: ['Gandhian politics', 'anti-colonialism', 'nonviolent resistance'],
    dimensionIds: ['economic', 'social', 'authority', 'identity', 'foreign'],
    translationNote: 'The Gujarati original and English versions have distinct publication histories; the portal records the work’s manuscript and translation history.',
    context: 'A critical response to colonial rule and industrial civilization, useful for studying self-rule, nonviolence, decentralized economics, and the limits of copying European institutions.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('gandhi-hind-swaraj-self-rule', 'authority', [-75, -20], 'primary-text reading', 'Swaraj is presented as ethical self-rule and disciplined collective action, with resistance to domination rather than a simple rejection of all social authority.', 'Chapters VI–XVII'),
      claim('gandhi-hind-swaraj-economy', 'economic', [-35, 20], 'primary-text reading', 'The critique of industrial civilization and preference for self-sufficient, decentralized production place the work away from both laissez-faire capitalism and centralized state socialism.', 'Chapters VI, XIII, XIX'),
    ],
  },
  {
    id: 'dubois-black-reconstruction',
    title: 'Black Reconstruction in America, 1860–1880',
    creators: ['W. E. B. Du Bois'],
    originalLanguage: 'English',
    publicationDate: '1935',
    publisher: 'Harcourt, Brace and Company; editions vary',
    canonicalUrl: 'https://www.marxists.org/history/usa/black-history/marxists/black-reconstruction/',
    sourceType: 'historical study / book',
    evidenceRole: 'primary',
    discipline: 'history and political sociology',
    regions: ['United States / African diaspora'],
    periods: ['19th–20th century interpretation of Reconstruction'],
    traditions: ['Pan-Africanism', 'Black political thought', 'labor history'],
    dimensionIds: ['economic', 'social', 'identity', 'foreign'],
    translationNote: 'Original English; later editions and digital transcriptions should be checked against a publisher or library copy.',
    context: 'A major reinterpretation of Reconstruction centered on labor, emancipation, race, democracy, and the political agency of formerly enslaved people.',
    review: { status: 'needs-review', confidence: 'medium' },
    claims: [
      claim('dubois-reconstruction-labor', 'economic', [-35, 20], 'primary historical analysis', 'Du Bois links emancipation and Reconstruction to labor power, class conflict, and the struggle over who controls the fruits of work.', 'Chapters I–IV; “The General Strike”'),
      claim('dubois-reconstruction-democracy', 'social', [35, 85], 'primary historical analysis', 'The book treats Black political participation and equal citizenship as central to democratic reconstruction, while documenting the violent reversal of those gains.', 'Chapters VIII–XVI'),
    ],
  },
  {
    id: 'fanon-wretched-earth',
    title: 'The Wretched of the Earth',
    creators: ['Frantz Fanon'],
    originalLanguage: 'French',
    publicationDate: '1961',
    publisher: 'François Maspero; English edition by Grove Press',
    canonicalUrl: 'https://groveatlantic.com/book/the-wretched-of-the-earth/',
    sourceType: 'political theory / book',
    evidenceRole: 'primary',
    discipline: 'anti-colonial political thought',
    regions: ['Martinique / Algeria / Global South'],
    periods: ['20th century decolonization'],
    traditions: ['anti-colonialism', 'decolonial thought', 'revolutionary nationalism'],
    dimensionIds: ['economic', 'social', 'authority', 'identity', 'foreign'],
    translationNote: 'The app does not reproduce the copyrighted translation; the English edition is identified so readers can inspect the exact wording and translator’s choices.',
    context: 'A politically consequential analysis of colonial violence, national consciousness, psychological effects, and postcolonial reconstruction. Its arguments are internally tense and remain contested.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('fanon-colonial-economy', 'economic', [20, 70], 'primary-text reading', 'Fanon analyzes colonial political economy as extractive and argues for transformation rather than merely transferring formal sovereignty to a local elite.', '“The Pitfalls of National Consciousness”'),
      claim('fanon-violence', 'foreign', [-45, 20], 'primary-text reading', 'The text treats anti-colonial violence as historically situated resistance; it should not be collapsed into a general endorsement of violence in ordinary democratic disagreement.', '“On Violence”'),
    ],
  },
  {
    id: 'rawls-theory-justice',
    title: 'A Theory of Justice',
    creators: ['John Rawls'],
    originalLanguage: 'English',
    publicationDate: '1971',
    publisher: 'Harvard University Press',
    canonicalUrl: 'https://www.hup.harvard.edu/books/9780674000780',
    sourceType: 'political philosophy / book',
    evidenceRole: 'primary',
    discipline: 'political theory',
    regions: ['United States / transnational liberal theory'],
    periods: ['20th century liberal theory'],
    traditions: ['egalitarian liberalism', 'social liberalism'],
    dimensionIds: ['economic', 'social', 'authority', 'identity', 'foreign'],
    translationNote: 'Original English; page references depend on the edition.',
    context: 'A foundational contemporary liberal account of justice, equal basic liberties, fair opportunity, and distributive principles. It is used as a theory anchor, not as a direct measure of any party.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('rawls-difference-principle', 'economic', [-25, 25], 'primary-text reading', 'The difference principle permits inequalities only when they improve the position of the least advantaged, placing Rawls between laissez-faire and full economic collectivism.', '§§11–17; §§26–29'),
      claim('rawls-basic-liberties', 'authority', [-25, 25], 'primary-text reading', 'Equal basic liberties and public justification constrain state power while allowing institutions capable of securing fair conditions.', '§§11–14; §§39–40'),
    ],
  },
  {
    id: 'sen-development-freedom',
    title: 'Development as Freedom',
    creators: ['Amartya Sen'],
    originalLanguage: 'English',
    publicationDate: '1999',
    publisher: 'Oxford University Press',
    canonicalUrl: 'https://global.oup.com/academic/product/development-as-freedom-9780192893309',
    sourceType: 'political economy / book',
    evidenceRole: 'primary',
    discipline: 'economics and development studies',
    regions: ['India / Global'],
    periods: ['Contemporary political economy'],
    traditions: ['capability approach', 'developmental liberalism'],
    dimensionIds: ['economic', 'social', 'authority', 'identity', 'foreign'],
    translationNote: 'Original English; the book’s argument is distinct from later capability-measurement frameworks.',
    context: 'A capability-based approach treats development as expanding substantive freedoms rather than equating it with income or growth alone.',
    review: { status: 'needs-review', confidence: 'medium' },
    claims: [
      claim('sen-capabilities', 'economic', [-20, 25], 'primary-text reading', 'Markets are treated as important but insufficient; public action, social opportunities, and protection against deprivation are part of development.', 'Chapters 1–3'),
      claim('sen-democracy-freedom', 'social', [25, 75], 'primary-text reading', 'Public reasoning, education, health, and political freedoms are treated as constitutive of development rather than optional cultural extras.', 'Chapters 5–6'),
    ],
  },
  {
    id: 'ostrom-beyond-markets-states',
    title: 'Beyond Markets and States: Polycentric Governance of Complex Economic Systems',
    creators: ['Elinor Ostrom'],
    originalLanguage: 'English',
    publicationDate: '2009',
    publisher: 'Nobel Prize lecture',
    canonicalUrl: 'https://www.nobelprize.org/uploads/2018/06/ostrom_lecture.pdf',
    sourceType: 'Nobel Prize lecture / institutional analysis',
    evidenceRole: 'primary',
    discipline: 'economics and institutional analysis',
    regions: ['United States / Global commons research'],
    periods: ['Contemporary social science'],
    traditions: ['commons governance', 'polycentricity', 'institutional economics'],
    dimensionIds: ['economic', 'authority', 'social'],
    translationNote: 'Original English; lecture pagination follows the PDF version linked here.',
    context: 'A research-based challenge to the assumption that common resources must be either privatized or centrally controlled. It supports context-sensitive institutional design.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('ostrom-polycentric-governance', 'authority', [-55, 15], 'primary research synthesis', 'Rules can be created and enforced by users across nested, polycentric levels, so governance need not be reduced to either a unitary state or pure individual exit.', 'Nobel lecture; design principles'),
      claim('ostrom-commons', 'economic', [-30, 30], 'primary research synthesis', 'Common-pool resources can be governed through locally adapted rules; “common” does not mean unregulated or identical to state ownership.', 'Nobel lecture; “Governing the commons” discussion'),
    ],
  },
  {
    id: 'weber-politics-vocation',
    title: 'Politics as a Vocation',
    creators: ['Max Weber'],
    originalLanguage: 'German',
    publicationDate: '1919',
    publisher: 'Lecture; editions and translations vary',
    canonicalUrl: 'https://www.marxists.org/reference/subject/philosophy/works/ge/weber.htm',
    sourceType: 'primary lecture / political sociology',
    evidenceRole: 'primary',
    discipline: 'political sociology',
    regions: ['Germany / Europe'],
    periods: ['Early 20th century'],
    traditions: ['political realism', 'constitutional government', 'sociology of authority'],
    dimensionIds: ['authority', 'foreign', 'identity'],
    translationNote: 'The linked version is an English translation; terminology such as legitimate domination and responsibility ethics varies by translation.',
    context: 'A classic account of the state, legitimate domination, political leadership, ethics of conviction, and ethics of responsibility.',
    review: { status: 'needs-review', confidence: 'medium' },
    claims: [
      claim('weber-legitimate-domination', 'authority', [20, 70], 'primary-text reading', 'Weber defines the modern state through a claim to legitimate physical force and distinguishes traditional, charismatic, and legal-rational authority.', 'Opening sections; types of legitimate domination'),
      claim('weber-responsibility', 'foreign', [-35, 25], 'primary-text reading', 'Political action is framed as a responsibility for consequences, not simply the application of private moral conviction.', '“Politics as a Vocation” conclusion'),
    ],
  },
  {
    id: 'mariategui-seven-essays',
    title: 'Seven Interpretive Essays on Peruvian Reality',
    creators: ['José Carlos Mariátegui'],
    originalLanguage: 'Spanish',
    publicationDate: '1928',
    publisher: 'Biblioteca Amauta; English edition by University of Texas Press',
    canonicalUrl: 'https://utpress.utexas.edu/9780292776111/',
    sourceType: 'political economy / book',
    evidenceRole: 'primary',
    discipline: 'Latin American political thought',
    regions: ['Peru / Latin America'],
    periods: ['20th century'],
    traditions: ['Indigenous Marxism', 'anti-colonial socialism', 'Latin American Marxism'],
    dimensionIds: ['economic', 'social', 'identity', 'foreign'],
    translationNote: 'The Spanish original and English translation are not interchangeable; the Marxists.org transcription identifies a copyrighted English edition and should remain link-only.',
    context: 'A regional and Indigenous-centered Marxist analysis of land, labor, colonial legacies, education, religion, and Peruvian state formation.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('mariategui-land', 'economic', [25, 80], 'primary-text reading', 'The land question and Indigenous communal life are placed at the center of political economy rather than treated as peripheral to a European industrial sequence.', 'Essays I–III'),
      claim('mariategui-indigenous', 'identity', [0, 55], 'primary-text reading', 'Mariátegui combines class analysis with a historically specific account of Indigenous community and nation-building, resisting a one-size-fits-all international model.', 'Essays II–III; VI'),
    ],
  },
  {
    id: 'cesaire-discourse-colonialism',
    title: 'Discourse on Colonialism',
    creators: ['Aimé Césaire'],
    originalLanguage: 'French',
    publicationDate: '1950',
    publisher: 'Présence Africaine; English editions vary',
    canonicalUrl: 'https://monthlyreview.org/product/discourse-on-colonialism/',
    sourceType: 'anti-colonial essay / book',
    evidenceRole: 'primary',
    discipline: 'anti-colonial political thought',
    regions: ['Martinique / Caribbean / Global'],
    periods: ['20th century decolonization'],
    traditions: ['Négritude', 'anti-colonialism', 'decolonial thought'],
    dimensionIds: ['economic', 'social', 'identity', 'foreign'],
    translationNote: 'The work was written in French; the linked publisher record describes an English edition and its rights remain separate from the original text.',
    context: 'A critique of colonial domination, racial hierarchy, European self-image, and the material structure of empire.',
    review: { status: 'needs-review', confidence: 'medium' },
    claims: [
      claim('cesaire-colonial-economy', 'economic', [20, 65], 'primary-text reading', 'Colonialism is analyzed as a material system of extraction and dehumanization, not simply as cultural misunderstanding.', 'Opening sections'),
      claim('cesaire-racial-order', 'social', [35, 85], 'primary-text reading', 'The essay attacks racial hierarchy and colonial “civilization” claims while connecting them to violence and political domination.', 'Opening and concluding sections'),
    ],
  },
  {
    id: 'constitution-united-states',
    title: 'Constitution of the United States of America',
    creators: ['Constitutional Convention and ratifying publics'],
    originalLanguage: 'English',
    publicationDate: '1787; amendments from 1791 onward',
    publisher: 'U.S. Congress, Constitution Annotated',
    canonicalUrl: 'https://constitution.congress.gov/constitution/',
    sourceType: 'primary legal document',
    evidenceRole: 'primary',
    discipline: 'constitutional law and institutions',
    regions: ['United States'],
    periods: ['18th century → present constitutional order'],
    traditions: ['constitutional republicanism', 'liberal constitutionalism', 'federalism'],
    dimensionIds: ['authority', 'social', 'identity', 'foreign'],
    translationNote: 'Original English; the current page includes the constitutional text and explanatory annotations.',
    context: 'A legal and institutional source for federalism, separated powers, rights, citizenship, and the contested history of constitutional inclusion.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('us-constitution-checks', 'authority', [-20, 35], 'primary legal text', 'Separated powers, federalism, judicial authority, and enumerated rights distribute and constrain public power while leaving major historical exclusions to later amendment and litigation.', 'Articles I–III; Amendments I, V, XIV'),
      claim('us-constitution-rights', 'social', [20, 70], 'primary legal text', 'The Bill of Rights and later amendments provide legal anchors for speech, due process, equality, and citizenship, but their meaning has been historically contested.', 'Amendments I, V, XIII, XIV, XV, XIX'),
    ],
  },
  {
    id: 'constitution-india',
    title: 'The Constitution of India',
    creators: ['Constituent Assembly of India'],
    originalLanguage: 'English and Hindi, with additional official-language translations',
    publicationDate: '1950',
    publisher: 'Government of India, Legislative Department',
    canonicalUrl: 'https://www.indiacode.nic.in/bitstream/123456789/16124/1/the_constitution_of_india.pdf',
    sourceType: 'primary legal document',
    evidenceRole: 'primary',
    discipline: 'constitutional law and institutions',
    regions: ['India / South Asia'],
    periods: ['20th century → present constitutional order'],
    traditions: ['constitutional democracy', 'social justice constitutionalism', 'postcolonial state-building'],
    dimensionIds: ['social', 'authority', 'identity', 'economic'],
    translationNote: 'The linked government PDF identifies the English text; language and amendment context should be preserved when comparing provisions.',
    context: 'A postcolonial constitutional project combining universal suffrage, rights, social reform, federalism, and a strong developmental state.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('india-constitution-social-justice', 'social', [35, 90], 'primary legal text', 'Equality, anti-discrimination, affirmative measures, and abolition of untouchability place social transformation inside the constitutional project.', 'Preamble; Articles 14–17; 46'),
      claim('india-constitution-state', 'authority', [10, 55], 'primary legal text', 'The Constitution builds a powerful democratic state while subjecting it to rights, judicial review, elections, and federal division.', 'Articles 1–4; 32; 245–263'),
    ],
  },
  {
    id: 'constitution-south-africa',
    title: 'Constitution of the Republic of South Africa, 1996',
    creators: ['Constitutional Assembly of South Africa'],
    originalLanguage: 'English and South African official languages',
    publicationDate: '1996',
    publisher: 'South African Department of Justice and Constitutional Development',
    canonicalUrl: 'https://www.justice.gov.za/constitution/chp01.html',
    sourceType: 'primary legal document',
    evidenceRole: 'primary',
    discipline: 'constitutional law and institutions',
    regions: ['South Africa / Southern Africa'],
    periods: ['Late 20th century → present constitutional order'],
    traditions: ['transformative constitutionalism', 'constitutional democracy', 'anti-apartheid politics'],
    dimensionIds: ['social', 'authority', 'identity', 'economic'],
    translationNote: 'The Justice Department provides the official text and translations; the linked chapter is the English founding-provisions page.',
    context: 'A negotiated post-apartheid constitutional order that explicitly combines democracy, equality, human rights, rule of law, and social transformation.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('sa-constitution-democracy', 'authority', [-10, 35], 'primary legal text', 'Universal suffrage, multi-party democracy, accountability, openness, and constitutional supremacy are explicit founding values.', 'Chapter 1, sections 1–2'),
      claim('sa-constitution-equality', 'social', [45, 95], 'primary legal text', 'Non-racism, non-sexism, dignity, equality, and a justiciable Bill of Rights make social repair a constitutional commitment.', 'Chapter 1; Chapter 2'),
    ],
  },
  {
    id: 'universal-declaration-human-rights',
    title: 'Universal Declaration of Human Rights',
    creators: ['United Nations General Assembly'],
    originalLanguage: 'United Nations official languages',
    publicationDate: '1948',
    publisher: 'United Nations',
    canonicalUrl: 'https://www.un.org/en/about-us/universal-declaration-of-human-rights',
    sourceType: 'international declaration',
    evidenceRole: 'primary',
    discipline: 'international law and political theory',
    regions: ['Global / postwar international order'],
    periods: ['20th century → present'],
    traditions: ['human rights universalism', 'international constitutionalism'],
    dimensionIds: ['social', 'identity', 'foreign', 'authority', 'economic'],
    translationNote: 'The declaration is authenticated in multiple official languages; translations should not be treated as interchangeable quotations without a language and version note.',
    context: 'An international normative reference for dignity, equality, civil and political rights, social rights, and a universalist postwar vocabulary.',
    review: { status: 'reviewed', confidence: 'high' },
    claims: [
      claim('udhr-universal-rights', 'identity', [35, 95], 'primary international text', 'Rights are framed as belonging to all human beings rather than only to members of a particular nation.', 'Articles 1–2; 28'),
      claim('udhr-social-economic-rights', 'economic', [-20, 45], 'primary international text', 'The declaration pairs civil liberties with work, social security, education, and an adequate standard of living.', 'Articles 22–26'),
    ],
  },
];

const profile = (economic, social, authority, identity, foreign) => ({ economic, social, authority, identity, foreign });

const RAW_RESEARCH_PEOPLE = [
  {
    id: 'person-plato', fullName: 'Plato', dates: 'c. 428/427–348/347 BCE', roles: ['philosopher', 'teacher'], region: 'Ancient Greece / Mediterranean', period: 'Classical antiquity', selfDescription: 'No modern ideological self-description is available.', affiliations: ['Academy'], traditions: ['classical philosophy', 'philosopher-rule'], canonicalUrl: 'https://plato.stanford.edu/entries/plato/', sourceType: 'scholarly reference profile', discipline: 'political philosophy', confidence: 'documented', works: ['plato-republic'], profile: profile({ range: [-20, 25], note: 'The Republic discusses property and class roles in a civic design that does not map cleanly onto modern economic systems.' }, { range: [-45, 15], note: 'Education, virtue, and role formation are public concerns, but the dialogue is not a modern culture-war platform.' }, { range: [45, 90], note: 'The ideal city is highly ordered and hierarchical, with authority assigned by purported knowledge.' }, { range: [-35, 10], note: 'The political unit is the polis; its civic identity is neither modern nationalism nor cosmopolitan universalism.' }, { range: [-35, 20], note: 'The texts discuss the city’s security and war without establishing one modern foreign-policy doctrine.' }), context: 'This is a partial match for authority and civic education only. Plato’s dialogues contain competing voices and should not be reduced to one profile.', relatedPeople: ['person-aristotle'],
  },
  {
    id: 'person-aristotle', fullName: 'Aristotle', dates: '384–322 BCE', roles: ['philosopher', 'teacher'], region: 'Ancient Greece / Mediterranean', period: 'Classical antiquity', selfDescription: 'No modern ideological self-description is available.', affiliations: ['Lyceum'], traditions: ['classical republicanism', 'civic naturalism'], canonicalUrl: 'https://plato.stanford.edu/entries/aristotle/', sourceType: 'scholarly reference profile', discipline: 'political philosophy', confidence: 'documented', works: ['aristotle-politics'], profile: profile({ range: [-20, 35], note: 'Aristotle examines household management, property, exchange, and class conflict without a modern left/right equivalent.' }, { range: [-40, 20], note: 'Citizenship and civic virtue are linked to social roles that are historically exclusionary.' }, { range: [25, 75], note: 'He evaluates constitutions by their orientation to the common good and gives civic formation a strong role.' }, { range: [-35, 5], note: 'His analysis centers on the polis and civic membership rather than the modern nation-state.' }, { range: [-40, 15], note: 'The Politics addresses war and security but is not a contemporary foreign-policy program.' }), context: 'A documented source for classical civic categories, not a claim that Aristotle would fit a contemporary party or constitutional system.', relatedPeople: ['person-plato'],
  },
  {
    id: 'person-confucius', fullName: 'Confucius (Kongzi)', dates: '551–479 BCE', roles: ['teacher', 'philosopher'], region: 'China / East Asia', period: 'Spring and Autumn period', selfDescription: 'The surviving Analects are transmitted sayings rather than a modern autobiography.', affiliations: ['Lu scholarly tradition'], traditions: ['Confucian political thought', 'East Asian statecraft'], canonicalUrl: 'https://plato.stanford.edu/entries/confucius/', sourceType: 'scholarly reference profile', discipline: 'comparative political thought', confidence: 'documented', works: ['confucius-analects'], profile: profile({ range: [-15, 30], note: 'The Analects is not an economic treatise; the range reflects limited evidence rather than a precise economic position.' }, { range: [-75, -10], note: 'Ritual, filial piety, learning, and role ethics are central, though later Confucian traditions vary.' }, { range: [25, 70], note: 'Moral cultivation and exemplary rule are emphasized; this is not identical to coercive authoritarianism.' }, { range: [-20, 25], note: 'The tradition links social order to community and polity but predates modern nationalism.' }, { range: [0, 40], note: 'The Analects emphasizes order and humane rule more than a modern military strategy.' }), context: 'Use as a non-Western political-thought anchor with attention to textual layers, later reception, and translation.', relatedPeople: ['person-kautilya'],
  },
  {
    id: 'person-kautilya', fullName: 'Kautilya / Chanakya', dates: 'traditionally associated with the 4th century BCE; dating is disputed', roles: ['statesman', 'strategist', 'political thinker'], region: 'India / South Asia', period: 'Ancient India', selfDescription: 'Attribution is traditional and not equivalent to a verified modern authorial biography.', affiliations: ['Mauryan statecraft tradition'], traditions: ['Indic statecraft', 'realist state formation'], canonicalUrl: 'https://www.britannica.com/biography/Kautilya', sourceType: 'reference profile', discipline: 'comparative political thought', confidence: 'strongly-supported', works: ['kautilya-arthashastra'], profile: profile({ range: [15, 55], note: 'The Arthashastra describes taxation, regulation, public works, and state administration rather than a modern free-market/collectivist choice.' }, { range: [-45, 10], note: 'The work assumes stratified social institutions and a strongly ordered polity.' }, { range: [60, 100], note: 'Administrative capacity, intelligence, punishment, and executive strategy are prominent.' }, { range: [-55, -10], note: 'The treatise is concerned with the security and expansion of a territorial polity, not modern nationalism.' }, { range: [-75, -10], note: 'The mandala framework is commonly read as strategic, realist, and open to coercive statecraft.' }), context: 'Dating, authorship, and the relation between prescription and historical practice require continued review.', relatedPeople: ['person-confucius'],
  },
  {
    id: 'person-gandhi', fullName: 'Mohandas K. Gandhi', dates: '1869–1948', roles: ['lawyer', 'anti-colonial leader', 'political thinker'], region: 'India / South Africa', period: 'Late colonial and anti-colonial period', selfDescription: 'Advocated swaraj, satyagraha, nonviolence, and ethical self-rule in his own writings.', affiliations: ['Indian National Congress; Satyagraha movements'], traditions: ['Gandhian politics', 'anti-colonialism', 'nonviolent resistance'], canonicalUrl: 'https://www.gandhiheritageportal.org/', sourceType: 'institutional archive profile', discipline: 'anti-colonial political thought', confidence: 'documented', works: ['gandhi-hind-swaraj'], profile: profile({ range: [-40, 20], note: 'Gandhi criticized industrial civilization and favored decentralized production, but did not simply advocate state ownership.' }, { range: [-35, 25], note: 'His social thought combines reform, moral discipline, religious pluralism, and positions that changed across contexts.' }, { range: [-80, -20], note: 'Satyagraha and civil disobedience resist domination through disciplined nonviolent action rather than state coercion.' }, { range: [-55, 10], note: 'He supported Indian self-rule while also arguing for universal ethical obligations.' }, { range: [25, 85], note: 'Nonviolence and anti-militarism are central, although his positions must be read across historical crises.' }), context: 'Gandhi’s writings and political practice contain tensions, including views that are criticized today; the profile preserves those limits rather than treating him as a single moral symbol.', relatedPeople: ['person-ambedkar', 'person-mandela'],
  },
  {
    id: 'person-dubois', fullName: 'W. E. B. Du Bois', dates: '1868–1963', roles: ['historian', 'sociologist', 'writer', 'activist'], region: 'United States / African diaspora', period: 'Late 19th–20th century', selfDescription: 'Described himself through changing commitments to Black freedom, Pan-Africanism, socialism, and anti-colonialism.', affiliations: ['NAACP; Pan-African Congresses'], traditions: ['Pan-Africanism', 'Black political thought', 'labor history'], canonicalUrl: 'https://www.loc.gov/item/n79021164/', sourceType: 'library authority profile', discipline: 'history and political sociology', confidence: 'documented', works: ['dubois-black-reconstruction'], profile: profile({ range: [-45, 20], note: 'His economic analysis increasingly connected racial domination, labor, and socialism, but shifted over a long life.' }, { range: [40, 90], note: 'Equal citizenship and anti-racist democracy are central to his documented political work.' }, { range: [-5, 45], note: 'He defended democratic participation while at times supporting disciplined collective organization and later socialist states.' }, { range: [5, 70], note: 'Pan-African solidarity is transnational, but his analysis also addressed national citizenship and state power.' }, { range: [20, 70], note: 'Anti-colonial internationalism and solidarity are recurring themes, with positions changing across periods.' }), context: 'Du Bois is an especially useful example of why a five-axis profile must be time-indexed: his views evolved and cannot be represented by one permanent score.', relatedPeople: ['person-fanon', 'person-mariategui'],
  },
  {
    id: 'person-fanon', fullName: 'Frantz Fanon', dates: '1925–1961', roles: ['psychiatrist', 'writer', 'anti-colonial activist'], region: 'Martinique / Algeria / Global South', period: '20th century decolonization', selfDescription: 'Wrote as a critic of colonial domination and advocate of anti-colonial liberation.', affiliations: ['Algerian National Liberation Front (FLN)'], traditions: ['anti-colonialism', 'decolonial thought', 'revolutionary nationalism'], canonicalUrl: 'https://www.britannica.com/biography/Frantz-Fanon', sourceType: 'reference profile', discipline: 'anti-colonial political thought', confidence: 'documented', works: ['fanon-wretched-earth'], profile: profile({ range: [20, 70], note: 'He analyzed colonial extraction and called for postcolonial economic transformation, though not one uniform model.' }, { range: [25, 80], note: 'Anti-colonial emancipation and racial equality are central, with revolutionary politics creating internal tensions.' }, { range: [5, 65], note: 'His analysis of revolutionary struggle can involve centralized organization, but it is directed at colonial domination rather than ordinary pluralist disagreement.' }, { range: [-20, 55], note: 'National liberation and broader human emancipation coexist uneasily in his work.' }, { range: [-55, 20], note: 'He treated anti-colonial force as historically situated resistance; this must not be generalized into a universal endorsement of violence.' }), context: 'Fanon’s work is historically situated, contested, and not a direct template for contemporary policy.', relatedPeople: ['person-dubois', 'person-cesaire'],
  },
  {
    id: 'person-rawls', fullName: 'John Rawls', dates: '1921–2002', roles: ['political philosopher', 'professor'], region: 'United States', period: '20th century', selfDescription: 'Described his project as political liberalism and justice as fairness, with important changes between works.', affiliations: ['Harvard University'], traditions: ['egalitarian liberalism', 'social liberalism'], canonicalUrl: 'https://scholar.harvard.edu/johnrawls/home', sourceType: 'university archive profile', discipline: 'political theory', confidence: 'documented', works: ['rawls-theory-justice'], profile: profile({ range: [-30, 30], note: 'The difference principle supports redistribution, but Rawls did not advocate abolishing markets or private property in every form.' }, { range: [30, 75], note: 'Equal basic liberties and fair opportunity support a socially progressive liberal reading, though the theory leaves room for disagreement.' }, { range: [-30, 25], note: 'Public justification and basic liberties constrain coercion while legitimate institutions remain necessary.' }, { range: [25, 70], note: 'Later “Law of Peoples” thinking gives international equality and public reason a strong role.' }, { range: [25, 75], note: 'The theory favors a law-governed international order and a restrained account of war.' }), context: 'Rawls is a theory anchor, not a representative of a political party. His later work modifies and qualifies the 1971 framework.', relatedPeople: ['person-sen', 'person-ginsburg'],
  },
  {
    id: 'person-sen', fullName: 'Amartya Sen', dates: 'born 1933', roles: ['economist', 'philosopher', 'development scholar'], region: 'India / United Kingdom / Global', period: 'Contemporary', selfDescription: 'Developed the capability approach and defended public reasoning, democracy, and substantive freedom.', affiliations: ['Trinity College Cambridge; Harvard University'], traditions: ['capability approach', 'developmental liberalism'], canonicalUrl: 'https://www.nobelprize.org/prizes/economic-sciences/1998/sen/biographical/', sourceType: 'Nobel Prize biography', discipline: 'economics and development studies', confidence: 'documented', works: ['sen-development-freedom'], profile: profile({ range: [-25, 25], note: 'Sen treats markets as useful but insufficient and emphasizes public provision and capabilities.' }, { range: [30, 80], note: 'Freedom, education, health, gender equality, and public reasoning are central.' }, { range: [-30, 25], note: 'Democratic accountability and open public reasoning are central constraints on power.' }, { range: [35, 80], note: 'His approach is universalist and attentive to plural identities rather than nationalist closure.' }, { range: [20, 75], note: 'He generally supports international cooperation and human-security perspectives, with context-specific limits.' }), context: 'Sen’s positions are inferred from a broad body of economic and philosophical work; this entry cites the book used in the atlas and does not assign a single party label.', relatedPeople: ['person-rawls', 'person-ostrom'],
  },
  {
    id: 'person-ostrom', fullName: 'Elinor Ostrom', dates: '1933–2012', roles: ['political economist', 'institutional analyst'], region: 'United States / Global commons research', period: 'Contemporary', selfDescription: 'Studied how communities govern common-pool resources through rules and institutions.', affiliations: ['Indiana University; Workshop in Political Theory and Policy Analysis'], traditions: ['commons governance', 'polycentricity', 'institutional economics'], canonicalUrl: 'https://www.nobelprize.org/prizes/economic-sciences/2009/ostrom/facts/', sourceType: 'Nobel Prize profile', discipline: 'economics and institutional analysis', confidence: 'documented', works: ['ostrom-beyond-markets-states'], profile: profile({ range: [-35, 35], note: 'Her work rejects the assumption that every commons problem has either a privatization or centralized-state solution.' }, { range: [-15, 35], note: 'Local participation and mutual rule-making matter, but her framework does not prescribe one social-values agenda.' }, { range: [-60, 20], note: 'Polycentric, nested decision-making favors distributed authority and locally accountable rules.' }, { range: [0, 45], note: 'Institutional cooperation can be local or transnational; identity is not fixed by the commons framework.' }, { range: [0, 45], note: 'The work is primarily domestic/institutional and should not be overread as a foreign-policy doctrine.' }), context: 'Ostrom is included for the institutional alternative to the state-versus-market binary, not as a general ideological archetype.', relatedPeople: ['person-sen'],
  },
  {
    id: 'person-weber', fullName: 'Max Weber', dates: '1864–1920', roles: ['sociologist', 'historian', 'political thinker'], region: 'Germany / Europe', period: 'Late 19th–early 20th century', selfDescription: 'Analyzed politics through sociology, legitimacy, bureaucracy, and responsibility rather than a single ideology.', affiliations: ['University of Heidelberg; German constitutional debates'], traditions: ['political realism', 'sociology of authority'], canonicalUrl: 'https://www.britannica.com/biography/Max-Weber-German-sociologist', sourceType: 'reference profile', discipline: 'political sociology', confidence: 'documented', works: ['weber-politics-vocation'], profile: profile({ range: [-5, 40], note: 'His work is more institutional and sociological than a complete economic program.' }, { range: [-10, 35], note: 'He analyzed legitimacy and modernity without offering a simple traditionalist/progressive program.' }, { range: [25, 75], note: 'The state, bureaucracy, and legitimate domination are central analytical categories.' }, { range: [-15, 25], note: 'His analysis concerns national state formation and political responsibility rather than nationalism alone.' }, { range: [-40, 25], note: 'The ethics of responsibility and power politics resist a simple pacifist/interventionist classification.' }), context: 'Weber is a theorist of political action and authority, not a clean ideological “match” for a user’s result.', relatedPeople: ['person-rawls'],
  },
  {
    id: 'person-ambedkar', fullName: 'B. R. Ambedkar', dates: '1891–1956', roles: ['jurist', 'economist', 'constitutional founder', 'social reformer'], region: 'India / South Asia', period: '20th century anti-colonial and constitutional period', selfDescription: 'Advocated social democracy, equality, constitutional safeguards, and the annihilation of caste.', affiliations: ['Chair of the Constitution Drafting Committee; Scheduled Castes Federation'], traditions: ['social democracy', 'anti-caste politics', 'constitutionalism'], canonicalUrl: 'https://www.britannica.com/biography/B-R-Ambedkar', sourceType: 'reference profile', discipline: 'constitutional law and social reform', confidence: 'documented', works: ['constitution-india'], profile: profile({ range: [-40, 15], note: 'His economic arguments combine state action, labor protection, and democratic safeguards; they changed across policy questions.' }, { range: [55, 100], note: 'The destruction of caste hierarchy and equal citizenship are core commitments.' }, { range: [-25, 35], note: 'He favored constitutional institutions and legal safeguards rather than unchecked majoritarian or executive power.' }, { range: [25, 75], note: 'His constitutional vision is universalist while grounded in the social realities of India.' }, { range: [15, 60], note: 'The primary orientation is constitutional and social reconstruction, not a complete foreign-policy theory.' }), context: 'Ambedkar is included as a jurist and constitutional thinker whose work resists being reduced to either a caste, party, or economic label.', relatedPeople: ['person-gandhi', 'person-mandela'],
  },
  {
    id: 'person-mandela', fullName: 'Nelson Mandela', dates: '1918–2013', roles: ['lawyer', 'anti-apartheid leader', 'president'], region: 'South Africa', period: 'Late 20th century transition', selfDescription: 'Publicly combined African nationalism, non-racial democracy, reconciliation, and changing economic positions.', affiliations: ['African National Congress; Rivonia trial defense; Presidency of South Africa'], traditions: ['anti-apartheid politics', 'constitutional democracy', 'African nationalism'], canonicalUrl: 'https://www.nelsonmandela.org/', sourceType: 'institutional archive profile', discipline: 'constitutional politics and public leadership', confidence: 'documented', works: ['constitution-south-africa'], profile: profile({ range: [-30, 30], note: 'His political record moved between nationalization rhetoric, the Freedom Charter, mixed-economy governance, and later pragmatic policy.' }, { range: [45, 95], note: 'Non-racial citizenship and equality are central to the democratic transition associated with him.' }, { range: [-20, 35], note: 'The anti-apartheid movement included armed struggle and centralized organization, while the constitutional settlement constrained state power.' }, { range: [0, 55], note: 'South African national liberation and a non-racial, internationally engaged identity coexist.' }, { range: [20, 70], note: 'The transition emphasized diplomacy, reconciliation, and international legitimacy after a period of armed resistance.' }), context: 'Mandela’s life includes major changes in strategy and office; this entry connects him to constitutional transition, not every policy of the ANC or later governments.', relatedPeople: ['person-gandhi', 'person-ambedkar'],
  },
  {
    id: 'person-king', fullName: 'Martin Luther King Jr.', dates: '1929–1968', roles: ['minister', 'civil-rights leader', 'writer'], region: 'United States', period: '20th century civil-rights movement', selfDescription: 'Advocated nonviolent direct action, racial equality, economic justice, and a morally universal democracy.', affiliations: ['Southern Christian Leadership Conference'], traditions: ['civil-rights movement', 'Christian social ethics', 'nonviolent resistance'], canonicalUrl: 'https://kinginstitute.stanford.edu/', sourceType: 'university archive profile', discipline: 'civil-rights and social movements', confidence: 'documented', works: [], profile: profile({ range: [-45, 15], note: 'His later work connected civil rights to economic justice, labor, and critiques of poverty without settling every question of ownership.' }, { range: [65, 100], note: 'Abolition of racial hierarchy and equal citizenship were explicit commitments.' }, { range: [-45, 15], note: 'Nonviolent protest and civil disobedience challenged state authority while claiming democratic constitutional ideals.' }, { range: [35, 85], note: 'His moral universalism crossed national boundaries, while his activism remained rooted in U.S. citizenship and history.' }, { range: [40, 90], note: 'Nonviolence and opposition to militarism are strongly documented, especially in his later speeches.' }), context: 'King is a movement leader and public intellectual, not a complete five-axis policy platform. His economic views developed over time.', relatedPeople: ['person-dubois', 'person-ginsburg'],
  },
  {
    id: 'person-ginsburg', fullName: 'Ruth Bader Ginsburg', dates: '1933–2020', roles: ['lawyer', 'legal scholar', 'judge'], region: 'United States', period: 'Late 20th–early 21st century', selfDescription: 'Advocated constitutional equality and gender-equality litigation; judicial opinions are more reliable evidence than retrospective labels.', affiliations: ['American Civil Liberties Union; U.S. Supreme Court'], traditions: ['rights constitutionalism', 'gender equality', 'liberal legalism'], canonicalUrl: 'https://www.supremecourt.gov/about/biographyGinsburg.aspx', sourceType: 'official judicial biography', discipline: 'constitutional law', confidence: 'documented', works: ['constitution-united-states'], profile: profile({ range: [-20, 30], note: 'The cited constitutional work does not establish a complete economic program; the range is intentionally broad.' }, { range: [50, 95], note: 'Her litigation and opinions consistently addressed sex equality and anti-discrimination.' }, { range: [-25, 25], note: 'She worked through constitutional adjudication and institutional checks rather than executive or majoritarian absolutism.' }, { range: [20, 65], note: 'Rights were framed through constitutional citizenship and equal protection, with limited evidence for a full international-identity position.' }, { range: [0, 40], note: 'The record supports little more than a cautious institutional range on foreign policy.' }), context: 'This profile is deliberately partial: a judge’s legal record should not be converted into positions on issues outside the cases and writings that support them.', relatedPeople: ['person-rawls', 'person-king'],
  },
  {
    id: 'person-mariategui', fullName: 'José Carlos Mariátegui', dates: '1894–1930', roles: ['writer', 'journalist', 'political thinker', 'organizer'], region: 'Peru / Latin America', period: 'Early 20th century', selfDescription: 'Developed a locally grounded socialist and Indigenous-centered analysis of Peru.', affiliations: ['Peruvian Socialist Party tradition; Amauta'], traditions: ['Indigenous Marxism', 'anti-colonial socialism', 'Latin American Marxism'], canonicalUrl: 'https://www.marxists.org/archive/mariateg/works/7-interpretive-essays/index.htm', sourceType: 'archival text profile', discipline: 'Latin American political thought', confidence: 'documented', works: ['mariategui-seven-essays'], profile: profile({ range: [30, 85], note: 'Land, labor, and anti-oligarchic transformation are central, though his socialism is adapted to Peru rather than copied from Europe.' }, { range: [20, 70], note: 'He combined social emancipation with a culturally and historically specific analysis of Indigenous life.' }, { range: [5, 55], note: 'The political project is organized and transformative, but not reducible to a fixed authoritarian score.' }, { range: [0, 55], note: 'His work joins national and Indigenous questions to international socialism without collapsing one into the other.' }, { range: [20, 75], note: 'Anti-imperial and internationalist themes are strong, with strategy tied to Peruvian conditions.' }), context: 'Mariátegui is included to widen the canon beyond European Marxism and to show why regional history matters to spectrum interpretation.', relatedPeople: ['person-dubois', 'person-cesaire'],
  },
  {
    id: 'person-cesaire', fullName: 'Aimé Césaire', dates: '1913–2008', roles: ['poet', 'writer', 'politician', 'anti-colonial thinker'], region: 'Martinique / Caribbean', period: '20th century decolonization', selfDescription: 'Developed Négritude and an anti-colonial critique of racial hierarchy and empire.', affiliations: ['Mayor of Fort-de-France; French National Assembly'], traditions: ['Négritude', 'anti-colonialism', 'decolonial thought'], canonicalUrl: 'https://www.britannica.com/biography/Aime-Cesaire', sourceType: 'reference profile', discipline: 'anti-colonial political thought', confidence: 'documented', works: ['cesaire-discourse-colonialism'], profile: profile({ range: [15, 65], note: 'His anti-colonial critique is materially focused, but it does not prescribe one uniform postcolonial economic system.' }, { range: [40, 90], note: 'He attacked racial hierarchy and colonial dehumanization while participating in electoral politics.' }, { range: [-20, 35], note: 'He worked within and against French institutions; the profile therefore stays broad.' }, { range: [0, 65], note: 'Négritude and anti-colonial identity are not reducible to European nationalism or a simple internationalism score.' }, { range: [15, 75], note: 'His work critiques empire and supports anti-colonial solidarity rather than a complete military doctrine.' }), context: 'Césaire’s poetry, political office, and anti-colonial essays should be read together but not assumed to express a single unchanging position.', relatedPeople: ['person-fanon', 'person-mariategui'],
  },
];

const workTitleById = Object.fromEntries(RESEARCH_WORKS.map((work) => [work.id, work.title]));

export const RESEARCH_PEOPLE = RAW_RESEARCH_PEOPLE.map((person) => ({
  ...person,
  claimEvidence: RESEARCH_DIMENSION_IDS.map((dimensionId) => ({
    dimensionId,
    evidenceType: person.works.length ? 'documented work + analyst range' : 'institutional record + analyst range',
    sourceIds: person.works,
    sourceLabel: person.works.length ? person.works.map((workId) => workTitleById[workId]).join(' · ') : 'Institutional archive and documented public record',
    sourceUrl: person.canonicalUrl,
    locator: person.works.length ? `See the cited work record${person.works.length > 1 ? 's' : ''} and its claim locations.` : 'Archive profile, indexed speeches, opinions, or documented public record; exact scope varies by dimension.',
    summary: person.profile[dimensionId].note,
  })),
}));

export const RESEARCH_RELATIONSHIPS = [
  { from: 'person-plato', to: 'person-aristotle', type: 'influenced', note: 'Aristotle studied in Plato’s Academy and later developed significant critiques of Platonic political theory.' },
  { from: 'person-confucius', to: 'person-kautilya', type: 'distinct_from', note: 'Both are classical Asian political-thought anchors, but their textual traditions, concepts of rule, and historical contexts differ.' },
  { from: 'person-gandhi', to: 'person-ambedkar', type: 'opposed', note: 'They shared anti-colonial context but sharply disagreed over caste, representation, social reform, and political strategy.' },
  { from: 'person-dubois', to: 'person-mariategui', type: 'close_to', note: 'Both connected class and racial/colonial structures to regional history, without being interchangeable.' },
  { from: 'person-dubois', to: 'person-fanon', type: 'influenced', note: 'Du Bois’s analysis of race, colonialism, and Black internationalism forms part of the intellectual context later taken up by Fanon.' },
  { from: 'person-fanon', to: 'person-cesaire', type: 'influenced', note: 'Césaire was a major anti-colonial and Négritude influence on Fanon’s intellectual formation.' },
  { from: 'person-rawls', to: 'person-sen', type: 'close_to', note: 'Both develop egalitarian theories of justice, while Sen criticizes resource-focused approaches through the capability perspective.' },
  { from: 'person-sen', to: 'person-ostrom', type: 'close_to', note: 'Both emphasize human capabilities and institutional diversity, though they study different explanatory problems.' },
  { from: 'person-gandhi', to: 'person-mandela', type: 'historically_contextualized', note: 'Both are associated with anti-colonial struggle and nonviolence, but Mandela’s political trajectory included armed struggle and a different constitutional settlement.' },
  { from: 'person-king', to: 'person-dubois', type: 'successor_to', note: 'King’s movement inherited and revised earlier Black freedom, anti-racist, and democratic traditions that Du Bois helped develop.' },
  { from: 'person-ambedkar', to: 'person-ginsburg', type: 'close_to', note: 'Both illuminate rights-based legal equality, but their jurisdictions, social problems, and constitutional contexts are distinct.' },
  { from: 'person-weber', to: 'person-rawls', type: 'distinct_from', note: 'Weber analyzes legitimacy and political responsibility sociologically; Rawls offers a normative theory of justice.' },
];

export const RESEARCH_SECTIONS = [
  { id: 'foundations', label: 'Foundations', description: 'Core concepts and original texts.' },
  { id: 'schools', label: 'Schools and traditions', description: 'Internal branches, regional variants, and disagreements.' },
  { id: 'people', label: 'People', description: 'Documented examples by dimension and period.' },
  { id: 'law', label: 'Law and institutions', description: 'Constitutions, courts, legal doctrines, and institutional design.' },
  { id: 'movements', label: 'Movements and parties', description: 'Historical development and regional variation.' },
  { id: 'critiques', label: 'Critiques and alternatives', description: 'Serious challenges from neighboring traditions.' },
  { id: 'reference', label: 'Reference guide', description: 'Definitions, bibliography, and research limitations.' },
];

export const RESEARCH_BACKLOG = [
  { id: 'backlog-indigenous-governance', priority: 'high', title: 'Add Indigenous governance traditions with community-reviewed sources', reason: 'Current coverage is still too thin for Indigenous constitutional and ecological traditions.' },
  { id: 'backlog-african-legal-thought', priority: 'high', title: 'Expand African legal and political thought beyond anti-apartheid constitutionalism', reason: 'Add precolonial, postcolonial, feminist, and contemporary African scholarship with regional reviewers.' },
  { id: 'backlog-islamic-political-thought', priority: 'high', title: 'Add Islamic political thought as internally diverse schools', reason: 'The taxonomy has a label, but the evidence inventory needs primary texts and disagreement-aware scholarship.' },
  { id: 'backlog-latin-america', priority: 'medium', title: 'Add more Latin American constitutional and feminist sources', reason: 'Mariátegui and Césaire widen coverage, but do not represent the region’s full diversity.' },
  { id: 'backlog-legal-case-law', priority: 'medium', title: 'Add claim-level court opinions for rights and executive power', reason: 'Constitutional texts alone do not show how legal doctrines operate in practice.' },
  { id: 'backlog-contemporary-parties', priority: 'medium', title: 'Add time-indexed party platforms with versioned datasets', reason: 'Current people and works should be complemented by carefully dated party documents, not assumed from labels.' },
];

function overlaps(range, band) {
  return Array.isArray(range) && range[0] <= band[1] && range[1] >= band[0];
}

function coverageForBand(dimensionId, band) {
  const works = RESEARCH_WORKS.filter((work) => work.claims.some((item) => item.dimensionId === dimensionId && overlaps(item.positionRange, band))).map(({ id }) => id);
  const people = RESEARCH_PEOPLE.filter((person) => overlaps(person.profile?.[dimensionId]?.range, band)).map(({ id }) => id);
  const total = new Set([...works, ...people]).size;
  return { works, people, total, status: total >= 3 ? 'strong' : total >= 1 ? 'thin' : 'gap' };
}

export const RESEARCH_COVERAGE_MATRIX = RESEARCH_DIMENSION_IDS.map((dimensionId) => ({
  dimensionId,
  bands: RESEARCH_BAND_RANGES.map((range, index) => ({ band: index + 1, range, ...coverageForBand(dimensionId, range) })),
}));
