import { RESEARCH_WORKS } from './research.js';

const REVIEWED_AT = '2026-09-12';
const RESEARCH_WORKS_REVIEWED_AT = '2026-09-13';

function record(rightsStatus, license, commercialUse, publicationStatus, action, notes) {
  return {
    reviewedAt: REVIEWED_AT,
    rightsStatus,
    license,
    commercialUse,
    publicationStatus,
    action,
    notes,
  };
}

const LINK_ONLY = record(
  'copyrighted / link-only',
  'No reuse licence identified for the referenced page or publication.',
  'Original summaries and links only; no copied text, tables, screenshots, or media cleared.',
  'link-only',
  'Use as a source for independent analysis and link to the original. Do not reproduce the source content.',
  'Citation is not a licence to republish the work.',
);

const PUBLIC_DOMAIN_CANDIDATE = record(
  'public-domain candidate',
  'Underlying historical work may be public domain; the specific edition or translation is not automatically cleared.',
  'Verify the exact edition, translation, jurisdiction, and moral-rights position before commercial quotation or redistribution.',
  'review-required',
  'Use a stable bibliographic link and an original paraphrase. Quote only after the edition/translation review is recorded.',
  'Public-domain status belongs to a work and edition in a jurisdiction, not automatically to every online transcription or translation.',
);

const PERMISSION_SENSITIVE = record(
  'permission-sensitive',
  'Copyrighted or rights status not cleared for reproduction.',
  'No commercial reproduction, translation, adaptation, or redistribution cleared.',
  'link-only',
  'Link and paraphrase independently. Obtain permission or qualified legal review before reproducing expressive text or media.',
  'A short quote may still require a case-specific exception analysis.',
);

const RESTRICTED_DATA = record(
  'restricted-data',
  'Terms of use restrict redistribution and/or commercial use.',
  'Do not publish the original dataset, bulk extracts, or a mirror from this repository without written permission.',
  'link-only',
  'Use only permitted citations and derived summaries. Preserve the provider’s terms, provenance, and version information.',
  'Derived facts and independently authored descriptions require their own provenance record.',
);

const OPEN_LICENSE = record(
  'open-license',
  'Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).',
  'Commercial use is allowed when attribution and ShareAlike obligations are followed.',
  'allowed-with-attribution',
  'If data or adapted data is distributed, include the required attribution, licence link, version, and indication of changes.',
  'This status applies to the V-Dem dataset terms, not automatically to every page, graphic, or third-party source linked from V-Dem.',
);

const OFFICIAL_TEXT = record(
  'official or institutional text / jurisdiction-dependent',
  'The official text is publicly accessible, but no blanket commercial-reuse licence is recorded for this project.',
  'Publish an independent summary and link to the official text. Do not assume that public access clears reproduction, translation, or derivative publication.',
  'link-only',
  'Link to the official repository and paraphrase independently. Verify the issuing institution’s terms before reproducing text, translations, or facsimiles.',
  'Legal and international instruments may have special publication rules, but the exact repository and jurisdiction still control reuse.',
);

const COMMUNITY_CONTROLLED = record(
  'community-controlled / permission-sensitive',
  'No blanket commercial-reuse licence identified for the oral tradition, community-held knowledge, or modern transcription/translation.',
  'Do not commercially reproduce, adapt, or package the tradition, performance, translation, or transcription without source-owner or community review.',
  'link-only',
  'Use contextual description and a stable link only. Preserve community attribution and distinguish living oral transmission from a later written edition.',
  'A public archive or UNESCO listing documents access or recognition; it does not automatically grant commercial rights to every version or translation.',
);

const PUBLIC_DOMAIN_CANDIDATE_WORK_IDS = new Set([
  'plato-republic',
  'aristotle-politics',
  'confucius-analects',
  'kautilya-arthashastra',
  'ptahhotep-instruction',
  'hammurabi-code',
  'thucydides-peloponnesian-war',
  'polybius-histories',
  'cicero-de-republica',
  'augustine-city-of-god',
  'justinian-corpus-juris-civilis',
  'aquinas-de-regno',
  'magna-carta-1215',
  'constitution-medina',
  'laozi-dao-de-jing',
  'sunzi-art-of-war',
  'mencius',
  'xunzi',
  'mozi',
  'han-feizi',
  'book-lord-shang',
  'ashoka-edicts',
  'manusmriti',
  'tirukkural',
  'agganna-sutta',
  'al-farabi-virtuous-city',
  'al-mawardi-ordinances',
  'nizam-siyasatnama',
  'ibn-khaldun-muqaddimah',
  'machiavelli-prince',
  'machiavelli-discourses',
  'grotius-rights-war-peace',
  'hobbes-leviathan',
  'locke-second-treatise',
  'rousseau-social-contract',
  'montesquieu-spirit-laws',
  'wollstonecraft-vindication',
  'federalist-papers',
  'tocqueville-democracy-america',
  'mill-on-liberty',
  'marx-engels-communist-manifesto',
  'maimonides-mishneh-torah',
  'rizal-philippines-century',
]);

const OFFICIAL_TEXT_WORK_IDS = new Set([
  'constitution-united-states',
  'constitution-india',
  'constitution-south-africa',
  'universal-declaration-human-rights',
  'treaty-waitangi',
]);

const COMMUNITY_CONTROLLED_WORK_IDS = new Set([
  'great-law-peace',
  'manden-charter',
  'sunjata-epic',
  'florentine-codex',
]);

function researchWorkRights(work) {
  const base = OFFICIAL_TEXT_WORK_IDS.has(work.id)
    ? OFFICIAL_TEXT
    : COMMUNITY_CONTROLLED_WORK_IDS.has(work.id)
      ? COMMUNITY_CONTROLLED
      : PUBLIC_DOMAIN_CANDIDATE_WORK_IDS.has(work.id)
        ? PUBLIC_DOMAIN_CANDIDATE
        : PERMISSION_SENSITIVE;

  const focus = work.originalLanguage.includes('translated') || work.originalLanguage.includes('translations')
    ? 'Translation and edition review is mandatory because the inventory includes later translations.'
    : work.sourceType.includes('manuscript')
      ? 'Archive, manuscript-image, and transcription rights must be checked separately.'
      : work.sourceType.includes('inscription') || work.sourceType.includes('legal')
        ? 'Check the exact inscription, official repository, transcription, and jurisdiction before quoting.'
        : 'Check the exact edition, transcription, translation, and repository terms before quoting.';

  return {
    ...base,
    reviewedAt: RESEARCH_WORKS_REVIEWED_AT,
    notes: `${base.notes} ${focus} Inventory record: ${work.title} (${work.originalLanguage}).`,
  };
}

const RESEARCH_WORK_RIGHTS = Object.fromEntries(
  RESEARCH_WORKS.map((work) => [work.id, researchWorkRights(work)]),
);

const RIGHTS_RECORDS = {
  researchWorks: RESEARCH_WORK_RIGHTS,
  researchSources: {
    panXu: { ...LINK_ONLY, notes: 'Scholarly article used as a claim-level reference; the article text is not reproduced.' },
    sepSocialism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepLuxemburg: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepLiberalism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    oxfordLiberalismResearch: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordNationalSocialism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordNaziGermany: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    ushmmNaziRacism: { ...PERMISSION_SENSITIVE, notes: 'United States Holocaust Memorial Museum historical source used for independent educational synthesis; no institutional text, images, or graphics are reproduced.' },
    ushmmThirdReich: { ...PERMISSION_SENSITIVE, notes: 'United States Holocaust Memorial Museum historical source used for independent educational synthesis; no institutional text, images, or graphics are reproduced.' },
    ushmmNaziPartyPlatform: { ...PERMISSION_SENSITIVE, notes: 'United States Holocaust Memorial Museum documentary source used for independent historical synthesis; no institutional text, documents, images, or graphics are reproduced.' },
    unGenocideConvention: { ...OFFICIAL_TEXT, notes: 'United Nations legal-history page used to link and independently summarize the Genocide Convention; no treaty text or facsimile is reproduced.' },
    oxfordImperialism: { ...LINK_ONLY, notes: 'Oxford Bibliographies entry used as a linked scholarly source; no entry text, tables, or figures are reproduced.' },
    oxfordMilitarism: { ...LINK_ONLY, notes: 'Oxford Bibliographies entry used as a linked scholarly source; no entry text, tables, or figures are reproduced.' },
    oxfordPoliticalEconomyMilitarism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordColonialismEmpireSociology: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    cambridgeMilitarismImperialism: { ...LINK_ONLY, notes: 'Cambridge scholarly chapter used as a linked comparative historical source; no chapter text, tables, or figures are reproduced.' },
    unCharterForce: { ...OFFICIAL_TEXT, notes: 'United Nations Security Council page used for independent synthesis of Charter principles; no UN text, graphics, or institutional materials are reproduced.' },
    usStateMahan: { ...OFFICIAL_TEXT, notes: 'U.S. Office of the Historian page used for independent historical synthesis; no institutional text, images, or graphics are reproduced.' },
    sepConstitutionalism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    oxfordConstitutionalJustice: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    oxfordBritishConstitutionalism: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    locFederalistPapers: { ...OFFICIAL_TEXT, notes: 'Library of Congress guide used to locate and contextualize primary documents; no guide text, scans, or facsimiles are reproduced.' },
    unRuleLawHumanRights: { ...OFFICIAL_TEXT, notes: 'United Nations rule-of-law page used for independent synthesis; no UN text, graphics, or institutional materials are reproduced.' },
    echrConvention: { ...OFFICIAL_TEXT, notes: 'European Court of Human Rights treaty page used as a link to the official text and institutional context; no treaty text or facsimile is reproduced.' },
    colonialLiberalismExclusion: { ...LINK_ONLY, notes: 'SAGE scholarly article used as a linked historical source; no article text, tables, or figures are reproduced.' },
    sepLibertarianism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepMill: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepLibertyPositiveNegative: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepConservatism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    bpbConservatism: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical synthesis; no bpb text, images, or graphics are reproduced.' },
    sepNationalism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    bpbNationalism: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical and conceptual synthesis; no bpb text, images, or graphics are reproduced.' },
    cambridgeKohnDichotomy: { ...LINK_ONLY, notes: 'Cambridge scholarly article used as a linked source; no article text, tables, or figures are reproduced.' },
    sepColonialism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    unIndigenousDeclaration: { ...OFFICIAL_TEXT, notes: 'United Nations digital-library record used for independent synthesis of Indigenous collective rights and self-determination; no UN text, translation, or facsimile is reproduced.' },
    oxfordTribalConstitutions: { ...LINK_ONLY, notes: 'Oxford Handbook chapter used as a linked scholarly legal-history source; no chapter text, tables, or figures are reproduced.' },
    waitangiTribunalTreaty: { ...OFFICIAL_TEXT, notes: 'Waitangi Tribunal institutional source used for independent synthesis of treaty texts and Māori authority; no Tribunal text, translation, or document image is reproduced.' },
    pmcIndigenousDeliberative: { ...LINK_ONLY, notes: 'Peer-reviewed article accessed through PubMed Central and used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    vdem: { ...OPEN_LICENSE },
    wvs: { ...RESTRICTED_DATA, notes: 'WVS documentation states that data access/use is subject to non-redistribution terms and, for some files, non-commercial conditions.' },
    ches: { ...PERMISSION_SENSITIVE, notes: 'The public site provides datasets and codebooks, but this project does not rely on a cleared right to redistribute CHES files.' },
    manifesto: { ...RESTRICTED_DATA, notes: 'Manifesto Project terms prohibit redistribution except when authorized in writing and require provenance and citation.' },
    foreignPolicy: { ...LINK_ONLY, notes: 'Journal article used as a linked scholarly source; no article text, figures, or tables are reproduced.' },
    oecdWelfareModels: { ...LINK_ONLY, notes: 'OECD comparative policy source used for independent synthesis of welfare-regime distinctions; no OECD text, tables, or graphics are reproduced.' },
    ghdiGodesberg: { ...LINK_ONLY, notes: 'Historical document repository used for independent synthesis of the 1959 SPD programme; no GHDI text, scans, or translation are reproduced.' },
    jauresArchive: { ...LINK_ONLY, notes: 'Primary-source archive used as a linked historical source; no translated text or archive material is reproduced.' },
    openTextbook: { ...RESTRICTED_DATA, license: 'CC BY-NC 4.0 (as listed by Open Textbook Library).', commercialUse: 'Non-commercial reuse only under the licence; commercial reproduction or adaptation is not cleared.', notes: 'Use the textbook for research and link-level citation. Do not copy its chapters, tables, or wording into an ad-supported product without permission.' },
    sepAnarchism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    cambridgeAnarchismBolshevism: { ...LINK_ONLY, notes: 'Cambridge scholarly article used as a linked historical source; no article text, tables, or figures are reproduced.' },
    iloCooperatives: { ...OFFICIAL_TEXT, notes: 'International Labour Organization page used for independent synthesis of cooperative principles; no ILO text, graphics, or institutional materials are reproduced.' },
    iloWorkerCooperatives: { ...OFFICIAL_TEXT, notes: 'International Labour Organization resource used for independent synthesis; no ILO text, graphics, or institutional materials are reproduced.' },
    sepEnvironmentalEthics: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepClimateJustice: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    ipccAr6Synthesis: { ...LINK_ONLY, notes: 'IPCC assessment used for independently authored summaries of climate risk and policy context; no IPCC text, figures, or graphics are reproduced.' },
    socialEcologyMunicipalism: { ...LINK_ONLY, notes: 'Institute for Social Ecology page used for independent synthesis of Bookchin’s proposal; no page text, graphics, or chapters are reproduced.' },
    makhnoRuralAnarchism: { ...LINK_ONLY, notes: 'Scholarly book record used as a linked historical source; no book text, scans, or tables are reproduced.' },
    cambridgeSpanishAnarchism: { ...LINK_ONLY, notes: 'Cambridge scholarly chapter used as a linked historical source; no chapter text, tables, or figures are reproduced.' },
    sepFascism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepFeminism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepPopulism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepConfucianism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepLegalism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepMedieval: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    bpbMonarchy: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent conceptual synthesis; no bpb text, images, or graphics are reproduced.' },
    perseeFrenchConstitutionalMonarchy: { ...LINK_ONLY, notes: 'French academic archive used as a linked historical source; no article text, scans, or translations are reproduced.' },
    oxfordConstitutionalMonarchy: { ...LINK_ONLY, notes: 'Oxford Academic article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    oxfordMonarchyConstitution: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    ukParliamentCrown: { ...OFFICIAL_TEXT, notes: 'UK Parliament information used for independent summary of the contemporary Crown–Parliament relationship; no parliamentary text, images, or graphics are reproduced.' },
    journalDemocraticMonarchies: { ...LINK_ONLY, notes: 'Journal of Democracy article used as a linked comparative source; no article text, tables, or figures are reproduced.' },
    torontoConstitutionalTheocracy: { ...LINK_ONLY, notes: 'University of Toronto faculty publication page used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    oxfordStateReligionFreedom: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordIranTheocraticCriminalLaw: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    iconStateReligionTheocracy: { ...LINK_ONLY, notes: 'International Journal of Constitutional Law article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    cambridgeMaimonidesTheocracy: { ...LINK_ONLY, notes: 'Cambridge scholarly element used as a linked historical and philosophical source; no chapter text, tables, or figures are reproduced.' },
    perseusJosephusTheocracy: { ...PUBLIC_DOMAIN_CANDIDATE, notes: 'Perseus hosts a historical translation of an ancient work; the specific translation and edition should be verified before commercial quotation.' },
    waqfeyaMawardiOrdinances: { ...LINK_ONLY, notes: 'Arabic digital-library record used as a link to a classical public-law work; no collection or translated book text is reproduced.' },
    nsarchiveKhomeini1979: { ...PERMISSION_SENSITIVE, notes: 'National Security Archive document record used for bounded historical context; no archive text, scans, or media are reproduced.' },
    constituteIran1989: { ...LINK_ONLY, notes: 'Constitute Project hosts a linked constitutional text; no constitutional text, tables, or annotations are reproduced.' },
    vaticanStateBodies: { ...OFFICIAL_TEXT, notes: 'Vatican City official government information used for independent institutional summary; no official text, images, or graphics are reproduced.' },
    ushmmFascism: { ...PERMISSION_SENSITIVE, notes: 'Institutional educational source used for historical context; reproduce no USHMM text, images, or graphics.' },
    ushmmCommunism: { ...PERMISSION_SENSITIVE, notes: 'Institutional educational source used for bounded historical context; reproduce no USHMM text, images, or graphics.' },
    bpbFascism: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical synthesis; no bpb text, images, or graphics are reproduced.' },
    bpbNationalSocialism: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical synthesis; no bpb text, images, or graphics are reproduced.' },
    ushmmNurembergLaws: { ...PERMISSION_SENSITIVE, notes: 'United States Holocaust Memorial Museum historical source used for bounded documentation; no institutional text, documents, images, or graphics are reproduced.' },
    ohchrMinorityRights: { ...OFFICIAL_TEXT, notes: 'United Nations human-rights guidance used for independent synthesis; no OHCHR text, tables, or graphics are reproduced.' },
    panAfricanism: { ...LINK_ONLY, notes: 'Scholarly article used as a linked source; no article text, figures, or tables are reproduced.' },
    sepMarx: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    oxfordHistoryCommunism: { ...LINK_ONLY, notes: 'Oxford Academic volume used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordAuthoritarianConsolidation: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked comparative scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordCommunismEasternEurope: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordWorkersCommunism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordContemporarySocialistLaw: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked comparative scholarly source; no book text, tables, or figures are reproduced.' },
    cambridgeCommunistIdeologyAdaptation: { ...LINK_ONLY, notes: 'Cambridge scholarly article used as a linked comparative source; no article text, tables, or figures are reproduced.' },
    ghdiMarxLeninism: { ...LINK_ONLY, notes: 'German historical document repository used for independent synthesis; no document text, scans, or translation are reproduced.' },
    aeaChinaSocialism: { ...LINK_ONLY, notes: 'Journal article used as a linked economic analysis; no article text, figures, or tables are reproduced.' },
    sepReligionPolitics: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    oxfordChristianDemocracy: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordChristianDemocracyEurope: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked comparative source; no chapter text, tables, or figures are reproduced.' },
    cambridgeChristianDemocracy: { ...LINK_ONLY, notes: 'Cambridge scholarly chapter record used as a linked historical source; no chapter text, tables, or figures are reproduced.' },
    oxfordSocialCatholicismChristianDemocracy: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked intellectual-history source; no chapter text, tables, or figures are reproduced.' },
    oxfordChristianDemocratDecade: { ...LINK_ONLY, notes: 'Oxford Academic book chapter used as a linked historical source; no chapter text, tables, or figures are reproduced.' },
    vaticanRerumNovarum: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted primary social encyclical used for independent synthesis; no encyclical text or translation is reproduced.' },
    vaticanQuadragesimoAnno: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted primary social encyclical used for independent synthesis; no encyclical text or translation is reproduced.' },
    vaticanSocialDoctrineCompendium: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted institutional compendium used for independent synthesis of social-doctrine concepts; no text or graphics are reproduced.' },
    oxfordLiberationTheologies: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordChristianSocialism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked historical source; no chapter text, tables, or figures are reproduced.' },
    cambridgeReligionOriginsSocialism: { ...LINK_ONLY, notes: 'Cambridge-hosted scholarly chapter used as a linked source; no chapter text, PDF text, tables, or figures are reproduced.' },
    jstorChristianSocialistRevival: { ...LINK_ONLY, notes: 'JSTOR scholarly book record used as a linked historical source; no book text, scans, or tables are reproduced.' },
    vaticanLiberationInstruction: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted primary doctrinal instruction used for independent synthesis; no text or translation is reproduced.' },
    vaticanChristianFreedomLiberation: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted primary doctrinal instruction used for independent synthesis; no text or translation is reproduced.' },
    celamMedellin: { ...OFFICIAL_TEXT, notes: 'CELAM institutional history used for independent context on Medellín and Latin American episcopal conferences; no CELAM text, scans, or graphics are reproduced.' },
    catholicWorkerMovement: { ...LINK_ONLY, notes: 'Movement-maintained history used as a linked primary/community source; no page text, photographs, or archival material are reproduced.' },
    kingPoorPeoplesCampaign: { ...LINK_ONLY, notes: 'Stanford King Institute historical record used as a linked institutional source; no institute text, photographs, or archival material are reproduced.' },
    oxfordLiberationLegacy: { ...LINK_ONLY, notes: 'Oxford institutional research overview used as a linked scholarly source; no PDF text, images, or figures are reproduced.' },
    oxfordPopulismShortIntroduction: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked conceptual source; no book text, tables, or figures are reproduced.' },
    oxfordModernPopulism: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked methodological source; no chapter text, tables, or figures are reproduced.' },
    annualReviewPoliticalTheoryPopulism: { ...LINK_ONLY, notes: 'Annual Review scholarly article used as a linked political-theory source; no article text, tables, or figures are reproduced.' },
    oxfordMullerPopulism: { ...LINK_ONLY, notes: 'Oxford Academic journal article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    cambridgeAnatomyPopulistIdeology: { ...LINK_ONLY, notes: 'Cambridge journal article used as a linked comparative source; no article text, tables, or figures are reproduced.' },
    scieloLatinAmericanPopulism: { ...LINK_ONLY, notes: 'Spanish-language SciELO article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    oxfordLatinAmericaPopulism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked comparative source; no chapter text, tables, or figures are reproduced.' },
    americanYawpOmahaPlatform: { ...LINK_ONLY, notes: 'Educational primary-source reader used as a link to the Omaha Platform; no reader text, scans, or reproduced platform wording is published.' },
    coePopulismDemocracy: { ...OFFICIAL_TEXT, notes: 'Council of Europe institutional report used for independent synthesis of pluralism, rule of law, rights, media, and democratic resilience; no report text or graphics are reproduced.' },
    oxfordPoliticalCentrism: { ...LINK_ONLY, notes: 'Oxford Research Archive thesis record used as a linked scholarly source; no thesis text, tables, or figures are reproduced.' },
    lijphartConsensusDemocracy: { ...LINK_ONLY, notes: 'Wiley scholarly article used as a linked comparative source; no article text, tables, or figures are reproduced.' },
    oxfordThirdWayConversion: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked critical historical source; no chapter text, tables, or figures are reproduced.' },
    wileyThirdWayGiddens: { ...LINK_ONLY, notes: 'Publisher record used as a link to Giddens’s work; no copyrighted book text or figures are reproduced.' },
    sepPragmatism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared; only independent summaries and links are used.' },
    sepDemocracy: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared; only independent summaries and links are used.' },
    oxfordPluralismConsensus: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked political-theory source; no book text, tables, or figures are reproduced.' },
    coeDemocraticGovernance: { ...OFFICIAL_TEXT, notes: 'Council of Europe institutional framework used for independent synthesis of transparency, accountability, participation, and democratic trust; no institutional text or graphics are reproduced.' },
    euRobertSchuman: { ...OFFICIAL_TEXT, notes: 'European Union historical page used for independent summary of Robert Schuman’s public work; no EU text, images, or graphics are reproduced.' },
    adenauerHouse: { ...LINK_ONLY, notes: 'Institutional foundation and biography page used as a linked source for Konrad Adenauer’s political work; no page text, images, or exhibition material is reproduced.' },
    bpbChristianDemocraticCVP: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical synthesis; no bpb text, images, or graphics are reproduced.' },
    oxfordPortugalPoliticalCatholicism: { ...LINK_ONLY, notes: 'Oxford Academic historical chapter used as a linked source; no chapter text, tables, or figures are reproduced.' },
    comparativeChristianDemocracy: { ...LINK_ONLY, notes: 'Stanford-hosted scholarly working paper used as a linked comparative source; no paper text, tables, or figures are reproduced.' },
    oxfordConstitutionalPatriotism: { ...LINK_ONLY, notes: 'Oxford Academic article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    coeDemocraticCitizenship: { ...OFFICIAL_TEXT, notes: 'Council of Europe charter and educational framework used as an institutional source; no charter text, manuals, or graphics are reproduced.' },
  },
  sourceLinks: {
    smith: { ...LINK_ONLY },
    locke: { ...LINK_ONLY },
    bakunin: { ...LINK_ONLY },
    bernstein: { ...LINK_ONLY },
    ostrom: { ...PERMISSION_SENSITIVE, notes: 'Nobel Prize page used as a link to the lecture; no Nobel Foundation text, PDF, or media is reproduced.' },
    sen: { ...LINK_ONLY },
    fanon: { ...PERMISSION_SENSITIVE, notes: 'Publisher page used as a link; the copyrighted translation and book text are not reproduced.' },
    dubois: { ...LINK_ONLY },
    gandhi: { ...LINK_ONLY },
    marx: { ...LINK_ONLY },
    lenin: { ...LINK_ONLY },
    friedman: { ...LINK_ONLY },
    hayek: { ...LINK_ONLY },
    mill: { ...LINK_ONLY },
    nozik: { ...LINK_ONLY },
    hitler: { ...PERMISSION_SENSITIVE, notes: 'US Holocaust Memorial Museum page used as a link; no institutional text or media is copied.' },
    mussolini: { ...LINK_ONLY },
    burke: { ...LINK_ONLY },
    degaulle: { ...LINK_ONLY },
    palme: { ...LINK_ONLY },
    freedomChina: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomNorthKorea: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomVietnam: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomNetherlands: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomDenmark: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomSwitzerland: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomHungary: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomIndia: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomSouthAfrica: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomNorway: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomSweden: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomItaly: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    renan: { ...LINK_ONLY, notes: 'Biographical reference used for an independent summary of Renan’s account of nationhood; no Britannica text is reproduced.' },
    kant: { ...LINK_ONLY, notes: 'Biographical reference used for an independent summary of Kant’s political thought; no Britannica text is reproduced.' },
    king: { ...LINK_ONLY, notes: 'University archive used as a link to primary and biographical materials; no archive text, images, or media are reproduced.' },
    morgenthau: { ...LINK_ONLY, notes: 'Biographical reference used for an independent summary of classical realism; no Britannica text is reproduced.' },
    holocaust: { ...PERMISSION_SENSITIVE, notes: 'US Holocaust Memorial Museum page used as a link; no institutional text or media is copied.' },
  },
  authorReferences: {
    marxEngelsManifesto: { ...PUBLIC_DOMAIN_CANDIDATE },
    leninStateRevolution: { ...PUBLIC_DOMAIN_CANDIDATE },
    bernsteinEvolutionarySocialism: { ...PUBLIC_DOMAIN_CANDIDATE },
    luxemburgReformRevolution: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific English translation and online transcription must be verified before commercial quotation.' },
    jauresSocialistHistory: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific English translation and online transcription must be verified before commercial quotation.' },
    kropotkinMutualAid: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific English edition and online transcription must be verified before commercial quotation.' },
    kropotkinConquestBread: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific English edition and online transcription must be verified before commercial quotation.' },
    bookchinLibertarianMunicipalism: { ...PERMISSION_SENSITIVE },
    adamSmithWealth: { ...PUBLIC_DOMAIN_CANDIDATE },
    constantLibertyModerns: { ...PUBLIC_DOMAIN_CANDIDATE },
    bagehotEnglishConstitution: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the exact Project Gutenberg edition and transcription should still be verified before commercial quotation.' },
    hayekKnowledge: { ...PERMISSION_SENSITIVE, publicationStatus: 'review-required', notes: 'The work is not treated as public domain; the current short quote is held for exact edition and commercial quotation review.' },
    keynesGeneralTheory: { ...PERMISSION_SENSITIVE },
    nozickASU: { ...PERMISSION_SENSITIVE },
    millOnLiberty: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The underlying work is old, but the exact Gutenberg edition and any transcription/translation status must still be recorded before commercial publication.' },
    wollstonecraftRights: { ...PUBLIC_DOMAIN_CANDIDATE },
    burkeReflections: { ...PUBLIC_DOMAIN_CANDIDATE },
    oakeshottRationalismPolitics: { ...PERMISSION_SENSITIVE, notes: 'The 1962 work and specific edition remain rights-sensitive; the project uses a catalog link and independent paraphrase only.' },
    tocquevilleDemocracy: { ...PUBLIC_DOMAIN_CANDIDATE },
    hobbesLeviathan: { ...PUBLIC_DOMAIN_CANDIDATE },
    lockeSecondTreatise: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The underlying work is old, but the exact Gutenberg edition and any transcription/translation status must still be recorded before commercial publication.' },
    federalistPapers: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The essays are historical, but the specific Library of Congress edition, editorial apparatus, and any modern transcription should be verified before commercial quotation.' },
    bakuninStatism: { ...PUBLIC_DOMAIN_CANDIDATE },
    arendtTotalitarianism: { ...PERMISSION_SENSITIVE },
    griffinNatureFascism: { ...PERMISSION_SENSITIVE },
    hitlerMeinKampf: { ...PERMISSION_SENSITIVE, notes: 'Historical work and modern translation/edition rights vary by jurisdiction; the project uses a link only and no quotation is published.' },
    mussoliniDoctrine: { ...PERMISSION_SENSITIVE, publicationStatus: 'review-required', notes: 'The current direct quote is held for translation, sourcebook, and commercial quotation review.' },
    renanNation: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the current English translation/sourcebook page must be verified before commercial quotation.' },
    andersonImaginedCommunities: { ...PERMISSION_SENSITIVE },
    smithEthnicOrigins: { ...PERMISSION_SENSITIVE, notes: 'The scholarly work and specific edition remain rights-sensitive; the project uses a catalog link and independent paraphrase only.' },
    connorEthnonationalism: { ...PERMISSION_SENSITIVE, notes: 'The scholarly reference entry remains rights-sensitive; the project uses a catalog link and independent paraphrase only.' },
    brubakerEthnicityWithoutGroups: { ...PERMISSION_SENSITIVE, notes: 'The scholarly work and specific edition remain rights-sensitive; the project uses a catalog link and independent paraphrase only.' },
    kantPerpetualPeace: { ...PUBLIC_DOMAIN_CANDIDATE },
    rothbardForNewLiberty: { ...PERMISSION_SENSITIVE, notes: 'The work and specific edition have separate rights questions; the project uses a catalog link and independent paraphrase only.' },
    morgenthauRealism: { ...PERMISSION_SENSITIVE },
    mearsheimerTragedy: { ...PERMISSION_SENSITIVE },
    walzerJustWars: { ...PERMISSION_SENSITIVE },
    clausewitzOnWar: { ...PUBLIC_DOMAIN_CANDIDATE },
    mahanInfluenceSeaPower: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the exact Gutenberg edition and transcription should still be verified before commercial quotation.' },
    hobsonImperialism: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the Marxists Internet Archive transcription and any editorial apparatus should be verified before commercial quotation.' },
    gandhiHindSwaraj: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific Gujarati edition, English translation, and digital transcription must be verified before commercial quotation.' },
    duboisBlackReconstruction: { ...PERMISSION_SENSITIVE, publicationStatus: 'review-required', notes: 'The 1935 work, later editions, and digital transcriptions may have different rights status by jurisdiction; the project uses a link and independent paraphrase only.' },
    fanonWretchedEarth: { ...PERMISSION_SENSITIVE },
    cesaireDiscourseColonialism: { ...PERMISSION_SENSITIVE, notes: 'The French essay and later translations/editions have separate rights questions; the project uses independent paraphrase and a link only.' },
    nabucoAbolitionism: { ...PERMISSION_SENSITIVE, notes: 'The Portuguese-language work and specific Senate or later editions have separate rights questions; the project uses independent paraphrase and a link only.' },
    ostromGoverningCommons: { ...PERMISSION_SENSITIVE },
    senDevelopmentFreedom: { ...PERMISSION_SENSITIVE },
    lockeLetterToleration: { ...PERMISSION_SENSITIVE },
    josephusAgainstApion: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The ancient work may be public domain, but the specific Perseus translation and edition must be verified before commercial quotation.' },
    mawardiOrdinances: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The classical Arabic work may be public domain, but the specific modern translation and National Library of Israel edition record must be verified before commercial quotation.' },
    khomeiniIslamicRepublic: { ...PERMISSION_SENSITIVE, notes: 'The modern speech and archive record remain rights-sensitive; the project uses independent paraphrase and a link only.' },
    aquinasMoralPolitical: { ...PERMISSION_SENSITIVE },
    spinozaPolitical: { ...PERMISSION_SENSITIVE },
    maritainIntegralHumanism: { ...PERMISSION_SENSITIVE, notes: 'Publisher/catalog record used as a link to Maritain’s work; no copyrighted book text or translation is reproduced.' },
    gutierrezTheologyLiberation: { ...PERMISSION_SENSITIVE, notes: 'Publisher record used as a link to Gutiérrez’s work; no copyrighted book text or translation is reproduced.' },
    dorothyDayCatholicWorker: { ...LINK_ONLY, notes: 'Movement-maintained historical record used as a link to Dorothy Day’s tradition; no copyrighted writings or archival material are reproduced.' },
    kingPoorPeoplesCampaign: { ...LINK_ONLY, notes: 'Stanford King Institute record used as a link to a historical movement programme; no copyrighted text or archival material is reproduced.' },
    muddeKaltwasserPopulism: { ...PERMISSION_SENSITIVE, notes: 'Publisher/catalog record used as a link to a scholarly book; no copyrighted book text or figures are reproduced.' },
    mullerWhatIsPopulism: { ...PERMISSION_SENSITIVE, notes: 'Publisher record used as a link to a scholarly book; no copyrighted book text or figures are reproduced.' },
    laclauOnPopulistReason: { ...PERMISSION_SENSITIVE, notes: 'Publisher record used as a link to a scholarly book; no copyrighted book text or figures are reproduced.' },
    lijphartPatternsDemocracy: { ...PERMISSION_SENSITIVE, notes: 'Scholarly book record used as a link to comparative research; no copyrighted book text, tables, or figures are reproduced.' },
    giddensThirdWay: { ...PERMISSION_SENSITIVE, notes: 'Publisher record used as a link to Giddens’s work; no copyrighted book text or figures are reproduced.' },
  },
};

export { RIGHTS_RECORDS };
