import { RESEARCH_WORKS } from './research.js';

const REVIEWED_AT = '2026-09-12';
const RESEARCH_WORKS_REVIEWED_AT = '2026-09-13';

function record(rightsStatus, license, commercialUse, publicationStatus, action, notes) {
  return {
    reviewedAt: REVIEWED_AT,
    rightsStatus,
    license,
    commercialUse,
    publicationStatus,
    action,
    notes,
  };
}

const LINK_ONLY = record(
  'copyrighted / link-only',
  'No reuse licence identified for the referenced page or publication.',
  'Original summaries and links only; no copied text, tables, screenshots, or media cleared.',
  'link-only',
  'Use as a source for independent analysis and link to the original. Do not reproduce the source content.',
  'Citation is not a licence to republish the work.',
);

const PUBLIC_DOMAIN_CANDIDATE = record(
  'public-domain candidate',
  'Underlying historical work may be public domain; the specific edition or translation is not automatically cleared.',
  'Verify the exact edition, translation, jurisdiction, and moral-rights position before commercial quotation or redistribution.',
  'review-required',
  'Use a stable bibliographic link and an original paraphrase. Quote only after the edition/translation review is recorded.',
  'Public-domain status belongs to a work and edition in a jurisdiction, not automatically to every online transcription or translation.',
);

const PERMISSION_SENSITIVE = record(
  'permission-sensitive',
  'Copyrighted or rights status not cleared for reproduction.',
  'No commercial reproduction, translation, adaptation, or redistribution cleared.',
  'link-only',
  'Link and paraphrase independently. Obtain permission or qualified legal review before reproducing expressive text or media.',
  'A short quote may still require a case-specific exception analysis.',
);

const RESTRICTED_DATA = record(
  'restricted-data',
  'Terms of use restrict redistribution and/or commercial use.',
  'Do not publish the original dataset, bulk extracts, or a mirror from this repository without written permission.',
  'link-only',
  'Use only permitted citations and derived summaries. Preserve the provider’s terms, provenance, and version information.',
  'Derived facts and independently authored descriptions require their own provenance record.',
);

const OPEN_LICENSE = record(
  'open-license',
  'Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).',
  'Commercial use is allowed when attribution and ShareAlike obligations are followed.',
  'allowed-with-attribution',
  'If data or adapted data is distributed, include the required attribution, licence link, version, and indication of changes.',
  'This status applies to the V-Dem dataset terms, not automatically to every page, graphic, or third-party source linked from V-Dem.',
);

const OFFICIAL_TEXT = record(
  'official or institutional text / jurisdiction-dependent',
  'The official text is publicly accessible, but no blanket commercial-reuse licence is recorded for this project.',
  'Publish an independent summary and link to the official text. Do not assume that public access clears reproduction, translation, or derivative publication.',
  'link-only',
  'Link to the official repository and paraphrase independently. Verify the issuing institution’s terms before reproducing text, translations, or facsimiles.',
  'Legal and international instruments may have special publication rules, but the exact repository and jurisdiction still control reuse.',
);

const COMMUNITY_CONTROLLED = record(
  'community-controlled / permission-sensitive',
  'No blanket commercial-reuse licence identified for the oral tradition, community-held knowledge, or modern transcription/translation.',
  'Do not commercially reproduce, adapt, or package the tradition, performance, translation, or transcription without source-owner or community review.',
  'link-only',
  'Use contextual description and a stable link only. Preserve community attribution and distinguish living oral transmission from a later written edition.',
  'A public archive or UNESCO listing documents access or recognition; it does not automatically grant commercial rights to every version or translation.',
);

const PUBLIC_DOMAIN_CANDIDATE_WORK_IDS = new Set([
  'plato-republic',
  'aristotle-politics',
  'confucius-analects',
  'kautilya-arthashastra',
  'ptahhotep-instruction',
  'hammurabi-code',
  'thucydides-peloponnesian-war',
  'polybius-histories',
  'cicero-de-republica',
  'augustine-city-of-god',
  'justinian-corpus-juris-civilis',
  'aquinas-de-regno',
  'magna-carta-1215',
  'constitution-medina',
  'laozi-dao-de-jing',
  'sunzi-art-of-war',
  'mencius',
  'xunzi',
  'mozi',
  'han-feizi',
  'book-lord-shang',
  'ashoka-edicts',
  'manusmriti',
  'tirukkural',
  'agganna-sutta',
  'al-farabi-virtuous-city',
  'al-mawardi-ordinances',
  'nizam-siyasatnama',
  'ibn-khaldun-muqaddimah',
  'machiavelli-prince',
  'machiavelli-discourses',
  'grotius-rights-war-peace',
  'hobbes-leviathan',
  'locke-second-treatise',
  'rousseau-social-contract',
  'montesquieu-spirit-laws',
  'wollstonecraft-vindication',
  'federalist-papers',
  'tocqueville-democracy-america',
  'mill-on-liberty',
  'marx-engels-communist-manifesto',
  'maimonides-mishneh-torah',
  'rizal-philippines-century',
]);

const OFFICIAL_TEXT_WORK_IDS = new Set([
  'constitution-united-states',
  'constitution-india',
  'constitution-south-africa',
  'universal-declaration-human-rights',
  'treaty-waitangi',
]);

const COMMUNITY_CONTROLLED_WORK_IDS = new Set([
  'great-law-peace',
  'manden-charter',
  'sunjata-epic',
  'florentine-codex',
]);

function researchWorkRights(work) {
  const base = OFFICIAL_TEXT_WORK_IDS.has(work.id)
    ? OFFICIAL_TEXT
    : COMMUNITY_CONTROLLED_WORK_IDS.has(work.id)
      ? COMMUNITY_CONTROLLED
      : PUBLIC_DOMAIN_CANDIDATE_WORK_IDS.has(work.id)
        ? PUBLIC_DOMAIN_CANDIDATE
        : PERMISSION_SENSITIVE;

  const focus = work.originalLanguage.includes('translated') || work.originalLanguage.includes('translations')
    ? 'Translation and edition review is mandatory because the inventory includes later translations.'
    : work.sourceType.includes('manuscript')
      ? 'Archive, manuscript-image, and transcription rights must be checked separately.'
      : work.sourceType.includes('inscription') || work.sourceType.includes('legal')
        ? 'Check the exact inscription, official repository, transcription, and jurisdiction before quoting.'
        : 'Check the exact edition, transcription, translation, and repository terms before quoting.';

  return {
    ...base,
    reviewedAt: RESEARCH_WORKS_REVIEWED_AT,
    notes: `${base.notes} ${focus} Inventory record: ${work.title} (${work.originalLanguage}).`,
  };
}

const RESEARCH_WORK_RIGHTS = Object.fromEntries(
  RESEARCH_WORKS.map((work) => [work.id, researchWorkRights(work)]),
);

const RIGHTS_RECORDS = {
  researchWorks: RESEARCH_WORK_RIGHTS,
  researchSources: {
    ghdiGodesbergGerman: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'GHDI credits the German source edition to Hoffmann und Campe, copyright 1973; no republication clearance inferred.', notes: 'Independent English paraphrase and link only; no German passage, translation, scan, or modern introduction reproduced.' },
    lompeGodesberg1979: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original attributed summary of selected sections only. No article passage, embedded historical quotation, footnote extract, or translated quotation republished.' },
    algeriaSenatusConsulte1865: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Independent summary and link only; no historical provision, modern transcription, facsimile, or translation reproduced. Document age does not clear every modern edition component.' },
    algeriaCremieuxDecrees1870: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original paraphrase of selected decrees and source link only. No legal passage, editorial introduction, or document image republished.' },
    immigrationMuseumColonialStatus: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Independent synthesis and link only. No museum prose, artwork, photograph, caption, or exhibition asset reproduced.' },
    direcheStoraExhibition2022: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Attributed original paraphrase and link only. No interview passage, translated quotation, catalogue page, or photograph reproduced; hosting does not grant republication permission.' },
    brazilCouncilDecree1847: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original paraphrase and official link only. No decree passage, facsimile, or translation reproduced; historical-text age is not blanket clearance for modern assets.' },
    ferrazImperialCabinets2017: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'The publisher landing page states CC BY 4.0 for journal content. This pass remains independent-summary-and-link only.', notes: 'No article passage, embedded historical quotation, figure, table, or PDF republished. Selected arguments are attributed and English wording is original synthesis.' },
    cdecAntisemiticDecrees1938: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Independent summary and link only; no legal passage, editorial text, translation, or document image reproduced. Historical legislation does not clear every modern collection component.' },
    anselmiPropertyReport2001: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original attributed paraphrase and link only; no report passage, archival quotation, table, or facsimile republished.' },
    ushmmItalyPersecution: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original synthesis and link only; no museum text, testimony, photograph, or map reproduced.' },
    friedmanEducation1955: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'The reprint credits copyright to the Trustees of Rutgers College (1955) and states Rutgers University Press granted reprint permission. That is not permission granted to this project.', notes: 'Original critical paraphrase and source link only. No essay passage, footnote quotation, page image, or PDF redistributed.' },
    cowenPublicGoods: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'Econlib displays an all-rights-reserved notice.', notes: 'Original attributed summary and link only. No article passage, examples table, embedded quotation, or further-reading extract reproduced.' },
    whakaputangaTexts1835: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'NZHistory displays CC BY-NC 3.0 New Zealand for text, with separate conditions for non-text material. No commercial republication clearance inferred for the modern translation.', notes: 'Original synthesis and link only. No Māori transcription, Hēnare translation, Busby text, archival image, or facsimile reproduced; public access does not establish community endorsement.' },
    dpmcTreatyTextsKawharu: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Summary and official link only. No treaty passage, modern translation, explanatory note, or document image republished; government hosting does not clear every component for reuse.' },
    teRakiStageOne2014Release: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Attributed independent summary of the release only. No report excerpt, institutional quotation, Q&A text, or PDF image reproduced; findings are not generalized beyond their stated scope.' },
    keaneWhakaputanga2017: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'Te Ara identifies CC BY-NC 4.0 for text and separate conditions for media; commercial reuse may require permission.', notes: 'Original attributed synthesis and link only. No article passage, embedded quotation, translation, photograph, or cited book extract reproduced.' },
    proudhonFederative1863French: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'Wikisource displays an Attribution-ShareAlike notice with possible additional conditions. The project retains a summary-and-link-only boundary.', notes: 'No treatise passage, Code civil extract, scan, or translation reproduced. Historical-text age does not clear every modern edition and asset.' },
    dejacqueLetter1857French: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'Wikisource displays an Attribution-ShareAlike notice with possible additional conditions; no blanket rights claim is made for the 2012 reprint.', notes: 'Original paraphrase and link only. No letter passage, embedded quotation, reprint page, or translation reproduced; polemical language is contextualized, not adopted.' },
    cagiaoProudhonFederalism2011: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Attributed independent synthesis of selected discussion only. No scholarly passage, embedded quotation, notes, or translated extract reproduced.' },
    msheDejacqueVolume2019: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'The consulted institutional page displays all rights reserved.', notes: 'Bibliographic facts and original contextual summary only. No book cover, synopsis text, introduction, chapter, or review reproduced.' },
    reichConcordat1933German: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original summary and link only. No treaty passage, facsimile, or translated extract reproduced; the historical legal text does not establish reuse rights for every modern edition or asset.' },
    barmenDeclaration1934German: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original paraphrase and link only. No declaration wording, biblical epigraph, translation, modern editorial passage, or photograph reproduced.' },
    piusXiMitBrennender1937: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Selected arguments are critically paraphrased with paragraph locators. No encyclical passage, scriptural quotation, translation, PDF, or image reproduced.' },
    ushmmGermanChurches: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Attributed independent synthesis and link only. No article passage, embedded historical quotation, photograph, or cited book extract reproduced; museum access is not blanket reuse permission.' },
    ferryColonialSpeech1885: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Historical rhetoric is critically paraphrased, not endorsed. No speech passage, modern introduction, translated quotation, portrait, or facsimile reproduced; public access does not clear every edition and asset.' },
    clemenceauColonialReply1885: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original paraphrase and official-page link only. No excerpt text, translation, editorial biography, or illustration republished; the underlying speech and modern presentation have distinct provenance.' },
    assemblyRacismReport2021: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Selected bibliographic and contextual information summarized independently. No report passage, hearing extract, embedded quotation, or PDF image reproduced.' },
    osterhammelImperialism2012: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Independent synthesis and link only. The page identifies fee-bearing graphics and separately credited excerpts; no map, table, photograph, source box, or translated passage is redistributed.' },
    brazilConstitution1824: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original summary and official link only. No historical passage, transcription, facsimile, or modern translation republished; legal-text age does not clear every edition or page asset.' },
    lynchModeratingPower2005: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'Article notice identifies CC BY-NC 4.0; a separate site link points to CC BY 4.0. No commercial republication clearance is inferred from the broader site link.', notes: 'Attributed independent synthesis and link only. No Portuguese passage, embedded Constant quotation, archival extract, translation, or page image reproduced.' },
    galvesCostaProperty2022: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'The article links to Creative Commons Attribution 4.0 International (CC BY 4.0). This project retains its summary-and-link publication boundary.', notes: 'No article passage, embedded third-party quotation, translated extract, table, or image reproduced. The article licence is not treated as clearance for every work it cites.' },
    blairSchroeder1999Excerpt: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original summary and link only. No German declaration, translated passage, editorial introduction, or print facsimile reproduced; accessible excerpt is not full-publication permission.' },
    wiesenthalThirdWay2010: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Attributed independent synthesis of a selected reprint. No essay passage, translation, embedded quotation, or GHDI editorial text reproduced.' },
    swissCollegialConsensus: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original prose and official-page link only. Government authorship does not clear every page asset; no text, photograph, video, or legal extract republished.' },
    gallusJesseThirdWays2002: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Selected conceptual claims summarized independently. No source passage, translation, quotations from cited books, or PDF page images copied.' },
    appOmahaPlatform1892: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Historical primary document linked through a modern university edition. No platform text, facsimile, or editorial apparatus reproduced; the age of the document does not clear every edition for reuse.' },
    priesterPopulismus2012: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Independent attributed English synthesis only. No German passage, translation, embedded political quotation, illustration, or linked source reproduced.' },
    weylandPoliticalStrategy2021: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Abstract-only consultation; publisher marks the article restricted and provides a permissions route. No abstract wording or inaccessible text reproduced.' },
    moffittTormeyPoliticalStyle2014: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Independent short account of the stated methodological proposal and a bibliographic link. No abstract, article text, tables, or figures republished; no full-text access or reuse permission inferred.' },
    dayAimsPurposes1940: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Primary article used for original paraphrases and a bibliographic link. No newspaper passage, embedded quotation, facsimile, or author photograph reproduced.' },
    catholicWorkerAims2019: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Movement self-description is not a blanket republication licence. No statement text, embedded Day/Maurin quotations, liturgical wording, or printable PDF copied.' },
    marquetteMaurinPapers: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Institutional biography and collection description used through independent summary. Finding-aid access does not grant rights to the manuscripts, correspondence, or images listed.' },
    lowyRadicalizedCatholicism1989: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'Publisher landing page says article reproduction requires author consent and journal credit. Permission noted for the 1989 reprint is not permission granted to this project.', notes: 'Original English synthesis and publisher link only. No Portuguese translation, earlier text, embedded quotation, or PDF page image distributed.' },
    cduAhlen1947: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Original summary and archival link only. A publicly accessible party programme is not assumed to have blanket commercial-reuse clearance; no transcription, translation, or facsimile copied.' },
    cduDuesseldorf1949: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'The German short version and its editorial apparatus have separate provenance. No programme text, GHDI translation, introduction, or source image reproduced.' },
    zehenderDuesseldorfHistory: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Modern institutional commentary used through attributed independent synthesis. No source prose, illustrations, or linked photographs republished.' },
    seidelChristianSocialCDU1979: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'Independent paraphrases and bibliography link only. No article passage, embedded historical quotation, page scan, or translated extract reproduced; full-text republication permission not established.' },
    malatestaCommunismIndividualism1926: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'The historical essay’s age does not establish rights in the consulted modern English translation or collection. Original paraphrases and link only; no translated passage or facsimile reproduced.' },
    malatestaOrganization1927: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'Translator and translation rights remain unresolved. HTML markup credit is not translation provenance or a reuse licence; no source text reproduced.' },
    makhnoMalatestaOrganizationExchange: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'Translation credit and original-publication attributions are retained without assuming public-domain status for modern translations. No letter extract, page image, or archival scan reproduced.' },
    turcatoTransnationalAnarchism: { ...LINK_ONLY, reviewedAt: '2026-09-15', license: 'Journal footer identifies CC BY-NC 4.0; the article separately records permission for this reprint. No commercial republication clearance inferred.', notes: 'Independent synthesis and link only. No article text, quoted correspondence, tables, or illustrations copied; permission given to the journal is not treated as permission granted to this project.' },
    davidFriedmanMachinery2014: { ...LINK_ONLY, reviewedAt: '2026-09-15', license: 'The consulted third-edition copyright page states all rights reserved; free author-hosted access is not a redistribution licence.', notes: 'Original summaries and bibliographic link only. No passage, epigraph, translated extract, page image, or PDF is distributed by this project.' },
    byockFeuding2003: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'University-hosted scholarly copy consulted for original synthesis. No open republication licence identified; no chapter text, saga quotation, figure, map, or page image reproduced.' },
    thingvellirLawCouncil: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'Independent historical summary and institutional link only. No exhibition reconstruction, image, diagram, translation, or copied passage reproduced.' },
    ghdiGdrConstitution1974: { ...OFFICIAL_TEXT, reviewedAt: '2026-09-15', notes: 'Independent paraphrase and source link only. No constitutional passage, GHDI introduction, translation, or facsimile is republished; the historical text does not clear the modern edition.' },
    hugiGdrChurchPolicy: { ...LINK_ONLY, reviewedAt: '2026-09-15', license: 'The text displays CC BY-NC-ND 4.0; this does not clear commercial republication or translated adaptations. Images have separate credits.', notes: 'Original factual synthesis and attribution only, with no quoted or translated passage, image, or page copy. No broader commercial-use clearance is asserted.' },
    bundesarchivJugendweihe: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'Original analysis with attribution to the archive; no photographs, file images, historical quotations, or monograph extracts reproduced. Public archival access is not treated as a blanket reuse licence.' },
    cabralCulturePortuguese: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'No blanket clearance of Cabral’s work, collected edition, transcription, or translations is assumed. Original English paraphrase and source link only; no speech passages reproduced.' },
    gomesWomenLiberation: { ...OPEN_LICENSE, reviewedAt: '2026-09-15', action: 'Link to the publisher and use original analysis. Any republication or adaptation of licensed text must satisfy attribution and ShareAlike; independently check third-party material.', notes: 'The publisher displays CC BY-SA 4.0 for the article. No participant quotation, photograph, PDF page, or translated extract is reproduced in this project.' },
    degrassiCabralSocionatures: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'Only an original paraphrase of the stated research focus and a repository link are used. Abstract availability does not clear reproduction of the abstract or full article.' },
    leoImmortaleDeiFrench: { ...OFFICIAL_TEXT, reviewedAt: '2026-09-15', notes: 'Original paraphrase and link only. The historical date does not clear the French version, transcription, or modern translations for reproduction.' },
    vaticanReligiousFreedomFrench: { ...OFFICIAL_TEXT, reviewedAt: '2026-09-15', notes: 'No conciliar passage, translated extract, facsimile, or media reproduced; public access is not treated as a reuse licence.' },
    portierEpiscopateFreedom: { ...LINK_ONLY, reviewedAt: '2026-09-15', license: 'Publisher website states all rights reserved; free PDF access is not a republication licence.', notes: 'Only original synthesis and a publisher link. No article text, translated quotation, page image, or PDF is bundled.' },
    allegrettiSeringueiros: { ...LINK_ONLY, reviewedAt: '2026-09-15', license: 'Publisher states that volumes 1–52 (2000–2019) did not adopt a Creative Commons licence; its later CC BY policy is not assumed to cover this 2008 article.', notes: 'Original English paraphrase and source link only. No Portuguese passages, translated extracts, tables, or media reproduced.' },
    chicoMendesCreationDecree: { ...OFFICIAL_TEXT, reviewedAt: '2026-09-15', notes: 'Historical Portuguese legal text paraphrased independently. The transcription and issuing date are recorded; current legal validity and present reserve conditions were not audited.' },
    agarwalParticipatoryExclusions: { ...LINK_ONLY, reviewedAt: '2026-09-15', license: '© 2001 Published by Elsevier Science Ltd., as printed in the author-hosted paper.', notes: 'Printed pages 1623–1625 checked visually. No table, page image, quotation, or translated passage is republished; the participation distinction is summarized independently.' },
    communeDeclarationFrench: { ...PUBLIC_DOMAIN_CANDIDATE, reviewedAt: '2026-09-15', notes: 'Historical French declaration consulted in a modern transcription. No facsimile verification or clearance of the edition, commentary, or translations is claimed. Original paraphrase and link only.' },
    rougerieInternationalCommune: { ...LINK_ONLY, reviewedAt: '2026-09-15', license: 'Copyright © Internationaal Instituut voor Sociale Geschiedenis 1972, as recorded by Cambridge.', notes: 'Selected publisher-PDF pages consulted. No article passages, translations, tables, or scans reproduced.' },
    cossartCommuneCommunalism: { ...LINK_ONLY, reviewedAt: '2026-09-15', license: 'Publisher PDF notice: article text CC BY-SA 4.0; other elements reserved unless specified.', commercialUse: 'Only original synthesis and links are published here. Reusing licensed text would require attribution and ShareAlike compliance; no media reuse is cleared.', notes: 'Abstract and opening consulted; later full-text access was unavailable. No quotations, translated extracts, or images reproduced.' },
    assembleeCommuneHistory: { ...OFFICIAL_TEXT, reviewedAt: '2026-09-15', notes: 'Institutional narrative paraphrased independently. Its historical quotations, photographs, and declaration facsimile are not reproduced.' },
    panXu: { ...LINK_ONLY, notes: 'Scholarly article used as a claim-level reference; the article text is not reproduced.' },
    sepSocialism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepLuxemburg: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    luxemburgSpartacusGerman: { ...PUBLIC_DOMAIN_CANDIDATE, reviewedAt: '2026-09-15', notes: 'German historical programme consulted through the foundation’s transcription of Gesammelte Werke 4. Edition and transcription rights are not cleared for reproduction; publish only original paraphrase and a link.' },
    ghdiWeimarGerman: { ...OFFICIAL_TEXT, reviewedAt: '2026-09-15', notes: 'Selected German constitutional articles consulted as primary evidence. GHDI editorial material, document selection, scans, and translations are not reproduced or treated as generally cleared.' },
    kruseGermanRevolution: { ...LINK_ONLY, reviewedAt: '2026-09-15', license: 'CC BY-NC-ND 4.0, as displayed for Wolfgang Kruse’s text on bpb.de.', commercialUse: 'The displayed licence does not permit commercial republication or distribution of adaptations. This project uses independently written historical synthesis and links only.', notes: 'No source text, translated passage, image, or document extract is reproduced. The licence statement applies to the article text; media have separate terms.' },
    jesseKoehlerCouncilDebate: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'German APuZ article used for attributed original synthesis of a historical controversy. No article text, translated extracts, or facsimiles are reproduced.' },
    sepLiberalism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    humboldtLimitsGerman: { ...PUBLIC_DOMAIN_CANDIDATE, reviewedAt: '2026-09-15', notes: 'German primary text read through an independent digital edition of Leitzmann. Only original paraphrase and links are used; the transcription, apparatus, and any translation are not cleared for reproduction.' },
    vallsHumboldtMill: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'Only the publisher-hosted abstract and bibliographic record were consulted. No claim of full-article review; no abstract text or translated passage is reproduced.' },
    euckenFreiburgHistory: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'German institutional account used for attributed synthesis and links. No institutional text, photographs, or translations are reproduced.' },
    freiburgOrdoliberalDebates: { ...LINK_ONLY, reviewedAt: '2026-09-15', notes: 'German university report used for attributed paraphrase. No quotations, photographs, or translated extracts are reproduced.' },
    oxfordLiberalismResearch: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordNationalSocialism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordNaziGermany: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    ushmmNaziRacism: { ...PERMISSION_SENSITIVE, notes: 'United States Holocaust Memorial Museum historical source used for independent educational synthesis; no institutional text, images, or graphics are reproduced.' },
    ushmmThirdReich: { ...PERMISSION_SENSITIVE, notes: 'United States Holocaust Memorial Museum historical source used for independent educational synthesis; no institutional text, images, or graphics are reproduced.' },
    ushmmNaziPartyPlatform: { ...PERMISSION_SENSITIVE, notes: 'United States Holocaust Memorial Museum documentary source used for independent historical synthesis; no institutional text, documents, images, or graphics are reproduced.' },
    unGenocideConvention: { ...OFFICIAL_TEXT, notes: 'United Nations legal-history page used to link and independently summarize the Genocide Convention; no treaty text or facsimile is reproduced.' },
    oxfordImperialism: { ...LINK_ONLY, notes: 'Oxford Bibliographies entry used as a linked scholarly source; no entry text, tables, or figures are reproduced.' },
    oxfordMilitarism: { ...LINK_ONLY, notes: 'Oxford Bibliographies entry used as a linked scholarly source; no entry text, tables, or figures are reproduced.' },
    oxfordPoliticalEconomyMilitarism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordColonialismEmpireSociology: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    cambridgeMilitarismImperialism: { ...LINK_ONLY, notes: 'Cambridge scholarly chapter used as a linked comparative historical source; no chapter text, tables, or figures are reproduced.' },
    unCharterForce: { ...OFFICIAL_TEXT, notes: 'United Nations Security Council page used for independent synthesis of Charter principles; no UN text, graphics, or institutional materials are reproduced.' },
    usStateMahan: { ...OFFICIAL_TEXT, notes: 'U.S. Office of the Historian page used for independent historical synthesis; no institutional text, images, or graphics are reproduced.' },
    sepConstitutionalism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    oxfordConstitutionalJustice: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    oxfordBritishConstitutionalism: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    locFederalistPapers: { ...OFFICIAL_TEXT, notes: 'Library of Congress guide used to locate and contextualize primary documents; no guide text, scans, or facsimiles are reproduced.' },
    unRuleLawHumanRights: { ...OFFICIAL_TEXT, notes: 'United Nations rule-of-law page used for independent synthesis; no UN text, graphics, or institutional materials are reproduced.' },
    echrConvention: { ...OFFICIAL_TEXT, notes: 'European Court of Human Rights treaty page used as a link to the official text and institutional context; no treaty text or facsimile is reproduced.' },
    colonialLiberalismExclusion: { ...LINK_ONLY, notes: 'SAGE scholarly article used as a linked historical source; no article text, tables, or figures are reproduced.' },
    sepLibertarianism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sageWhatIsFrenchLiberalism: { ...LINK_ONLY, notes: 'SAGE scholarly article used as a linked source on French liberalism; no article text, tables, or figures are reproduced.' },
    cambridgeConstitutionalLiberalismFrance: { ...LINK_ONLY, notes: 'Cambridge scholarly chapter used as a linked source on French constitutional liberalism; no chapter text, tables, or figures are reproduced.' },
    economieBastiat: { ...OFFICIAL_TEXT, notes: 'French Ministry of Economy institutional page used for independent historical context; no page text, graphics, or tables are reproduced.' },
    sepMill: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepLibertyPositiveNegative: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepConservatism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    bpbConservatism: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical synthesis; no bpb text, images, or graphics are reproduced.' },
    sepNationalism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    bpbNationalism: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical and conceptual synthesis; no bpb text, images, or graphics are reproduced.' },
    cambridgeKohnDichotomy: { ...LINK_ONLY, notes: 'Cambridge scholarly article used as a linked source; no article text, tables, or figures are reproduced.' },
    sepColonialism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    unIndigenousDeclaration: { ...OFFICIAL_TEXT, notes: 'United Nations digital-library record used for independent synthesis of Indigenous collective rights and self-determination; no UN text, translation, or facsimile is reproduced.' },
    oxfordTribalConstitutions: { ...LINK_ONLY, notes: 'Oxford Handbook chapter used as a linked scholarly legal-history source; no chapter text, tables, or figures are reproduced.' },
    waitangiTribunalTreaty: { ...OFFICIAL_TEXT, notes: 'Waitangi Tribunal institutional source used for independent synthesis of treaty texts and Māori authority; no Tribunal text, translation, or document image is reproduced.' },
    pmcIndigenousDeliberative: { ...LINK_ONLY, notes: 'Peer-reviewed article accessed through PubMed Central and used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    vdem: { ...OPEN_LICENSE },
    wvs: { ...RESTRICTED_DATA, notes: 'WVS documentation states that data access/use is subject to non-redistribution terms and, for some files, non-commercial conditions.' },
    ches: { ...PERMISSION_SENSITIVE, notes: 'The public site provides datasets and codebooks, but this project does not rely on a cleared right to redistribute CHES files.' },
    manifesto: { ...RESTRICTED_DATA, notes: 'Manifesto Project terms prohibit redistribution except when authorized in writing and require provenance and citation.' },
    foreignPolicy: { ...LINK_ONLY, notes: 'Journal article used as a linked scholarly source; no article text, figures, or tables are reproduced.' },
    oecdWelfareModels: { ...LINK_ONLY, notes: 'OECD comparative policy source used for independent synthesis of welfare-regime distinctions; no OECD text, tables, or graphics are reproduced.' },
    ghdiGodesberg: { ...LINK_ONLY, reviewedAt: '2026-09-16', notes: 'English historical programme excerpt used for independent synthesis. No English translation, source-edition passage, GHDI introduction, or scan reproduced; primary evidence status is not a rights clearance.' },
    fesHistorySocialDemocracy: { ...LINK_ONLY, notes: 'Friedrich-Ebert-Stiftung German-language institutional history used as a linked source; no PDF text, images, or graphics are reproduced.' },
    bpbSpdProgrammatics: { ...LINK_ONLY, reviewedAt: '2026-09-16', license: 'The page credits Frank Decker and states CC BY-NC-ND 4.0; commercial republication or adapted-text clearance is not inferred.', notes: 'Independent summary and link only; no article text, translated passage, images, or graphics reproduced.' },
    bpbGermanSocialState: { ...LINK_ONLY, notes: 'German federal civic-education reference used for independent synthesis of social-state history; no bpb text, images, or graphics are reproduced.' },
    bpbWelfareModels: { ...LINK_ONLY, notes: 'German federal civic-education reference used for independent comparative synthesis; no bpb text, tables, or graphics are reproduced.' },
    bpbSocialMarketEconomy: { ...LINK_ONLY, notes: 'German federal civic-education history used for independent synthesis of the social-market economy; no bpb text, tables, or graphics are reproduced.' },
    jauresArchive: { ...LINK_ONLY, notes: 'Primary-source archive used as a linked historical source; no translated text or archive material is reproduced.' },
    openTextbook: { ...RESTRICTED_DATA, license: 'CC BY-NC 4.0 (as listed by Open Textbook Library).', commercialUse: 'Non-commercial reuse only under the licence; commercial reproduction or adaptation is not cleared.', notes: 'Use the textbook for research and link-level citation. Do not copy its chapters, tables, or wording into an ad-supported product without permission.' },
    sepAnarchism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    cambridgeAnarchismBolshevism: { ...LINK_ONLY, notes: 'Cambridge scholarly article used as a linked historical source; no article text, tables, or figures are reproduced.' },
    iloCooperatives: { ...OFFICIAL_TEXT, notes: 'International Labour Organization page used for independent synthesis of cooperative principles; no ILO text, graphics, or institutional materials are reproduced.' },
    iloWorkerCooperatives: { ...OFFICIAL_TEXT, notes: 'International Labour Organization resource used for independent synthesis; no ILO text, graphics, or institutional materials are reproduced.' },
    sepEnvironmentalEthics: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepClimateJustice: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    ipccAr6Synthesis: { ...LINK_ONLY, notes: 'IPCC assessment used for independently authored summaries of climate risk and policy context; no IPCC text, figures, or graphics are reproduced.' },
    socialEcologyMunicipalism: { ...LINK_ONLY, notes: 'Institute for Social Ecology page used for independent synthesis of Bookchin’s proposal; no page text, graphics, or chapters are reproduced.' },
    makhnoRuralAnarchism: { ...LINK_ONLY, notes: 'Scholarly book record used as a linked historical source; no book text, scans, or tables are reproduced.' },
    cambridgeSpanishAnarchism: { ...LINK_ONLY, notes: 'Cambridge scholarly chapter used as a linked historical source; no chapter text, tables, or figures are reproduced.' },
    sepFascism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    oxfordRepublicanismTransatlantic: { ...LINK_ONLY, notes: 'Oxford Handbook chapter used as a linked comparative source; no chapter text, tables, or figures are reproduced.' },
    perseeRepublicanismLiberalism: { ...LINK_ONLY, notes: 'Persée French-language article used as a linked scholarly source; no article text, scans, or translations are reproduced.' },
    viePubliqueLaiciteStasi: { ...OFFICIAL_TEXT, notes: 'French public institutional report used for independent synthesis of laïcité; no report text, tables, or graphics are reproduced.' },
    cambridgeIndivisibilityFrenchRepublic: { ...LINK_ONLY, notes: 'Cambridge scholarly article used as a linked constitutional source; no article text, tables, or figures are reproduced.' },
    sageFrenchRepublicLiberalFounders: { ...LINK_ONLY, notes: 'SAGE scholarly article used as a linked source on French republican liberalism; no article text, tables, or figures are reproduced.' },
    cairnLesGaullistes: { ...LINK_ONLY, notes: 'Cairn French-language political-history article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    fondationDeGaulleOppositionIVe: { ...OFFICIAL_TEXT, notes: 'Fondation Charles de Gaulle institutional history used for independent synthesis; no page text, images, or archival material are reproduced.' },
    perseeDeGaulleConstitutionalThought: { ...LINK_ONLY, notes: 'Persée French-language scholarly article used as a linked historical source; no article text, scans, or translations are reproduced.' },
    treccaniFascismo: { ...LINK_ONLY, notes: 'Treccani encyclopedia entry used as a linked Italian-language historical source; no entry text, images, or graphics are reproduced.' },
    treccaniCorporativismo: { ...LINK_ONLY, notes: 'Treccani encyclopedia entry used as a linked Italian-language source on corporatism; no entry text, images, or graphics are reproduced.' },
    treccaniLateranPacts: { ...LINK_ONLY, notes: 'Treccani historical dictionary entry used as a linked Italian-language source; no entry text, images, or graphics are reproduced.' },
    cambridgeMussolinisFollies: { ...LINK_ONLY, notes: 'Cambridge scholarly article used as a linked historical source; no article text, tables, or figures are reproduced.' },
    sageColonialDominationItaly: { ...LINK_ONLY, notes: 'SAGE scholarly article used as a linked historical source; no article text, tables, or figures are reproduced.' },
    sepFeminism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepPopulism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepConfucianism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepLegalism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    sepMedieval: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    bpbMonarchy: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent conceptual synthesis; no bpb text, images, or graphics are reproduced.' },
    perseeFrenchConstitutionalMonarchy: { ...LINK_ONLY, notes: 'French academic archive used as a linked historical source; no article text, scans, or translations are reproduced.' },
    oxfordConstitutionalMonarchy: { ...LINK_ONLY, notes: 'Oxford Academic article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    oxfordMonarchyConstitution: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    ukParliamentCrown: { ...OFFICIAL_TEXT, notes: 'UK Parliament information used for independent summary of the contemporary Crown–Parliament relationship; no parliamentary text, images, or graphics are reproduced.' },
    journalDemocraticMonarchies: { ...LINK_ONLY, notes: 'Journal of Democracy article used as a linked comparative source; no article text, tables, or figures are reproduced.' },
    torontoConstitutionalTheocracy: { ...LINK_ONLY, notes: 'University of Toronto faculty publication page used as a linked scholarly source; no book text, tables, or figures are reproduced.' },
    oxfordStateReligionFreedom: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordIranTheocraticCriminalLaw: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    iconStateReligionTheocracy: { ...LINK_ONLY, notes: 'International Journal of Constitutional Law article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    cambridgeMaimonidesTheocracy: { ...LINK_ONLY, notes: 'Cambridge scholarly element used as a linked historical and philosophical source; no chapter text, tables, or figures are reproduced.' },
    perseusJosephusTheocracy: { ...PUBLIC_DOMAIN_CANDIDATE, notes: 'Perseus hosts a historical translation of an ancient work; the specific translation and edition should be verified before commercial quotation.' },
    waqfeyaMawardiOrdinances: { ...LINK_ONLY, notes: 'Arabic digital-library record used as a link to a classical public-law work; no collection or translated book text is reproduced.' },
    nsarchiveKhomeini1979: { ...PERMISSION_SENSITIVE, notes: 'National Security Archive document record used for bounded historical context; no archive text, scans, or media are reproduced.' },
    constituteIran1989: { ...LINK_ONLY, notes: 'Constitute Project hosts a linked constitutional text; no constitutional text, tables, or annotations are reproduced.' },
    vaticanStateBodies: { ...OFFICIAL_TEXT, notes: 'Vatican City official government information used for independent institutional summary; no official text, images, or graphics are reproduced.' },
    ushmmFascism: { ...PERMISSION_SENSITIVE, notes: 'Institutional educational source used for historical context; reproduce no USHMM text, images, or graphics.' },
    ushmmCommunism: { ...PERMISSION_SENSITIVE, notes: 'Institutional educational source used for bounded historical context; reproduce no USHMM text, images, or graphics.' },
    bpbFascism: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical synthesis; no bpb text, images, or graphics are reproduced.' },
    bpbNationalSocialism: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical synthesis; no bpb text, images, or graphics are reproduced.' },
    ushmmNurembergLaws: { ...PERMISSION_SENSITIVE, notes: 'United States Holocaust Memorial Museum historical source used for bounded documentation; no institutional text, documents, images, or graphics are reproduced.' },
    ohchrMinorityRights: { ...OFFICIAL_TEXT, notes: 'United Nations human-rights guidance used for independent synthesis; no OHCHR text, tables, or graphics are reproduced.' },
    panAfricanism: { ...LINK_ONLY, notes: 'Scholarly article used as a linked source; no article text, figures, or tables are reproduced.' },
    sepMarx: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    oxfordHistoryCommunism: { ...LINK_ONLY, notes: 'Oxford Academic volume used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordAuthoritarianConsolidation: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked comparative scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordCommunismEasternEurope: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordWorkersCommunism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordContemporarySocialistLaw: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked comparative scholarly source; no book text, tables, or figures are reproduced.' },
    cambridgeCommunistIdeologyAdaptation: { ...LINK_ONLY, notes: 'Cambridge scholarly article used as a linked comparative source; no article text, tables, or figures are reproduced.' },
    ghdiMarxLeninism: { ...LINK_ONLY, notes: 'German historical document repository used for independent synthesis; no document text, scans, or translation are reproduced.' },
    aeaChinaSocialism: { ...LINK_ONLY, notes: 'Journal article used as a linked economic analysis; no article text, figures, or tables are reproduced.' },
    sepReligionPolitics: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared.' },
    oxfordChristianDemocracy: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordChristianDemocracyEurope: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked comparative source; no chapter text, tables, or figures are reproduced.' },
    cambridgeChristianDemocracy: { ...LINK_ONLY, notes: 'Cambridge scholarly chapter record used as a linked historical source; no chapter text, tables, or figures are reproduced.' },
    oxfordSocialCatholicismChristianDemocracy: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked intellectual-history source; no chapter text, tables, or figures are reproduced.' },
    oxfordChristianDemocratDecade: { ...LINK_ONLY, notes: 'Oxford Academic book chapter used as a linked historical source; no chapter text, tables, or figures are reproduced.' },
    vaticanRerumNovarum: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted primary social encyclical used for independent synthesis; no encyclical text or translation is reproduced.' },
    vaticanQuadragesimoAnno: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted primary social encyclical used for independent synthesis; no encyclical text or translation is reproduced.' },
    vaticanSocialDoctrineCompendium: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted institutional compendium used for independent synthesis of social-doctrine concepts; no text or graphics are reproduced.' },
    oxfordLiberationTheologies: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked scholarly source; no chapter text, tables, or figures are reproduced.' },
    oxfordChristianSocialism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked historical source; no chapter text, tables, or figures are reproduced.' },
    cambridgeReligionOriginsSocialism: { ...LINK_ONLY, notes: 'Cambridge-hosted scholarly chapter used as a linked source; no chapter text, PDF text, tables, or figures are reproduced.' },
    jstorChristianSocialistRevival: { ...LINK_ONLY, notes: 'JSTOR scholarly book record used as a linked historical source; no book text, scans, or tables are reproduced.' },
    vaticanLiberationInstruction: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted primary doctrinal instruction used for independent synthesis; no text or translation is reproduced.' },
    vaticanChristianFreedomLiberation: { ...OFFICIAL_TEXT, notes: 'Vatican-hosted primary doctrinal instruction used for independent synthesis; no text or translation is reproduced.' },
    celamMedellin: { ...OFFICIAL_TEXT, notes: 'CELAM institutional history used for independent context on Medellín and Latin American episcopal conferences; no CELAM text, scans, or graphics are reproduced.' },
    catholicWorkerMovement: { ...LINK_ONLY, notes: 'Movement-maintained history used as a linked primary/community source; no page text, photographs, or archival material are reproduced.' },
    kingPoorPeoplesCampaign: { ...LINK_ONLY, notes: 'Stanford King Institute historical record used as a linked institutional source; no institute text, photographs, or archival material are reproduced.' },
    oxfordLiberationLegacy: { ...LINK_ONLY, notes: 'Oxford institutional research overview used as a linked scholarly source; no PDF text, images, or figures are reproduced.' },
    oxfordPopulismShortIntroduction: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked conceptual source; no book text, tables, or figures are reproduced.' },
    oxfordModernPopulism: { ...LINK_ONLY, notes: 'Oxford Research Encyclopedia chapter used as a linked methodological source; no chapter text, tables, or figures are reproduced.' },
    annualReviewPoliticalTheoryPopulism: { ...LINK_ONLY, notes: 'Annual Review scholarly article used as a linked political-theory source; no article text, tables, or figures are reproduced.' },
    oxfordMullerPopulism: { ...LINK_ONLY, notes: 'Oxford Academic journal article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    cambridgeAnatomyPopulistIdeology: { ...LINK_ONLY, notes: 'Cambridge journal article used as a linked comparative source; no article text, tables, or figures are reproduced.' },
    scieloLatinAmericanPopulism: { ...LINK_ONLY, notes: 'Spanish-language SciELO article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    oxfordLatinAmericaPopulism: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked comparative source; no chapter text, tables, or figures are reproduced.' },
    americanYawpOmahaPlatform: { ...LINK_ONLY, notes: 'Educational primary-source reader used as a link to the Omaha Platform; no reader text, scans, or reproduced platform wording is published.' },
    coePopulismDemocracy: { ...OFFICIAL_TEXT, notes: 'Council of Europe institutional report used for independent synthesis of pluralism, rule of law, rights, media, and democratic resilience; no report text or graphics are reproduced.' },
    oxfordPoliticalCentrism: { ...LINK_ONLY, notes: 'Oxford Research Archive thesis record used as a linked scholarly source; no thesis text, tables, or figures are reproduced.' },
    lijphartConsensusDemocracy: { ...LINK_ONLY, notes: 'Wiley scholarly article used as a linked comparative source; no article text, tables, or figures are reproduced.' },
    oxfordThirdWayConversion: { ...LINK_ONLY, notes: 'Oxford Academic chapter used as a linked critical historical source; no chapter text, tables, or figures are reproduced.' },
    wileyThirdWayGiddens: { ...LINK_ONLY, notes: 'Publisher record used as a link to Giddens’s work; no copyrighted book text or figures are reproduced.' },
    sepPragmatism: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared; only independent summaries and links are used.' },
    sepDemocracy: { ...LINK_ONLY, notes: 'SEP grants limited user rights and states that commercial distribution is not generally cleared; only independent summaries and links are used.' },
    oxfordPluralismConsensus: { ...LINK_ONLY, notes: 'Oxford Academic book record used as a linked political-theory source; no book text, tables, or figures are reproduced.' },
    coeDemocraticGovernance: { ...OFFICIAL_TEXT, notes: 'Council of Europe institutional framework used for independent synthesis of transparency, accountability, participation, and democratic trust; no institutional text or graphics are reproduced.' },
    euRobertSchuman: { ...OFFICIAL_TEXT, notes: 'European Union historical page used for independent summary of Robert Schuman’s public work; no EU text, images, or graphics are reproduced.' },
    adenauerHouse: { ...LINK_ONLY, notes: 'Institutional foundation and biography page used as a linked source for Konrad Adenauer’s political work; no page text, images, or exhibition material is reproduced.' },
    bpbChristianDemocraticCVP: { ...LINK_ONLY, notes: 'German federal civic-education source used for independent historical synthesis; no bpb text, images, or graphics are reproduced.' },
    oxfordPortugalPoliticalCatholicism: { ...LINK_ONLY, notes: 'Oxford Academic historical chapter used as a linked source; no chapter text, tables, or figures are reproduced.' },
    comparativeChristianDemocracy: { ...LINK_ONLY, notes: 'Stanford-hosted scholarly working paper used as a linked comparative source; no paper text, tables, or figures are reproduced.' },
    oxfordConstitutionalPatriotism: { ...LINK_ONLY, notes: 'Oxford Academic article used as a linked scholarly source; no article text, tables, or figures are reproduced.' },
    coeDemocraticCitizenship: { ...OFFICIAL_TEXT, notes: 'Council of Europe charter and educational framework used as an institutional source; no charter text, manuals, or graphics are reproduced.' },
  },
  sourceLinks: {
    smith: { ...LINK_ONLY },
    locke: { ...LINK_ONLY },
    bakunin: { ...LINK_ONLY },
    bernstein: { ...LINK_ONLY },
    ostrom: { ...PERMISSION_SENSITIVE, notes: 'Nobel Prize page used as a link to the lecture; no Nobel Foundation text, PDF, or media is reproduced.' },
    sen: { ...LINK_ONLY },
    fanon: { ...PERMISSION_SENSITIVE, notes: 'Publisher page used as a link; the copyrighted translation and book text are not reproduced.' },
    dubois: { ...LINK_ONLY },
    gandhi: { ...LINK_ONLY },
    marx: { ...LINK_ONLY },
    lenin: { ...LINK_ONLY },
    friedman: { ...LINK_ONLY },
    hayek: { ...LINK_ONLY },
    mill: { ...LINK_ONLY },
    nozik: { ...LINK_ONLY },
    hitler: { ...PERMISSION_SENSITIVE, notes: 'US Holocaust Memorial Museum page used as a link; no institutional text or media is copied.' },
    mussolini: { ...LINK_ONLY },
    fascistItaly: { ...PERMISSION_SENSITIVE, reviewedAt: '2026-09-16', notes: 'USHMM Italy article consulted for institutions, imperial warfare, 1938 legislation, and the 1943 occupation. Shared card and encyclopedia reference: independent summaries and a link only; no institutional text, translations, images, or media reproduced.' },
    burke: { ...LINK_ONLY },
    degaulle: { ...LINK_ONLY },
    palme: { ...LINK_ONLY },
    freedomChina: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomNorthKorea: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomVietnam: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomNetherlands: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomDenmark: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomSwitzerland: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomHungary: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomIndia: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomSouthAfrica: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomNorway: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomSweden: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    freedomItaly: { ...PERMISSION_SENSITIVE, notes: 'Freedom House requires prior approval for commercial use of its content; the app currently links and writes independent summaries only.' },
    renan: { ...LINK_ONLY, notes: 'Biographical reference used for an independent summary of Renan’s account of nationhood; no Britannica text is reproduced.' },
    kant: { ...LINK_ONLY, notes: 'Biographical reference used for an independent summary of Kant’s political thought; no Britannica text is reproduced.' },
    king: { ...LINK_ONLY, notes: 'University archive used as a link to primary and biographical materials; no archive text, images, or media are reproduced.' },
    morgenthau: { ...LINK_ONLY, notes: 'Biographical reference used for an independent summary of classical realism; no Britannica text is reproduced.' },
    holocaust: { ...PERMISSION_SENSITIVE, notes: 'US Holocaust Memorial Museum page used as a link; no institutional text or media is copied.' },
  },
  authorReferences: {
    marxEngelsManifesto: { ...PUBLIC_DOMAIN_CANDIDATE },
    leninStateRevolution: { ...PUBLIC_DOMAIN_CANDIDATE },
    bernsteinEvolutionarySocialism: { ...PUBLIC_DOMAIN_CANDIDATE },
    luxemburgReformRevolution: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific English translation and online transcription must be verified before commercial quotation.' },
    jauresSocialistHistory: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific English translation and online transcription must be verified before commercial quotation.' },
    kropotkinMutualAid: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific English edition and online transcription must be verified before commercial quotation.' },
    kropotkinConquestBread: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific English edition and online transcription must be verified before commercial quotation.' },
    bookchinLibertarianMunicipalism: { ...PERMISSION_SENSITIVE },
    adamSmithWealth: { ...PUBLIC_DOMAIN_CANDIDATE },
    constantLibertyModerns: { ...PUBLIC_DOMAIN_CANDIDATE },
    bagehotEnglishConstitution: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the exact Project Gutenberg edition and transcription should still be verified before commercial quotation.' },
    hayekKnowledge: { ...PERMISSION_SENSITIVE, publicationStatus: 'review-required', notes: 'The work is not treated as public domain; the current short quote is held for exact edition and commercial quotation review.' },
    keynesGeneralTheory: { ...PERMISSION_SENSITIVE },
    nozickASU: { ...PERMISSION_SENSITIVE },
    millOnLiberty: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The underlying work is old, but the exact Gutenberg edition and any transcription/translation status must still be recorded before commercial publication.' },
    wollstonecraftRights: { ...PUBLIC_DOMAIN_CANDIDATE },
    burkeReflections: { ...PUBLIC_DOMAIN_CANDIDATE },
    oakeshottRationalismPolitics: { ...PERMISSION_SENSITIVE, notes: 'The 1962 work and specific edition remain rights-sensitive; the project uses a catalog link and independent paraphrase only.' },
    tocquevilleDemocracy: { ...PUBLIC_DOMAIN_CANDIDATE },
    hobbesLeviathan: { ...PUBLIC_DOMAIN_CANDIDATE },
    lockeSecondTreatise: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The underlying work is old, but the exact Gutenberg edition and any transcription/translation status must still be recorded before commercial publication.' },
    federalistPapers: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The essays are historical, but the specific Library of Congress edition, editorial apparatus, and any modern transcription should be verified before commercial quotation.' },
    bakuninStatism: { ...PUBLIC_DOMAIN_CANDIDATE },
    arendtTotalitarianism: { ...PERMISSION_SENSITIVE },
    griffinNatureFascism: { ...PERMISSION_SENSITIVE },
    hitlerMeinKampf: { ...PERMISSION_SENSITIVE, notes: 'Historical work and modern translation/edition rights vary by jurisdiction; the project uses a link only and no quotation is published.' },
    mussoliniDoctrine: { ...PERMISSION_SENSITIVE, publicationStatus: 'review-required', notes: 'The current direct quote is held for translation, sourcebook, and commercial quotation review.' },
    renanNation: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the current English translation/sourcebook page must be verified before commercial quotation.' },
    andersonImaginedCommunities: { ...PERMISSION_SENSITIVE },
    smithEthnicOrigins: { ...PERMISSION_SENSITIVE, notes: 'The scholarly work and specific edition remain rights-sensitive; the project uses a catalog link and independent paraphrase only.' },
    connorEthnonationalism: { ...PERMISSION_SENSITIVE, notes: 'The scholarly reference entry remains rights-sensitive; the project uses a catalog link and independent paraphrase only.' },
    brubakerEthnicityWithoutGroups: { ...PERMISSION_SENSITIVE, notes: 'The scholarly work and specific edition remain rights-sensitive; the project uses a catalog link and independent paraphrase only.' },
    kantPerpetualPeace: { ...PUBLIC_DOMAIN_CANDIDATE },
    rothbardForNewLiberty: { ...PERMISSION_SENSITIVE, notes: 'The work and specific edition have separate rights questions; the project uses a catalog link and independent paraphrase only.' },
    morgenthauRealism: { ...PERMISSION_SENSITIVE },
    mearsheimerTragedy: { ...PERMISSION_SENSITIVE },
    walzerJustWars: { ...PERMISSION_SENSITIVE },
    clausewitzOnWar: { ...PUBLIC_DOMAIN_CANDIDATE },
    mahanInfluenceSeaPower: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the exact Gutenberg edition and transcription should still be verified before commercial quotation.' },
    hobsonImperialism: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the Marxists Internet Archive transcription and any editorial apparatus should be verified before commercial quotation.' },
    gandhiHindSwaraj: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The historical work may be public domain, but the specific Gujarati edition, English translation, and digital transcription must be verified before commercial quotation.' },
    duboisBlackReconstruction: { ...PERMISSION_SENSITIVE, publicationStatus: 'review-required', notes: 'The 1935 work, later editions, and digital transcriptions may have different rights status by jurisdiction; the project uses a link and independent paraphrase only.' },
    fanonWretchedEarth: { ...PERMISSION_SENSITIVE },
    cesaireDiscourseColonialism: { ...PERMISSION_SENSITIVE, notes: 'The French essay and later translations/editions have separate rights questions; the project uses independent paraphrase and a link only.' },
    nabucoAbolitionism: { ...PERMISSION_SENSITIVE, notes: 'The Portuguese-language work and specific Senate or later editions have separate rights questions; the project uses independent paraphrase and a link only.' },
    ostromGoverningCommons: { ...PERMISSION_SENSITIVE },
    senDevelopmentFreedom: { ...PERMISSION_SENSITIVE },
    lockeLetterToleration: { ...PERMISSION_SENSITIVE },
    josephusAgainstApion: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The ancient work may be public domain, but the specific Perseus translation and edition must be verified before commercial quotation.' },
    mawardiOrdinances: { ...PUBLIC_DOMAIN_CANDIDATE, publicationStatus: 'review-required', notes: 'The classical Arabic work may be public domain, but the specific modern translation and National Library of Israel edition record must be verified before commercial quotation.' },
    khomeiniIslamicRepublic: { ...PERMISSION_SENSITIVE, notes: 'The modern speech and archive record remain rights-sensitive; the project uses independent paraphrase and a link only.' },
    aquinasMoralPolitical: { ...PERMISSION_SENSITIVE },
    spinozaPolitical: { ...PERMISSION_SENSITIVE },
    maritainIntegralHumanism: { ...PERMISSION_SENSITIVE, notes: 'Publisher/catalog record used as a link to Maritain’s work; no copyrighted book text or translation is reproduced.' },
    gutierrezTheologyLiberation: { ...PERMISSION_SENSITIVE, notes: 'Publisher record used as a link to Gutiérrez’s work; no copyrighted book text or translation is reproduced.' },
    dorothyDayCatholicWorker: { ...LINK_ONLY, notes: 'Movement-maintained historical record used as a link to Dorothy Day’s tradition; no copyrighted writings or archival material are reproduced.' },
    kingPoorPeoplesCampaign: { ...LINK_ONLY, notes: 'Stanford King Institute record used as a link to a historical movement programme; no copyrighted text or archival material is reproduced.' },
    muddeKaltwasserPopulism: { ...PERMISSION_SENSITIVE, notes: 'Publisher/catalog record used as a link to a scholarly book; no copyrighted book text or figures are reproduced.' },
    mullerWhatIsPopulism: { ...PERMISSION_SENSITIVE, notes: 'Publisher record used as a link to a scholarly book; no copyrighted book text or figures are reproduced.' },
    laclauOnPopulistReason: { ...PERMISSION_SENSITIVE, notes: 'Publisher record used as a link to a scholarly book; no copyrighted book text or figures are reproduced.' },
    lijphartPatternsDemocracy: { ...PERMISSION_SENSITIVE, notes: 'Scholarly book record used as a link to comparative research; no copyrighted book text, tables, or figures are reproduced.' },
    giddensThirdWay: { ...PERMISSION_SENSITIVE, notes: 'Publisher record used as a link to Giddens’s work; no copyrighted book text or figures are reproduced.' },
  },
};

export { RIGHTS_RECORDS };
