const TAXONOMY_LABELS = [
  {
    id: 'civic-republicanism',
    canonicalName: 'Civic republicanism',
    aliases: ['republican virtue', 'classical republicanism'],
    labelType: 'tradition',
    family: 'Ancient, medieval & classical',
    region: 'Mediterranean / Europe',
    period: 'Classical antiquity → present',
    status: 'revived',
    summary: 'A tradition centered on self-government, civic virtue, public freedom, and resistance to arbitrary domination.',
    differences: 'It overlaps with democracy and liberalism but gives civic participation and freedom from domination a more central role than either label necessarily implies.',
    axisPositions: { economic: 0, social: 10, authority: 25, identity: 15, foreign: -10 },
    sourceIds: ['openTextbook', 'sepMedieval'],
  },
  {
    id: 'monarchism',
    canonicalName: 'Monarchism',
    aliases: ['royalism', 'divine-right monarchy', 'constitutional monarchism'],
    labelType: 'regime type',
    family: 'Ancient, medieval & classical',
    region: 'Global',
    period: 'Ancient → present',
    status: 'active',
    summary: 'Political arrangements that place a monarch at the head of the state, with authority ranging from absolute rule to a largely ceremonial constitutional office.',
    differences: 'Monarchism describes a preferred institution of rule, not one fixed economic, social, or foreign-policy programme.',
    axisPositions: { economic: 5, social: 60, authority: 75, identity: 35, foreign: 25 },
    sourceIds: ['openTextbook', 'vdem'],
  },
  {
    id: 'classical-liberalism',
    canonicalName: 'Classical liberalism',
    aliases: ['economic liberalism', 'laissez-faire liberalism', 'liberal constitutionalism'],
    labelType: 'ideology',
    family: 'Liberal traditions',
    region: 'Europe / North America',
    period: '18th century → present',
    status: 'revived',
    summary: 'A liberal tradition emphasizing individual rights, constitutional limits, private property, voluntary exchange, and restricted government power.',
    differences: 'It is broader than laissez-faire and can support public goods or regulation; libertarianism is a later family with stronger claims about the limits of coercion.',
    axisPositions: { economic: 65, social: -20, authority: -55, identity: -10, foreign: -30 },
    sourceIds: ['openTextbook', 'sepLiberalism', 'ches'],
  },
  {
    id: 'social-liberalism',
    canonicalName: 'Social liberalism',
    aliases: ['modern liberalism', 'welfare liberalism', 'progressive liberalism'],
    labelType: 'ideology',
    family: 'Liberal traditions',
    region: 'Europe / North America',
    period: '19th century → present',
    status: 'active',
    summary: 'Liberal rights and personal autonomy combined with public action to expand equal opportunity and provide social protection.',
    differences: 'It accepts a more active state than classical liberalism while remaining distinct from democratic socialism because private ownership and markets remain central.',
    axisPositions: { economic: -25, social: -60, authority: -35, identity: -30, foreign: 0 },
    sourceIds: ['openTextbook', 'sepLiberalism', 'ches'],
  },
  {
    id: 'conservatism',
    canonicalName: 'Conservatism',
    aliases: ['traditional conservatism', 'Burkean conservatism', 'one-nation conservatism'],
    labelType: 'ideology',
    family: 'Conservative & reactionary traditions',
    region: 'Europe / North America',
    period: '18th century → present',
    status: 'active',
    summary: 'A family that values inherited institutions, continuity, practical judgment, and gradual rather than abstractly engineered change.',
    differences: 'Conservatism is not identical to nationalism, authoritarianism, or laissez-faire economics; conservative traditions differ sharply on each of those questions.',
    axisPositions: { economic: 25, social: 65, authority: 40, identity: 50, foreign: 15 },
    sourceIds: ['openTextbook', 'sepConservatism'],
  },
  {
    id: 'democratic-socialism',
    canonicalName: 'Democratic socialism',
    aliases: ['democratic socialist tradition', 'ethical socialism'],
    labelType: 'ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Americas',
    period: '19th century → present',
    status: 'active',
    summary: 'A socialist tradition seeking substantial economic equality and social ownership through democratic participation and civil liberties.',
    differences: 'It differs from social democracy in the desired long-term role of ownership and markets, and from Marxism-Leninism in its rejection of one-party coercive rule as a necessary route.',
    axisPositions: { economic: -65, social: -45, authority: -20, identity: -25, foreign: -15 },
    sourceIds: ['openTextbook', 'sepSocialism', 'manifesto'],
  },
  {
    id: 'social-democracy',
    canonicalName: 'Social democracy',
    aliases: ['social democratic reformism', 'Nordic social democracy'],
    labelType: 'ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Americas',
    period: 'Late 19th century → present',
    status: 'active',
    summary: 'A reformist tradition using democratic institutions, regulated markets, welfare provision, and collective bargaining to reduce inequality.',
    differences: 'Modern social democracy generally preserves a predominantly private mixed economy, distinguishing it from democratic socialism’s stronger social-ownership ambitions.',
    axisPositions: { economic: -55, social: -45, authority: -20, identity: -20, foreign: -15 },
    sourceIds: ['openTextbook', 'sepSocialism', 'ches'],
  },
  {
    id: 'marxism-leninism',
    canonicalName: 'Marxism–Leninism',
    aliases: ['state communism', 'Leninist communism', 'party-state communism'],
    labelType: 'sub-ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Asia / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A revolutionary communist tradition organized around a vanguard party, a transition led by the state, and collective ownership of major productive assets.',
    differences: 'It should not be used as a synonym for all socialism or communism; council communism, anarcho-communism, and democratic socialism reject important parts of the Leninist model.',
    axisPositions: { economic: -90, social: -10, authority: 85, identity: -15, foreign: 45 },
    sourceIds: ['openTextbook', 'sepSocialism', 'manifesto'],
  },
  {
    id: 'council-communism',
    canonicalName: 'Council communism',
    aliases: ['left communism', 'workers’ council communism'],
    labelType: 'sub-ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Global',
    period: '20th century → present',
    status: 'historical',
    summary: 'A communist current that places workers’ councils and direct workplace democracy above centralized party leadership.',
    differences: 'It shares an anti-capitalist economic goal with Marxism-Leninism but rejects the Leninist party-state as a vehicle for emancipation.',
    axisPositions: { economic: -80, social: -25, authority: -70, identity: -25, foreign: -35 },
    sourceIds: ['sepSocialism', 'manifesto'],
  },
  {
    id: 'anarcho-communism',
    canonicalName: 'Anarcho-communism',
    aliases: ['libertarian communism', 'anarchist communism'],
    labelType: 'sub-ideology',
    family: 'Anarchist traditions',
    region: 'Europe / Americas / Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A stateless communist tradition favoring common ownership, voluntary association, and decentralized self-management.',
    differences: 'Unlike Marxism-Leninism, it treats a centralized transitional state as incompatible with its goal; unlike anarcho-capitalism, it rejects private ownership of productive resources.',
    axisPositions: { economic: -85, social: -55, authority: -90, identity: -45, foreign: -50 },
    sourceIds: ['sepSocialism', 'sepAnarchism'],
  },
  {
    id: 'mutualism',
    canonicalName: 'Mutualism',
    aliases: ['Proudhonian mutualism', 'mutualist anarchism'],
    labelType: 'sub-ideology',
    family: 'Anarchist traditions',
    region: 'Europe / Americas',
    period: '19th century → present',
    status: 'revived',
    summary: 'An anti-authoritarian tradition centered on reciprocal exchange, federated association, and forms of possession distinct from both state ownership and absentee capitalism.',
    differences: 'It occupies a different economic position from both anarcho-communism and anarcho-capitalism, despite sharing a strong suspicion of centralized state power.',
    axisPositions: { economic: 0, social: -25, authority: -65, identity: -30, foreign: -45 },
    sourceIds: ['sepAnarchism', 'sepLibertarianism'],
  },
  {
    id: 'anarcho-capitalism',
    canonicalName: 'Anarcho-capitalism',
    aliases: ['market anarchism', 'libertarian anarchism'],
    labelType: 'sub-ideology',
    family: 'Liberal traditions',
    region: 'North America / Europe',
    period: '20th century → present',
    status: 'active',
    summary: 'A radical market-libertarian position that seeks to replace the state with voluntary, contractual, and privately provided institutions.',
    differences: 'It shares anti-state commitments with anarchist traditions but rejects their common-ownership or anti-capitalist economics; it is not equivalent to every free-market or libertarian view.',
    axisPositions: { economic: 95, social: -35, authority: -95, identity: -35, foreign: -65 },
    sourceIds: ['sepAnarchism', 'sepLibertarianism'],
  },
  {
    id: 'fascism',
    canonicalName: 'Fascism',
    aliases: ['Italian Fascism', 'fascist corporatism'],
    labelType: 'ideology',
    family: 'Fascist & ultranationalist traditions',
    region: 'Europe / Global',
    period: '20th century → present',
    status: 'historical',
    summary: 'An ultranationalist and authoritarian family emphasizing organic national unity, hierarchy, political mobilization, and subordinated individual rights.',
    differences: 'Fascism can use private property or corporatist institutions, so it should not be reduced to either socialism or a simple free-market position.',
    axisPositions: { economic: -15, social: 85, authority: 95, identity: 95, foreign: 90 },
    sourceIds: ['openTextbook', 'sepFascism'],
    warning: 'Historical-analytical entry; inclusion does not imply endorsement.',
  },
  {
    id: 'national-socialism',
    canonicalName: 'National Socialism',
    aliases: ['Nazism', 'Nazi ideology'],
    labelType: 'ideology',
    family: 'Fascist & ultranationalist traditions',
    region: 'Germany / Europe',
    period: '1920s–1945',
    status: 'historical',
    summary: 'The racial-totalitarian ideology of the Nazi movement, combining extreme ethnic hierarchy, dictatorship, mass mobilization, and expansionist war.',
    differences: 'The word “socialism” in the name does not make Nazism part of the socialist tradition; its racial hierarchy and totalizing nationalism are central to its historical meaning.',
    axisPositions: { economic: -20, social: 95, authority: 100, identity: 100, foreign: 100 },
    sourceIds: ['openTextbook', 'sepFascism', 'ushmmFascism'],
    warning: 'Historical-analytical entry concerning a genocidal regime; inclusion does not imply endorsement.',
  },
  {
    id: 'national-conservatism',
    canonicalName: 'National conservatism',
    aliases: ['sovereigntist conservatism', 'conservative nationalism'],
    labelType: 'sub-ideology',
    family: 'Conservative & reactionary traditions',
    region: 'Europe / Americas / Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A conservative family placing sovereignty, cultural continuity, national institutions, and border control at the center of political legitimacy.',
    differences: 'It differs from ethnic nationalism when national membership is civic or institutional, and from fascism when it retains pluralist or constitutional commitments.',
    axisPositions: { economic: 30, social: 70, authority: 50, identity: 85, foreign: 35 },
    sourceIds: ['sepConservatism', 'sepNationalism', 'ches'],
  },
  {
    id: 'civic-nationalism',
    canonicalName: 'Civic nationalism',
    aliases: ['liberal nationalism', 'constitutional patriotism'],
    labelType: 'identity project',
    family: 'Nationalist & identity traditions',
    region: 'Europe / Americas / Global',
    period: '18th century → present',
    status: 'active',
    summary: 'A form of national belonging based primarily on shared citizenship, political principles, and institutions rather than ancestry alone.',
    differences: 'It remains a form of nationalism, even when inclusive; internationalism and civic nationalism can coexist, while ethnic nationalism defines belonging more narrowly.',
    axisPositions: { economic: 0, social: 10, authority: 10, identity: 55, foreign: 10 },
    sourceIds: ['sepNationalism', 'openTextbook'],
  },
  {
    id: 'ethnic-nationalism',
    canonicalName: 'Ethnic nationalism',
    aliases: ['ethnonationalism', 'cultural nationalism'],
    labelType: 'identity project',
    family: 'Nationalist & identity traditions',
    region: 'Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A form of nationalism that defines the nation substantially through ancestry, ethnicity, language, religion, or inherited culture.',
    differences: 'It is not automatically identical to fascism or authoritarianism, but exclusionary variants can overlap with both and should be described with evidence.',
    axisPositions: { economic: 15, social: 60, authority: 45, identity: 95, foreign: 30 },
    sourceIds: ['sepNationalism', 'openTextbook'],
  },
  {
    id: 'anti-colonial-nationalism',
    canonicalName: 'Anti-colonial nationalism',
    aliases: ['national liberation', 'decolonizing nationalism'],
    labelType: 'movement',
    family: 'Nationalist & identity traditions',
    region: 'Africa / Asia / Middle East / Americas',
    period: '19th century → present',
    status: 'active',
    summary: 'National liberation projects seeking self-determination, sovereignty, and the end of foreign rule or colonial domination.',
    differences: 'It describes a political objective and historical situation rather than a single economic or social programme; movements within it can be liberal, socialist, religious, or authoritarian.',
    axisPositions: { economic: -25, social: -10, authority: 15, identity: 75, foreign: -5 },
    sourceIds: ['openTextbook', 'sepNationalism'],
  },
  {
    id: 'pan-africanism',
    canonicalName: 'Pan-Africanism',
    aliases: ['African continental solidarity', 'Black internationalism'],
    labelType: 'movement',
    family: 'Nationalist & identity traditions',
    region: 'Africa / African diaspora',
    period: '19th century → present',
    status: 'active',
    summary: 'A family of movements emphasizing solidarity, liberation, and political cooperation among African peoples and the African diaspora.',
    differences: 'It can combine nationalism with internationalism: the object of solidarity is transnational, so it should not be collapsed into a single nation-state nationalism.',
    axisPositions: { economic: -25, social: -30, authority: 10, identity: 65, foreign: -10 },
    sourceIds: ['openTextbook', 'panAfricanism'],
  },
  {
    id: 'pan-arabism',
    canonicalName: 'Pan-Arabism',
    aliases: ['Arab nationalism', 'Arab unity'],
    labelType: 'identity project',
    family: 'Islamic & Middle Eastern traditions',
    region: 'Middle East / North Africa',
    period: '19th century → present',
    status: 'active',
    summary: 'A transnational identity project seeking political or cultural unity among Arabic-speaking peoples.',
    differences: 'Pan-Arabism is not synonymous with Islamism: it can be secular, socialist, monarchist, or otherwise ideologically varied.',
    axisPositions: { economic: -20, social: 25, authority: 45, identity: 70, foreign: 15 },
    sourceIds: ['openTextbook', 'sepNationalism'],
  },
  {
    id: 'islamism',
    canonicalName: 'Islamism',
    aliases: ['political Islam', 'Islamic political activism'],
    labelType: 'identity project',
    family: 'Islamic & Middle Eastern traditions',
    region: 'Middle East / North Africa / South Asia / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A diverse family of projects that treat Islam as a significant source of political order, law, identity, or public governance.',
    differences: 'Islamism is not identical to Islam, Muslim identity, Salafism, or jihadism; its movements range from electoral reformism to revolutionary and militant currents.',
    axisPositions: { economic: -20, social: 65, authority: 70, identity: 60, foreign: 25 },
    sourceIds: ['openTextbook', 'sepNationalism'],
  },
  {
    id: 'confucian-political-thought',
    canonicalName: 'Confucian political thought',
    aliases: ['Confucianism', 'Confucian statecraft', 'ru tradition'],
    labelType: 'worldview',
    family: 'Chinese political thought',
    region: 'China / East Asia',
    period: 'Ancient → present',
    status: 'revived',
    summary: 'A political tradition emphasizing moral cultivation, social roles, education, ritual order, and government legitimacy through good governance.',
    differences: 'It is a broad ethical and political tradition rather than a modern party ideology, and historical Confucian states varied in institutions and economic policy.',
    axisPositions: { economic: 5, social: 65, authority: 55, identity: 20, foreign: 15 },
    sourceIds: ['openTextbook', 'sepConfucianism'],
  },
  {
    id: 'legalism',
    canonicalName: 'Chinese Legalism',
    aliases: ['fa tradition', 'Fajia'],
    labelType: 'tradition',
    family: 'Chinese political thought',
    region: 'China / East Asia',
    period: 'Warring States → imperial China',
    status: 'historical',
    summary: 'A classical Chinese statecraft tradition emphasizing clear laws, administrative technique, rewards, punishments, and concentrated state capacity.',
    differences: 'Legalism is an analytical tradition of governance, not a direct synonym for modern authoritarianism; its historical concepts do not map neatly onto every contemporary regime.',
    axisPositions: { economic: 15, social: 35, authority: 100, identity: 15, foreign: 40 },
    sourceIds: ['sepLegalism', 'openTextbook'],
  },
  {
    id: 'green-politics',
    canonicalName: 'Green politics',
    aliases: ['ecologism', 'political ecology', 'Green ideology'],
    labelType: 'ideology',
    family: 'Green, feminist & liberation traditions',
    region: 'Europe / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A family prioritizing ecological limits, sustainability, environmental justice, and political participation in response to environmental crises.',
    differences: 'Green politics is internally divided over markets, growth, technology, state authority, and social change; ecology alone does not determine the other four axes.',
    axisPositions: { economic: -20, social: -50, authority: -25, identity: -35, foreign: -25 },
    sourceIds: ['openTextbook', 'ches'],
  },
  {
    id: 'feminism',
    canonicalName: 'Feminism',
    aliases: ['feminist politics', 'women’s liberation'],
    labelType: 'ideology',
    family: 'Green, feminist & liberation traditions',
    region: 'Global',
    period: '18th century → present',
    status: 'active',
    summary: 'A diverse family of theories and movements concerned with gendered power, equality, autonomy, and the transformation of social institutions.',
    differences: 'Liberal, socialist, radical, conservative, Black, Indigenous, Islamic, and intersectional feminisms can disagree substantially about economics, authority, religion, and strategy.',
    axisPositions: { economic: -20, social: -65, authority: -45, identity: -40, foreign: -5 },
    sourceIds: ['openTextbook', 'sepFeminism'],
  },
  {
    id: 'populism',
    canonicalName: 'Populism',
    aliases: ['people-centrism', 'anti-elite politics', 'national populism'],
    labelType: 'analytical category',
    family: 'Populist & leader-centered labels',
    region: 'Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A thin and flexible political style or ideology that frames politics as a struggle between a morally unified people and a corrupt elite.',
    differences: 'Populism is not a complete economic or social programme: left and right populists can occupy opposite positions on markets, identity, and social values.',
    axisPositions: { economic: null, social: null, authority: 35, identity: 50, foreign: null },
    sourceIds: ['openTextbook', 'sepPopulism'],
  },
  {
    id: 'neoliberalism',
    canonicalName: 'Neoliberalism',
    aliases: ['market-oriented reform', 'new liberalism'],
    labelType: 'policy doctrine',
    family: 'Liberal traditions',
    region: 'Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A contested label for policy and intellectual currents favoring competition, market coordination, fiscal restraint, and a reconfigured rather than absent state.',
    differences: 'Its meaning is disputed and varies between self-description and criticism; it should not be treated as a precise synonym for classical liberalism or libertarianism.',
    axisPositions: { economic: 80, social: -20, authority: -15, identity: -15, foreign: 10 },
    sourceIds: ['openTextbook', 'sepLiberalism', 'ches'],
  },
  {
    id: 'ordoliberalism',
    canonicalName: 'Ordoliberalism',
    aliases: ['German liberalism', 'social-market liberalism'],
    labelType: 'policy doctrine',
    family: 'Liberal traditions',
    region: 'Germany / Europe',
    period: '20th century → present',
    status: 'active',
    summary: 'A liberal tradition holding that the state must establish and enforce a competitive order rather than simply withdraw from the economy.',
    differences: 'It is more institutionally interventionist than laissez-faire liberalism while remaining committed to market competition and private ownership.',
    axisPositions: { economic: 55, social: 0, authority: 15, identity: 0, foreign: 5 },
    sourceIds: ['openTextbook', 'sepLiberalism'],
  },
  {
    id: 'gaullism',
    canonicalName: 'Gaullism',
    aliases: ['Gaullist nationalism', 'French grandeur'],
    labelType: 'leader doctrine',
    family: 'Populist & leader-centered labels',
    region: 'France / Europe',
    period: '1940s → present',
    status: 'revived',
    summary: 'A French state-national tradition emphasizing executive authority, national independence, strategic autonomy, and a strong role for the state.',
    differences: 'Gaullism combines elements that do not fit a simple left-right label: social protection, state planning, conservative social currents, and sovereign foreign policy.',
    axisPositions: { economic: 25, social: 35, authority: 65, identity: 85, foreign: 50 },
    sourceIds: ['sepNationalism', 'foreignPolicy'],
  },
  {
    id: 'decolonialism',
    canonicalName: 'Decolonialism',
    aliases: ['decolonial thought', 'coloniality critique'],
    labelType: 'analytical tradition',
    family: 'Green, feminist & liberation traditions',
    region: 'Latin America / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A family of critical approaches examining how colonial power, knowledge hierarchies, race, and global political economy persist after formal empire.',
    differences: 'It is a critical framework rather than one unified governing programme; it can inform anti-colonial, Indigenous, feminist, socialist, and pluralist projects.',
    axisPositions: { economic: -35, social: -35, authority: -30, identity: 35, foreign: -20 },
    sourceIds: ['openTextbook', 'sepNationalism'],
  },
  {
    id: 'aristocracy',
    canonicalName: 'Aristocracy',
    aliases: ['rule of the best', 'nobility rule'],
    labelType: 'regime type',
    family: 'Ancient, medieval & classical',
    region: 'Global',
    period: 'Ancient → present',
    status: 'historical',
    summary: 'A regime form that gives political authority to a hereditary, status-based, or otherwise restricted elite understood as socially superior.',
    differences: 'Aristocracy describes who rules rather than a complete economic or foreign-policy programme; it overlaps with oligarchy but emphasizes rank or nobility more than a small ruling group alone.',
    axisPositions: { economic: 20, social: -35, authority: 65, identity: -5, foreign: -10 },
    sourceIds: ['openTextbook', 'sepMedieval'],
  },
  {
    id: 'democracy',
    canonicalName: 'Democracy',
    aliases: ['popular government', 'rule by the people'],
    labelType: 'regime type',
    family: 'Ancient, medieval & classical',
    region: 'Global',
    period: 'Ancient → present',
    status: 'active',
    summary: 'A family of arrangements in which political authority is answerable to the people through participation, representation, or electoral and deliberative institutions.',
    differences: 'Democracy is primarily an institutional and procedural category, not a fixed economic, social, national-identity, or foreign-policy position; democratic systems can disagree across all four.',
    axisPositions: { economic: null, social: 10, authority: -25, identity: 5, foreign: null },
    sourceIds: ['openTextbook', 'sepMedieval', 'vdem'],
  },
  {
    id: 'oligarchy',
    canonicalName: 'Oligarchy',
    aliases: ['rule by the few', 'elite rule'],
    labelType: 'regime type',
    family: 'Ancient, medieval & classical',
    region: 'Global',
    period: 'Ancient → present',
    status: 'active',
    summary: 'A regime form in which effective political power is concentrated among a small group, whether defined by wealth, lineage, military position, party office, or corporate control.',
    differences: 'Oligarchy identifies concentrated rule by a few and does not by itself determine whether the ruling group is aristocratic, military, party-based, religious, or economic.',
    axisPositions: { economic: 35, social: -20, authority: 75, identity: -5, foreign: null },
    sourceIds: ['openTextbook', 'sepMedieval', 'vdem'],
  },
  {
    id: 'theocracy',
    canonicalName: 'Theocracy',
    aliases: ['clerical rule', 'sacred government'],
    labelType: 'regime type',
    family: 'Ancient, medieval & classical',
    region: 'Global',
    period: 'Ancient → present',
    status: 'active',
    summary: 'A regime form that gives religious authority, sacred law, or religious office a constitutive role in government and political legitimacy.',
    differences: 'Theocracy concerns the source and institutional role of religious authority, not one universal economic or foreign-policy programme; religious regimes vary substantially.',
    axisPositions: { economic: null, social: -75, authority: 80, identity: 30, foreign: null },
    sourceIds: ['openTextbook', 'sepMedieval'],
  },
  {
    id: 'constitutionalism',
    canonicalName: 'Constitutionalism',
    aliases: ['limited government', 'constitutional government'],
    labelType: 'political doctrine',
    family: 'Ancient, medieval & classical',
    region: 'Global',
    period: '17th century → present',
    status: 'active',
    summary: 'A doctrine that public power should be structured, limited, and reviewable through a constitution, rights, procedures, and institutional checks.',
    differences: 'Constitutionalism can coexist with monarchy, democracy, federalism, or different economic systems; having a written constitution alone does not guarantee constitutional government.',
    axisPositions: { economic: null, social: null, authority: -35, identity: null, foreign: null },
    sourceIds: ['openTextbook', 'sepMedieval', 'vdem'],
  },
  {
    id: 'federalism',
    canonicalName: 'Federalism',
    aliases: ['federal government', 'federal union'],
    labelType: 'state structure',
    family: 'Ancient, medieval & classical',
    region: 'Global',
    period: '18th century → present',
    status: 'active',
    summary: 'A state structure that constitutionally distributes authority between a common government and territorially based units.',
    differences: 'Federalism is a division-of-power arrangement rather than a complete ideology; it can be combined with democratic, conservative, socialist, or nationalist projects.',
    axisPositions: { economic: null, social: null, authority: -35, identity: 20, foreign: null },
    sourceIds: ['openTextbook', 'sepMedieval', 'vdem'],
  },
  {
    id: 'confederalism',
    canonicalName: 'Confederalism',
    aliases: ['confederation', 'league of states'],
    labelType: 'state structure',
    family: 'Ancient, medieval & classical',
    region: 'Global',
    period: 'Ancient → present',
    status: 'active',
    summary: 'A union in which constituent polities retain substantial sovereignty and delegate limited powers to common institutions.',
    differences: 'Confederalism generally leaves more authority with members than federalism; neither structure dictates a single social or economic ideology.',
    axisPositions: { economic: null, social: null, authority: -60, identity: 25, foreign: null },
    sourceIds: ['openTextbook', 'sepMedieval'],
  },
  {
    id: 'mercantilism',
    canonicalName: 'Mercantilism',
    aliases: ['commercial system of state power', 'protectionist statecraft'],
    labelType: 'policy doctrine',
    family: 'Ancient, medieval & classical',
    region: 'Europe / Atlantic world',
    period: '16th–18th centuries',
    status: 'historical',
    summary: 'An early-modern policy family linking state power, trade regulation, colonial competition, bullion, protected markets, and strategic commercial capacity.',
    differences: 'Mercantilism is not simply modern protectionism or socialism: it generally operated with private commerce while using strong state direction and imperial competition.',
    axisPositions: { economic: 45, social: -20, authority: 45, identity: -45, foreign: -65 },
    sourceIds: ['openTextbook', 'sepMedieval'],
  },
  {
    id: 'libertarianism',
    canonicalName: 'Libertarianism',
    aliases: ['libertarian political philosophy', 'liberty maximalism'],
    labelType: 'ideology',
    family: 'Liberal traditions',
    region: 'Europe / North America / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A family of views giving strong priority to individual liberty, voluntary association, property or self-ownership, and stringent limits on coercive state power.',
    differences: 'Libertarianism is broader than anarcho-capitalism and includes both minimal-state and more radical anti-state positions; it does not imply one uniform view on culture or foreign policy.',
    axisPositions: { economic: -70, social: 25, authority: -85, identity: 20, foreign: 45 },
    sourceIds: ['sepLibertarianism', 'openTextbook'],
  },
  {
    id: 'minarchism',
    canonicalName: 'Minarchism',
    aliases: ['minimal-state libertarianism', 'night-watchman state'],
    labelType: 'sub-ideology',
    family: 'Liberal traditions',
    region: 'North America / Europe',
    period: '20th century → present',
    status: 'active',
    summary: 'A libertarian position allowing a narrowly limited state for functions such as protection against force, fraud, and external aggression.',
    differences: 'Minarchism accepts a minimal state, unlike anarcho-capitalism, while demanding a much narrower government role than classical liberalism generally requires.',
    axisPositions: { economic: -80, social: 10, authority: -90, identity: 10, foreign: 35 },
    sourceIds: ['sepLibertarianism', 'openTextbook'],
  },
  {
    id: 'philosophical-anarchism',
    canonicalName: 'Philosophical anarchism',
    aliases: ['anarchist political philosophy', 'anti-authoritarian anarchism'],
    labelType: 'tradition',
    family: 'Anarchist traditions',
    region: 'Europe / Americas / Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A family of arguments questioning the moral legitimacy or necessity of political authority without necessarily prescribing one shared revolutionary programme.',
    differences: 'It is a philosophical critique of authority rather than a single economic system; philosophical anarchists may disagree about markets, common ownership, violence, and organization.',
    axisPositions: { economic: null, social: 20, authority: -95, identity: 20, foreign: 30 },
    sourceIds: ['sepAnarchism', 'openTextbook'],
  },
  {
    id: 'individualist-anarchism',
    canonicalName: 'Individualist anarchism',
    aliases: ['egoist anarchism', 'individualist anti-statism'],
    labelType: 'sub-ideology',
    family: 'Anarchist traditions',
    region: 'Europe / Americas',
    period: '19th century → present',
    status: 'revived',
    summary: 'Anarchist currents that make individual autonomy, self-direction, and resistance to imposed authority central to political life.',
    differences: 'Individualist anarchism is not identical to anarcho-capitalism: its currents include anti-capitalist, egoist, mutualist, and market-oriented arguments.',
    axisPositions: { economic: null, social: 25, authority: -90, identity: 20, foreign: 35 },
    sourceIds: ['sepAnarchism', 'sepLibertarianism'],
  },
  {
    id: 'anarcho-syndicalism',
    canonicalName: 'Anarcho-syndicalism',
    aliases: ['revolutionary unionism', 'anarchist syndicalism'],
    labelType: 'sub-ideology',
    family: 'Anarchist traditions',
    region: 'Europe / Americas / Global',
    period: '19th century → present',
    status: 'historical',
    summary: 'A revolutionary anarchist tradition using worker organization, unions, direct action, and self-management as vehicles for replacing capitalist and state hierarchy.',
    differences: 'It shares anti-capitalist economics with communist traditions but rejects centralized party rule and treats worker organization as the primary vehicle of transformation.',
    axisPositions: { economic: 70, social: 30, authority: -80, identity: 25, foreign: 35 },
    sourceIds: ['sepAnarchism', 'sepSocialism'],
  },
  {
    id: 'utopian-socialism',
    canonicalName: 'Utopian socialism',
    aliases: ['early socialism', 'communitarian socialism'],
    labelType: 'tradition',
    family: 'Socialist & communist traditions',
    region: 'Europe / Americas',
    period: 'Early–mid 19th century',
    status: 'historical',
    summary: 'Early socialist projects proposing cooperative, communal, or planned alternatives to competitive capitalism through moral persuasion, association, or model communities.',
    differences: 'The label is often retrospective and polemical; these currents differ from Marxism in method and theory and were not one unified programme.',
    axisPositions: { economic: 60, social: 25, authority: -25, identity: 20, foreign: 20 },
    sourceIds: ['sepSocialism', 'openTextbook'],
  },
  {
    id: 'revolutionary-socialism',
    canonicalName: 'Revolutionary socialism',
    aliases: ['revolutionary Marxism', 'insurrectionary socialism'],
    labelType: 'sub-ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Americas / Global',
    period: '19th century → present',
    status: 'active',
    summary: 'Socialist currents that treat a fundamental break with capitalist property and political institutions as necessary for emancipation.',
    differences: 'Revolutionary socialism includes rival Marxist, councilist, anarchist, and anti-colonial currents; it should not be collapsed into Leninism or one-party rule.',
    axisPositions: { economic: 80, social: 35, authority: 30, identity: 25, foreign: -40 },
    sourceIds: ['sepSocialism', 'manifesto', 'openTextbook'],
  },
  {
    id: 'marxism',
    canonicalName: 'Marxism',
    aliases: ['Marxian socialism', 'historical materialism'],
    labelType: 'ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A family of theories centered on material production, class conflict, capitalist social relations, and the possibility of overcoming class domination.',
    differences: 'Marxism is a broad intellectual and political tradition, not a synonym for Marxism–Leninism; later Marxists disagree about party, democracy, reform, and historical development.',
    axisPositions: { economic: 65, social: 25, authority: 15, identity: 25, foreign: -25 },
    sourceIds: ['sepSocialism', 'manifesto', 'openTextbook'],
  },
  {
    id: 'leninism',
    canonicalName: 'Leninism',
    aliases: ['vanguard-party socialism', 'Bolshevik theory'],
    labelType: 'sub-ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Global',
    period: 'Early 20th century → present',
    status: 'active',
    summary: 'A revolutionary socialist tradition emphasizing a disciplined vanguard party, imperialism, organized seizure of power, and a transitional workers’ state.',
    differences: 'Leninism is a specific revolutionary strategy and party theory rather than all Marxism or socialism; its centralized model differs from council communism and anarchism.',
    axisPositions: { economic: 90, social: 10, authority: 85, identity: 20, foreign: -50 },
    sourceIds: ['sepSocialism', 'manifesto', 'openTextbook'],
  },
  {
    id: 'trotskyism',
    canonicalName: 'Trotskyism',
    aliases: ['permanent revolution', 'Trotskyist Marxism'],
    labelType: 'sub-ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A Marxist tradition associated with permanent revolution, internationalism, opposition to Stalinist bureaucracy, and revolutionary democracy within the workers’ movement.',
    differences: 'It shares a revolutionary and anti-capitalist orientation with Leninism but rejects Stalinist national consolidation and emphasizes international revolutionary continuity.',
    axisPositions: { economic: 90, social: 35, authority: 45, identity: 40, foreign: -60 },
    sourceIds: ['sepSocialism', 'manifesto', 'openTextbook'],
  },
  {
    id: 'maoism',
    canonicalName: 'Maoism',
    aliases: ['Mao Zedong Thought', 'peasant revolutionary communism'],
    labelType: 'leader doctrine',
    family: 'Socialist & communist traditions',
    region: 'China / Asia / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A revolutionary communist doctrine emphasizing protracted mass mobilization, peasant political agency, party leadership, and continuing struggle against entrenched authority.',
    differences: 'Maoism adapts Marxism-Leninism to agrarian and anti-imperial conditions; it is not identical to every Chinese political tradition or to contemporary Chinese state policy.',
    axisPositions: { economic: 90, social: 20, authority: 90, identity: -10, foreign: -45 },
    sourceIds: ['sepSocialism', 'manifesto', 'openTextbook'],
    warning: 'Historical and contemporary variants differ; coordinates are an illustrative family estimate, not a profile of every movement using the label.',
  },
  {
    id: 'stalinism',
    canonicalName: 'Stalinism',
    aliases: ['bureaucratic party-state communism', 'high Stalinism'],
    labelType: 'leader doctrine',
    family: 'Socialist & communist traditions',
    region: 'Soviet Union / Global',
    period: '1920s–present variants',
    status: 'historical',
    summary: 'A contested label for centralized party-state rule, forced economic transformation, bureaucratic hierarchy, repression, and a doctrine of socialism in one country associated with Stalin’s period.',
    differences: 'It should not be used as a synonym for all communism or Marxism–Leninism; the label is historically specific and its extension to later regimes is disputed.',
    axisPositions: { economic: 95, social: -20, authority: 100, identity: -40, foreign: -75 },
    sourceIds: ['sepSocialism', 'openTextbook'],
    warning: 'Historical-analytical entry; avoid treating a contested label as a self-description for every later communist government.',
  },
  {
    id: 'eurocommunism',
    canonicalName: 'Eurocommunism',
    aliases: ['Western European communism', 'democratic communism'],
    labelType: 'sub-ideology',
    family: 'Socialist & communist traditions',
    region: 'Western Europe',
    period: '1960s–1980s, with later influence',
    status: 'historical',
    summary: 'A Western European communist current seeking national political autonomy, democratic legitimacy, civil liberties, and a less Soviet-dependent route to socialism.',
    differences: 'Eurocommunism retains an anti-capitalist orientation but differs from orthodox Marxism–Leninism through pluralism, electoral strategy, and criticism of Soviet-style party-state rule.',
    axisPositions: { economic: 60, social: 40, authority: 10, identity: 25, foreign: 30 },
    sourceIds: ['sepSocialism', 'openTextbook'],
  },
  {
    id: 'syndicalism',
    canonicalName: 'Syndicalism',
    aliases: ['revolutionary syndicalism', 'unionist socialism'],
    labelType: 'ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Americas / Global',
    period: '19th century → present',
    status: 'historical',
    summary: 'A socialist tradition treating organized labor, direct action, strikes, and worker control as central instruments for transforming economic and political life.',
    differences: 'Syndicalism overlaps with anarcho-syndicalism but is broader and can include currents with different views about the state, parties, and revolutionary authority.',
    axisPositions: { economic: 75, social: 30, authority: -55, identity: 25, foreign: 30 },
    sourceIds: ['sepSocialism', 'sepAnarchism', 'openTextbook'],
  },
  {
    id: 'christian-democracy',
    canonicalName: 'Christian democracy',
    aliases: ['Christian social politics', 'Christian democratic tradition'],
    labelType: 'ideology',
    family: 'Conservative & reactionary traditions',
    region: 'Europe / Latin America / Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A political family combining Christian social ethics, constitutional democracy, family and community institutions, social protection, and a mixed economy.',
    differences: 'Christian democracy is not identical to theocracy or social conservatism: many Christian democratic parties accept pluralist institutions, social insurance, and a secular state.',
    axisPositions: { economic: 10, social: -45, authority: 25, identity: 30, foreign: 20 },
    sourceIds: ['openTextbook', 'sepConservatism'],
  },
  {
    id: 'social-conservatism',
    canonicalName: 'Social conservatism',
    aliases: ['cultural conservatism', 'moral conservatism'],
    labelType: 'sub-ideology',
    family: 'Conservative & reactionary traditions',
    region: 'Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A family of views seeking to preserve or restore inherited moral, family, religious, and cultural norms in public and private life.',
    differences: 'Social conservatism is a cultural orientation rather than a complete economic or foreign-policy programme; it can coexist with markets, welfare policies, democracy, or authoritarianism.',
    axisPositions: { economic: null, social: -75, authority: 35, identity: null, foreign: null },
    sourceIds: ['sepConservatism', 'openTextbook'],
  },
  {
    id: 'paleoconservatism',
    canonicalName: 'Paleoconservatism',
    aliases: ['traditionalist American conservatism', 'Old Right conservatism'],
    labelType: 'sub-ideology',
    family: 'Conservative & reactionary traditions',
    region: 'United States',
    period: '20th century → present',
    status: 'active',
    summary: 'An American conservative current emphasizing inherited national culture, restricted immigration, skepticism of centralized power, protectionism or economic nationalism, and restraint abroad.',
    differences: 'It differs from neoconservatism through greater suspicion of interventionist foreign policy and from libertarianism through stronger emphasis on culture, nation, and tradition.',
    axisPositions: { economic: 15, social: -50, authority: 45, identity: -60, foreign: 55 },
    sourceIds: ['sepConservatism', 'sepNationalism', 'foreignPolicy'],
  },
  {
    id: 'neoconservatism',
    canonicalName: 'Neoconservatism',
    aliases: ['neoconservative foreign policy', 'neoconservative tradition'],
    labelType: 'sub-ideology',
    family: 'Conservative & reactionary traditions',
    region: 'United States / Europe',
    period: '20th century → present',
    status: 'active',
    summary: 'A contested conservative current associated with market-oriented economics, concern for social order, assertive national power, and an interventionist approach to foreign policy.',
    differences: 'Neoconservatism differs from paleoconservatism through stronger support for international activism and from classical liberalism through greater emphasis on order, national power, and strategic intervention.',
    axisPositions: { economic: -25, social: -20, authority: 55, identity: -30, foreign: -70 },
    sourceIds: ['sepConservatism', 'foreignPolicy', 'openTextbook'],
  },
  {
    id: 'radical-feminism',
    canonicalName: 'Radical feminism',
    aliases: ['radical feminist politics', 'patriarchy critique'],
    labelType: 'sub-ideology',
    family: 'Green, feminist & liberation traditions',
    region: 'Europe / Americas / Global',
    period: '1960s → present',
    status: 'active',
    summary: 'A feminist current that treats patriarchy and gendered power relations as foundational structures requiring deep social and institutional transformation.',
    differences: 'Radical feminism is distinct from liberal feminism’s emphasis on equal rights within existing institutions, though its internal positions on state power, sexuality, and identity vary.',
    axisPositions: { economic: 35, social: 80, authority: -20, identity: 30, foreign: 25 },
    sourceIds: ['sepFeminism', 'openTextbook'],
  },
  {
    id: 'socialist-feminism',
    canonicalName: 'Socialist feminism',
    aliases: ['Marxist feminism', 'socialist feminist politics'],
    labelType: 'sub-ideology',
    family: 'Green, feminist & liberation traditions',
    region: 'Europe / Americas / Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A feminist tradition connecting gender domination to class relations, labor, social reproduction, property, and the organization of economic life.',
    differences: 'It combines feminist and socialist analysis but is not identical to either all Marxism or all feminism; its strategies range from reform to revolutionary transformation.',
    axisPositions: { economic: 65, social: 75, authority: -25, identity: 35, foreign: 25 },
    sourceIds: ['sepFeminism', 'sepSocialism', 'openTextbook'],
  },
  {
    id: 'intersectional-feminism',
    canonicalName: 'Intersectional feminism',
    aliases: ['intersectional feminist politics', 'intersectionality'],
    labelType: 'analytical tradition',
    family: 'Green, feminist & liberation traditions',
    region: 'Global',
    period: 'Late 20th century → present',
    status: 'active',
    summary: 'A framework examining how gender interacts with race, class, sexuality, disability, coloniality, nationality, and other structures of power.',
    differences: 'Intersectionality is an analytical lens and political approach rather than one uniform programme; it can inform liberal, socialist, abolitionist, Indigenous, and other projects.',
    axisPositions: { economic: 35, social: 85, authority: -35, identity: 50, foreign: 35 },
    sourceIds: ['sepFeminism', 'openTextbook'],
  },
  {
    id: 'deep-ecology',
    canonicalName: 'Deep ecology',
    aliases: ['ecocentric politics', 'ecocentrism'],
    labelType: 'ideology',
    family: 'Green, feminist & liberation traditions',
    region: 'Europe / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'An ecological worldview assigning intrinsic value to nonhuman life and calling for a profound reduction of anthropocentric domination and ecological destruction.',
    differences: 'Deep ecology is more ecocentric than general environmentalism, but it does not by itself determine whether economic change should be socialist, market-based, authoritarian, or decentralized.',
    axisPositions: { economic: 35, social: 25, authority: -30, identity: 20, foreign: 30 },
    sourceIds: ['openTextbook'],
  },
  {
    id: 'degrowth',
    canonicalName: 'Degrowth',
    aliases: ['post-growth politics', 'a-growth debate'],
    labelType: 'policy doctrine',
    family: 'Green, feminist & liberation traditions',
    region: 'Europe / Global',
    period: '21st century',
    status: 'active',
    summary: 'A family of ecological-economic arguments calling for deliberate reduction of resource and energy throughput in affluent economies rather than treating perpetual GDP growth as the primary goal.',
    differences: 'Degrowth is not synonymous with recession or every green policy; its proponents disagree about planning, markets, technology, distribution, and the meaning of prosperity.',
    axisPositions: { economic: 65, social: 35, authority: -15, identity: 35, foreign: 25 },
    sourceIds: ['openTextbook'],
  },
  {
    id: 'nativism',
    canonicalName: 'Nativism',
    aliases: ['anti-immigrant nationalism', 'native-preference politics'],
    labelType: 'identity project',
    family: 'Nationalist & identity traditions',
    region: 'Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A political orientation that gives priority to an established or “native” population over immigrants and perceived outsiders in membership, rights, or public policy.',
    differences: 'Nativism is narrower than nationalism and focuses on insider preference; it can appear in otherwise different economic, religious, or regime projects.',
    axisPositions: { economic: null, social: -35, authority: 45, identity: -90, foreign: -30 },
    sourceIds: ['sepNationalism', 'openTextbook'],
  },
  {
    id: 'sovereigntism',
    canonicalName: 'Sovereigntism',
    aliases: ['sovereignty-first politics', 'sovereigntist politics'],
    labelType: 'identity project',
    family: 'Nationalist & identity traditions',
    region: 'Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A political orientation prioritizing the state’s exclusive authority over territory, law, borders, and collective decisions against external or supranational constraints.',
    differences: 'Sovereigntism can be civic, conservative, left-wing, democratic, or authoritarian; it is not automatically ethnic nationalism or isolationism.',
    axisPositions: { economic: null, social: null, authority: 15, identity: -70, foreign: -30 },
    sourceIds: ['sepNationalism', 'foreignPolicy'],
  },
];

export { TAXONOMY_LABELS };
