const TAXONOMY_LABELS = [
  {
    id: 'civic-republicanism',
    canonicalName: 'Civic republicanism',
    aliases: ['republican virtue', 'classical republicanism'],
    labelType: 'tradition',
    family: 'Ancient, medieval & classical',
    region: 'Mediterranean / Europe',
    period: 'Classical antiquity → present',
    status: 'revived',
    summary: 'A tradition centered on self-government, civic virtue, public freedom, and resistance to arbitrary domination.',
    differences: 'It overlaps with democracy and liberalism but gives civic participation and freedom from domination a more central role than either label necessarily implies.',
    axisPositions: { economic: 0, social: 10, authority: 25, identity: 15, foreign: -10 },
    sourceIds: ['openTextbook', 'sepMedieval'],
  },
  {
    id: 'monarchism',
    canonicalName: 'Monarchism',
    aliases: ['royalism', 'divine-right monarchy', 'constitutional monarchism'],
    labelType: 'regime type',
    family: 'Ancient, medieval & classical',
    region: 'Global',
    period: 'Ancient → present',
    status: 'active',
    summary: 'Political arrangements that place a monarch at the head of the state, with authority ranging from absolute rule to a largely ceremonial constitutional office.',
    differences: 'Monarchism describes a preferred institution of rule, not one fixed economic, social, or foreign-policy programme.',
    axisPositions: { economic: 5, social: 60, authority: 75, identity: 35, foreign: 25 },
    sourceIds: ['openTextbook', 'vdem'],
  },
  {
    id: 'classical-liberalism',
    canonicalName: 'Classical liberalism',
    aliases: ['economic liberalism', 'laissez-faire liberalism', 'liberal constitutionalism'],
    labelType: 'ideology',
    family: 'Liberal traditions',
    region: 'Europe / North America',
    period: '18th century → present',
    status: 'revived',
    summary: 'A liberal tradition emphasizing individual rights, constitutional limits, private property, voluntary exchange, and restricted government power.',
    differences: 'It is broader than laissez-faire and can support public goods or regulation; libertarianism is a later family with stronger claims about the limits of coercion.',
    axisPositions: { economic: 65, social: -20, authority: -55, identity: -10, foreign: -30 },
    sourceIds: ['openTextbook', 'sepLiberalism', 'ches'],
  },
  {
    id: 'social-liberalism',
    canonicalName: 'Social liberalism',
    aliases: ['modern liberalism', 'welfare liberalism', 'progressive liberalism'],
    labelType: 'ideology',
    family: 'Liberal traditions',
    region: 'Europe / North America',
    period: '19th century → present',
    status: 'active',
    summary: 'Liberal rights and personal autonomy combined with public action to expand equal opportunity and provide social protection.',
    differences: 'It accepts a more active state than classical liberalism while remaining distinct from democratic socialism because private ownership and markets remain central.',
    axisPositions: { economic: -25, social: -60, authority: -35, identity: -30, foreign: 0 },
    sourceIds: ['openTextbook', 'sepLiberalism', 'ches'],
  },
  {
    id: 'conservatism',
    canonicalName: 'Conservatism',
    aliases: ['traditional conservatism', 'Burkean conservatism', 'one-nation conservatism'],
    labelType: 'ideology',
    family: 'Conservative & reactionary traditions',
    region: 'Europe / North America',
    period: '18th century → present',
    status: 'active',
    summary: 'A family that values inherited institutions, continuity, practical judgment, and gradual rather than abstractly engineered change.',
    differences: 'Conservatism is not identical to nationalism, authoritarianism, or laissez-faire economics; conservative traditions differ sharply on each of those questions.',
    axisPositions: { economic: 25, social: 65, authority: 40, identity: 50, foreign: 15 },
    sourceIds: ['openTextbook', 'sepConservatism'],
  },
  {
    id: 'democratic-socialism',
    canonicalName: 'Democratic socialism',
    aliases: ['democratic socialist tradition', 'ethical socialism'],
    labelType: 'ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Americas',
    period: '19th century → present',
    status: 'active',
    summary: 'A socialist tradition seeking substantial economic equality and social ownership through democratic participation and civil liberties.',
    differences: 'It differs from social democracy in the desired long-term role of ownership and markets, and from Marxism-Leninism in its rejection of one-party coercive rule as a necessary route.',
    axisPositions: { economic: -65, social: -45, authority: -20, identity: -25, foreign: -15 },
    sourceIds: ['openTextbook', 'sepSocialism', 'manifesto'],
  },
  {
    id: 'social-democracy',
    canonicalName: 'Social democracy',
    aliases: ['social democratic reformism', 'Nordic social democracy'],
    labelType: 'ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Americas',
    period: 'Late 19th century → present',
    status: 'active',
    summary: 'A reformist tradition using democratic institutions, regulated markets, welfare provision, and collective bargaining to reduce inequality.',
    differences: 'Modern social democracy generally preserves a predominantly private mixed economy, distinguishing it from democratic socialism’s stronger social-ownership ambitions.',
    axisPositions: { economic: -55, social: -45, authority: -20, identity: -20, foreign: -15 },
    sourceIds: ['openTextbook', 'sepSocialism', 'ches'],
  },
  {
    id: 'marxism-leninism',
    canonicalName: 'Marxism–Leninism',
    aliases: ['state communism', 'Leninist communism', 'party-state communism'],
    labelType: 'sub-ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Asia / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A revolutionary communist tradition organized around a vanguard party, a transition led by the state, and collective ownership of major productive assets.',
    differences: 'It should not be used as a synonym for all socialism or communism; council communism, anarcho-communism, and democratic socialism reject important parts of the Leninist model.',
    axisPositions: { economic: -90, social: -10, authority: 85, identity: -15, foreign: 45 },
    sourceIds: ['openTextbook', 'sepSocialism', 'manifesto'],
  },
  {
    id: 'council-communism',
    canonicalName: 'Council communism',
    aliases: ['left communism', 'workers’ council communism'],
    labelType: 'sub-ideology',
    family: 'Socialist & communist traditions',
    region: 'Europe / Global',
    period: '20th century → present',
    status: 'historical',
    summary: 'A communist current that places workers’ councils and direct workplace democracy above centralized party leadership.',
    differences: 'It shares an anti-capitalist economic goal with Marxism-Leninism but rejects the Leninist party-state as a vehicle for emancipation.',
    axisPositions: { economic: -80, social: -25, authority: -70, identity: -25, foreign: -35 },
    sourceIds: ['sepSocialism', 'manifesto'],
  },
  {
    id: 'anarcho-communism',
    canonicalName: 'Anarcho-communism',
    aliases: ['libertarian communism', 'anarchist communism'],
    labelType: 'sub-ideology',
    family: 'Anarchist traditions',
    region: 'Europe / Americas / Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A stateless communist tradition favoring common ownership, voluntary association, and decentralized self-management.',
    differences: 'Unlike Marxism-Leninism, it treats a centralized transitional state as incompatible with its goal; unlike anarcho-capitalism, it rejects private ownership of productive resources.',
    axisPositions: { economic: -85, social: -55, authority: -90, identity: -45, foreign: -50 },
    sourceIds: ['sepSocialism', 'sepAnarchism'],
  },
  {
    id: 'mutualism',
    canonicalName: 'Mutualism',
    aliases: ['Proudhonian mutualism', 'mutualist anarchism'],
    labelType: 'sub-ideology',
    family: 'Anarchist traditions',
    region: 'Europe / Americas',
    period: '19th century → present',
    status: 'revived',
    summary: 'An anti-authoritarian tradition centered on reciprocal exchange, federated association, and forms of possession distinct from both state ownership and absentee capitalism.',
    differences: 'It occupies a different economic position from both anarcho-communism and anarcho-capitalism, despite sharing a strong suspicion of centralized state power.',
    axisPositions: { economic: 0, social: -25, authority: -65, identity: -30, foreign: -45 },
    sourceIds: ['sepAnarchism', 'sepLibertarianism'],
  },
  {
    id: 'anarcho-capitalism',
    canonicalName: 'Anarcho-capitalism',
    aliases: ['market anarchism', 'libertarian anarchism'],
    labelType: 'sub-ideology',
    family: 'Liberal traditions',
    region: 'North America / Europe',
    period: '20th century → present',
    status: 'active',
    summary: 'A radical market-libertarian position that seeks to replace the state with voluntary, contractual, and privately provided institutions.',
    differences: 'It shares anti-state commitments with anarchist traditions but rejects their common-ownership or anti-capitalist economics; it is not equivalent to every free-market or libertarian view.',
    axisPositions: { economic: 95, social: -35, authority: -95, identity: -35, foreign: -65 },
    sourceIds: ['sepAnarchism', 'sepLibertarianism'],
  },
  {
    id: 'fascism',
    canonicalName: 'Fascism',
    aliases: ['Italian Fascism', 'fascist corporatism'],
    labelType: 'ideology',
    family: 'Fascist & ultranationalist traditions',
    region: 'Europe / Global',
    period: '20th century → present',
    status: 'historical',
    summary: 'An ultranationalist and authoritarian family emphasizing organic national unity, hierarchy, political mobilization, and subordinated individual rights.',
    differences: 'Fascism can use private property or corporatist institutions, so it should not be reduced to either socialism or a simple free-market position.',
    axisPositions: { economic: -15, social: 85, authority: 95, identity: 95, foreign: 90 },
    sourceIds: ['openTextbook', 'sepFascism'],
    warning: 'Historical-analytical entry; inclusion does not imply endorsement.',
  },
  {
    id: 'national-socialism',
    canonicalName: 'National Socialism',
    aliases: ['Nazism', 'Nazi ideology'],
    labelType: 'ideology',
    family: 'Fascist & ultranationalist traditions',
    region: 'Germany / Europe',
    period: '1920s–1945',
    status: 'historical',
    summary: 'The racial-totalitarian ideology of the Nazi movement, combining extreme ethnic hierarchy, dictatorship, mass mobilization, and expansionist war.',
    differences: 'The word “socialism” in the name does not make Nazism part of the socialist tradition; its racial hierarchy and totalizing nationalism are central to its historical meaning.',
    axisPositions: { economic: -20, social: 95, authority: 100, identity: 100, foreign: 100 },
    sourceIds: ['openTextbook', 'sepFascism', 'ushmmFascism'],
    warning: 'Historical-analytical entry concerning a genocidal regime; inclusion does not imply endorsement.',
  },
  {
    id: 'national-conservatism',
    canonicalName: 'National conservatism',
    aliases: ['sovereigntist conservatism', 'conservative nationalism'],
    labelType: 'sub-ideology',
    family: 'Conservative & reactionary traditions',
    region: 'Europe / Americas / Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A conservative family placing sovereignty, cultural continuity, national institutions, and border control at the center of political legitimacy.',
    differences: 'It differs from ethnic nationalism when national membership is civic or institutional, and from fascism when it retains pluralist or constitutional commitments.',
    axisPositions: { economic: 30, social: 70, authority: 50, identity: 85, foreign: 35 },
    sourceIds: ['sepConservatism', 'sepNationalism', 'ches'],
  },
  {
    id: 'civic-nationalism',
    canonicalName: 'Civic nationalism',
    aliases: ['liberal nationalism', 'constitutional patriotism'],
    labelType: 'identity project',
    family: 'Nationalist & identity traditions',
    region: 'Europe / Americas / Global',
    period: '18th century → present',
    status: 'active',
    summary: 'A form of national belonging based primarily on shared citizenship, political principles, and institutions rather than ancestry alone.',
    differences: 'It remains a form of nationalism, even when inclusive; internationalism and civic nationalism can coexist, while ethnic nationalism defines belonging more narrowly.',
    axisPositions: { economic: 0, social: 10, authority: 10, identity: 55, foreign: 10 },
    sourceIds: ['sepNationalism', 'openTextbook'],
  },
  {
    id: 'ethnic-nationalism',
    canonicalName: 'Ethnic nationalism',
    aliases: ['ethnonationalism', 'cultural nationalism'],
    labelType: 'identity project',
    family: 'Nationalist & identity traditions',
    region: 'Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A form of nationalism that defines the nation substantially through ancestry, ethnicity, language, religion, or inherited culture.',
    differences: 'It is not automatically identical to fascism or authoritarianism, but exclusionary variants can overlap with both and should be described with evidence.',
    axisPositions: { economic: 15, social: 60, authority: 45, identity: 95, foreign: 30 },
    sourceIds: ['sepNationalism', 'openTextbook'],
  },
  {
    id: 'anti-colonial-nationalism',
    canonicalName: 'Anti-colonial nationalism',
    aliases: ['national liberation', 'decolonizing nationalism'],
    labelType: 'movement',
    family: 'Nationalist & identity traditions',
    region: 'Africa / Asia / Middle East / Americas',
    period: '19th century → present',
    status: 'active',
    summary: 'National liberation projects seeking self-determination, sovereignty, and the end of foreign rule or colonial domination.',
    differences: 'It describes a political objective and historical situation rather than a single economic or social programme; movements within it can be liberal, socialist, religious, or authoritarian.',
    axisPositions: { economic: -25, social: -10, authority: 15, identity: 75, foreign: -5 },
    sourceIds: ['openTextbook', 'sepNationalism'],
  },
  {
    id: 'pan-africanism',
    canonicalName: 'Pan-Africanism',
    aliases: ['African continental solidarity', 'Black internationalism'],
    labelType: 'movement',
    family: 'Nationalist & identity traditions',
    region: 'Africa / African diaspora',
    period: '19th century → present',
    status: 'active',
    summary: 'A family of movements emphasizing solidarity, liberation, and political cooperation among African peoples and the African diaspora.',
    differences: 'It can combine nationalism with internationalism: the object of solidarity is transnational, so it should not be collapsed into a single nation-state nationalism.',
    axisPositions: { economic: -25, social: -30, authority: 10, identity: 65, foreign: -10 },
    sourceIds: ['openTextbook', 'panAfricanism'],
  },
  {
    id: 'pan-arabism',
    canonicalName: 'Pan-Arabism',
    aliases: ['Arab nationalism', 'Arab unity'],
    labelType: 'identity project',
    family: 'Islamic & Middle Eastern traditions',
    region: 'Middle East / North Africa',
    period: '19th century → present',
    status: 'active',
    summary: 'A transnational identity project seeking political or cultural unity among Arabic-speaking peoples.',
    differences: 'Pan-Arabism is not synonymous with Islamism: it can be secular, socialist, monarchist, or otherwise ideologically varied.',
    axisPositions: { economic: -20, social: 25, authority: 45, identity: 70, foreign: 15 },
    sourceIds: ['openTextbook', 'sepNationalism'],
  },
  {
    id: 'islamism',
    canonicalName: 'Islamism',
    aliases: ['political Islam', 'Islamic political activism'],
    labelType: 'identity project',
    family: 'Islamic & Middle Eastern traditions',
    region: 'Middle East / North Africa / South Asia / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A diverse family of projects that treat Islam as a significant source of political order, law, identity, or public governance.',
    differences: 'Islamism is not identical to Islam, Muslim identity, Salafism, or jihadism; its movements range from electoral reformism to revolutionary and militant currents.',
    axisPositions: { economic: -20, social: 65, authority: 70, identity: 60, foreign: 25 },
    sourceIds: ['openTextbook', 'sepNationalism'],
  },
  {
    id: 'confucian-political-thought',
    canonicalName: 'Confucian political thought',
    aliases: ['Confucianism', 'Confucian statecraft', 'ru tradition'],
    labelType: 'worldview',
    family: 'Chinese political thought',
    region: 'China / East Asia',
    period: 'Ancient → present',
    status: 'revived',
    summary: 'A political tradition emphasizing moral cultivation, social roles, education, ritual order, and government legitimacy through good governance.',
    differences: 'It is a broad ethical and political tradition rather than a modern party ideology, and historical Confucian states varied in institutions and economic policy.',
    axisPositions: { economic: 5, social: 65, authority: 55, identity: 20, foreign: 15 },
    sourceIds: ['openTextbook', 'sepConfucianism'],
  },
  {
    id: 'legalism',
    canonicalName: 'Chinese Legalism',
    aliases: ['fa tradition', 'Fajia'],
    labelType: 'tradition',
    family: 'Chinese political thought',
    region: 'China / East Asia',
    period: 'Warring States → imperial China',
    status: 'historical',
    summary: 'A classical Chinese statecraft tradition emphasizing clear laws, administrative technique, rewards, punishments, and concentrated state capacity.',
    differences: 'Legalism is an analytical tradition of governance, not a direct synonym for modern authoritarianism; its historical concepts do not map neatly onto every contemporary regime.',
    axisPositions: { economic: 15, social: 35, authority: 100, identity: 15, foreign: 40 },
    sourceIds: ['sepLegalism', 'openTextbook'],
  },
  {
    id: 'green-politics',
    canonicalName: 'Green politics',
    aliases: ['ecologism', 'political ecology', 'Green ideology'],
    labelType: 'ideology',
    family: 'Green, feminist & liberation traditions',
    region: 'Europe / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A family prioritizing ecological limits, sustainability, environmental justice, and political participation in response to environmental crises.',
    differences: 'Green politics is internally divided over markets, growth, technology, state authority, and social change; ecology alone does not determine the other four axes.',
    axisPositions: { economic: -20, social: -50, authority: -25, identity: -35, foreign: -25 },
    sourceIds: ['openTextbook', 'ches'],
  },
  {
    id: 'feminism',
    canonicalName: 'Feminism',
    aliases: ['feminist politics', 'women’s liberation'],
    labelType: 'ideology',
    family: 'Green, feminist & liberation traditions',
    region: 'Global',
    period: '18th century → present',
    status: 'active',
    summary: 'A diverse family of theories and movements concerned with gendered power, equality, autonomy, and the transformation of social institutions.',
    differences: 'Liberal, socialist, radical, conservative, Black, Indigenous, Islamic, and intersectional feminisms can disagree substantially about economics, authority, religion, and strategy.',
    axisPositions: { economic: -20, social: -65, authority: -45, identity: -40, foreign: -5 },
    sourceIds: ['openTextbook', 'sepFeminism'],
  },
  {
    id: 'populism',
    canonicalName: 'Populism',
    aliases: ['people-centrism', 'anti-elite politics', 'national populism'],
    labelType: 'analytical category',
    family: 'Populist & leader-centered labels',
    region: 'Global',
    period: '19th century → present',
    status: 'active',
    summary: 'A thin and flexible political style or ideology that frames politics as a struggle between a morally unified people and a corrupt elite.',
    differences: 'Populism is not a complete economic or social programme: left and right populists can occupy opposite positions on markets, identity, and social values.',
    axisPositions: { economic: null, social: null, authority: 35, identity: 50, foreign: null },
    sourceIds: ['openTextbook', 'sepPopulism'],
  },
  {
    id: 'neoliberalism',
    canonicalName: 'Neoliberalism',
    aliases: ['market-oriented reform', 'new liberalism'],
    labelType: 'policy doctrine',
    family: 'Liberal traditions',
    region: 'Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A contested label for policy and intellectual currents favoring competition, market coordination, fiscal restraint, and a reconfigured rather than absent state.',
    differences: 'Its meaning is disputed and varies between self-description and criticism; it should not be treated as a precise synonym for classical liberalism or libertarianism.',
    axisPositions: { economic: 80, social: -20, authority: -15, identity: -15, foreign: 10 },
    sourceIds: ['openTextbook', 'sepLiberalism', 'ches'],
  },
  {
    id: 'ordoliberalism',
    canonicalName: 'Ordoliberalism',
    aliases: ['German liberalism', 'social-market liberalism'],
    labelType: 'policy doctrine',
    family: 'Liberal traditions',
    region: 'Germany / Europe',
    period: '20th century → present',
    status: 'active',
    summary: 'A liberal tradition holding that the state must establish and enforce a competitive order rather than simply withdraw from the economy.',
    differences: 'It is more institutionally interventionist than laissez-faire liberalism while remaining committed to market competition and private ownership.',
    axisPositions: { economic: 55, social: 0, authority: 15, identity: 0, foreign: 5 },
    sourceIds: ['openTextbook', 'sepLiberalism'],
  },
  {
    id: 'gaullism',
    canonicalName: 'Gaullism',
    aliases: ['Gaullist nationalism', 'French grandeur'],
    labelType: 'leader doctrine',
    family: 'Populist & leader-centered labels',
    region: 'France / Europe',
    period: '1940s → present',
    status: 'revived',
    summary: 'A French state-national tradition emphasizing executive authority, national independence, strategic autonomy, and a strong role for the state.',
    differences: 'Gaullism combines elements that do not fit a simple left-right label: social protection, state planning, conservative social currents, and sovereign foreign policy.',
    axisPositions: { economic: 25, social: 35, authority: 65, identity: 85, foreign: 50 },
    sourceIds: ['sepNationalism', 'foreignPolicy'],
  },
  {
    id: 'decolonialism',
    canonicalName: 'Decolonialism',
    aliases: ['decolonial thought', 'coloniality critique'],
    labelType: 'analytical tradition',
    family: 'Green, feminist & liberation traditions',
    region: 'Latin America / Global',
    period: '20th century → present',
    status: 'active',
    summary: 'A family of critical approaches examining how colonial power, knowledge hierarchies, race, and global political economy persist after formal empire.',
    differences: 'It is a critical framework rather than one unified governing programme; it can inform anti-colonial, Indigenous, feminist, socialist, and pluralist projects.',
    axisPositions: { economic: -35, social: -35, authority: -30, identity: 35, foreign: -20 },
    sourceIds: ['openTextbook', 'sepNationalism'],
  },
];

export { TAXONOMY_LABELS };
